//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.Web.Services.ApresentadorRelatorio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVDTW-01\\SQL2012;Initial catalog=SGFDev_0005;User ID=sa;MultipleActi" +
            "veResultSets=True;Application Name=EntityFramework")]
        public string SgfDev_0000ConnectionString {
            get {
                return ((string)(this["SgfDev_0000ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SRVDTW-01\\SQL2012;Initial Catalog=SGFDev_0004;User ID=sa;Password=s20" +
            "12E;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string SGFDev_0004ConnectionString {
            get {
                return ((string)(this["SGFDev_0004ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=srv2012I;Initial Catalog=SGFDev_029material;User ID=sa;Password=S2012" +
            "@e;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string SGFDev_029materialConnectionString {
            get {
                return ((string)(this["SGFDev_029materialConnectionString"]));
            }
        }
    }
}
