//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Aditamento : TO
    {
        public Aditamento()
        {
            this.AditamentoBolsa = new HashSet<AditamentoBolsa>();
            this.Desconto = new HashSet<DescontoContrato>();
            this.TituloAditamento = new HashSet<TituloAditamento>();
        }
    
         [Key()]
         public int cd_aditamento { get; set; }
    
         [CommonEntityProperty()]
        public int cd_contrato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_aditamento { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_data_inicio { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_inicio_aditamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_dia_vcto_desconto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_nome_contrato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_tipo_aditamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_previsao_inicial { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_aula_hora { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_tipo_pagamento { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_titulos_aditamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_vcto_aditamento { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_aditivo { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_aditamento { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_parcela_titulo_aditamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_reajuste_anual { get; set; }
    
         [CommonEntityProperty()]
        public bool id_ajuste_manual { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_vencto_inicial { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_financeiro { get; set; }
    
    
        public virtual ICollection<AditamentoBolsa> AditamentoBolsa { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual NomeContrato NomeContrato { get; set; }
        public virtual ReajusteAnual ReajusteAnual { get; set; }
        public virtual UsuarioWebSGF SysUsuario { get; set; }
        public virtual ICollection<DescontoContrato> Desconto { get; set; }
        public virtual ICollection<TituloAditamento> TituloAditamento { get; set; }
        public virtual TipoFinanceiro TipoFinanceiro { get; set; }
    }
}
