//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AditamentoBolsa : TO
    {
         [Key()]
         public int cd_aditamento_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public double pc_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_comunicado_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public string dc_validade_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_motivo_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aditamento { get; set; }
    
    
        public virtual MotivoBolsa MotivoBolsa { get; set; }
        public virtual Aditamento Aditamento { get; set; }
    }
}
