//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AlunoAulaReposicao : TO
    {
         [Key()]
         public int cd_aluno_aula_reposicao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aula_reposicao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public byte id_participacao { get; set; }
    
         [CommonEntityProperty()]
        public string tx_observacao_aluno_aula { get; set; }
    
    
        public virtual Aluno Aluno { get; set; }
        public virtual AulaReposicao AulaReposicao { get; set; }
    }
}
