//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno : TO
    {
        public Aluno()
        {
            this.AtividadeExtraAluno = new HashSet<AtividadeAluno>();
            this.AlunosMotivosMatricula = new HashSet<AlunoMotivoMatricula>();
            this.AlunoFollowUp = new HashSet<FollowUp>();
            this.AlunoTurma = new HashSet<AlunoTurma>();
            this.AlunoAvaliacao = new HashSet<AvaliacaoAluno>();
            this.Contratos = new HashSet<Contrato>();
            this.HistoricoAluno = new HashSet<HistoricoAluno>();
            this.AlunoEvento = new HashSet<AlunoEvento>();
            this.PoliticasAluno = new HashSet<PoliticaAluno>();
            this.AulasPersonalizadaAluno = new HashSet<AulaPersonalizadaAluno>();
            this.Movimento = new HashSet<Movimento>();
            this.ReajustesAlunos = new HashSet<ReajusteAluno>();
            this.ReajustesTitulos = new HashSet<ReajusteTitulo>();
            this.T_CONTROLE_FALTAS_ALUNO = new HashSet<ControleFaltasAluno>();
            this.AlunoAulaReposicao = new HashSet<AlunoAulaReposicao>();
            this.AlunoRestricao = new HashSet<AlunoRestricao>();
            this.MensagemAvaliacaoAluno = new HashSet<MensagemAvaliacaoAluno>();
            this.TransferenciaAlunoDestino = new HashSet<TransferenciaAluno>();
            this.TransferenciaAlunoOrigem = new HashSet<TransferenciaAluno>();
            this.FichaSaude = new HashSet<FichaSaude>();
        }
    
         [Key()]
         public int cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_aluno { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_midia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_escolaridade { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario_atendente { get; set; }
    
         [CommonEntityProperty()]
        public bool id_aluno_ativo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_prospect { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_contato { get; set; }
    
    
        public virtual Escola EscolaAluno { get; set; }
        public virtual Escolaridade EscolaridadeAluno { get; set; }
        public virtual Midia MidiaAluno { get; set; }
        public virtual ICollection<AtividadeAluno> AtividadeExtraAluno { get; set; }
        public virtual UsuarioWebSGF Atendente { get; set; }
        public virtual PessoaFisicaSGF AlunoPessoaFisica { get; set; }
        public virtual AlunoBolsa Bolsa { get; set; }
        public virtual ICollection<AlunoMotivoMatricula> AlunosMotivosMatricula { get; set; }
        public virtual ICollection<FollowUp> AlunoFollowUp { get; set; }
        public virtual ICollection<AlunoTurma> AlunoTurma { get; set; }
        public virtual ICollection<AvaliacaoAluno> AlunoAvaliacao { get; set; }
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual ICollection<HistoricoAluno> HistoricoAluno { get; set; }
        public virtual ICollection<AlunoEvento> AlunoEvento { get; set; }
        public virtual ICollection<PoliticaAluno> PoliticasAluno { get; set; }
        public virtual Prospect Prospect { get; set; }
        public virtual ICollection<AulaPersonalizadaAluno> AulasPersonalizadaAluno { get; set; }
        public virtual ICollection<Movimento> Movimento { get; set; }
        public virtual ICollection<ReajusteAluno> ReajustesAlunos { get; set; }
        public virtual ICollection<ReajusteTitulo> ReajustesTitulos { get; set; }
        public virtual ICollection<ControleFaltasAluno> T_CONTROLE_FALTAS_ALUNO { get; set; }
        public virtual ICollection<AlunoAulaReposicao> AlunoAulaReposicao { get; set; }
        public virtual ICollection<AlunoRestricao> AlunoRestricao { get; set; }
        public virtual ICollection<MensagemAvaliacaoAluno> MensagemAvaliacaoAluno { get; set; }
        public virtual ICollection<TransferenciaAluno> TransferenciaAlunoDestino { get; set; }
        public virtual ICollection<TransferenciaAluno> TransferenciaAlunoOrigem { get; set; }
        public virtual ICollection<FichaSaude> FichaSaude { get; set; }
    }
}
