//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AlunoRestricao : TO
    {
         [Key()]
         public int cd_aluno_resticao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public int cd_orgao_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_inicio_restricao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_final_restricao { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_cadastro { get; set; }
    
    
        public virtual Aluno Aluno { get; set; }
        public virtual UsuarioWebSGF UsuarioWebSgf { get; set; }
        public virtual OrgaoFinanceiro OrgaoFinanceiro { get; set; }
    }
}
