//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AtividadeRecorrencia : TO
    {
        public AtividadeRecorrencia()
        {
            this.AtividadeExtra = new HashSet<AtividadeExtra>();
        }
    
         [Key()]
         public int cd_atividade_recorrencia { get; set; }
    
         [CommonEntityProperty()]
        public int cd_atividade_extra { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_recorrencia { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_frequencia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_limite { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_eventos { get; set; }
    
    
        public virtual ICollection<AtividadeExtra> AtividadeExtra { get; set; }
    }
}
