//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AtividadeProspect : TO
    {
         [Key()]
         public int cd_atividade_prospect { get; set; }
    
         [CommonEntityProperty()]
        public int cd_atividade_extra { get; set; }
    
         [CommonEntityProperty()]
        public int cd_prospect { get; set; }
    
         [CommonEntityProperty()]
        public bool ind_participacao { get; set; }
    
         [CommonEntityProperty()]
        public string txt_obs_atividade_propspect { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_participacao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_email_enviado { get; set; }
    
    
        public virtual AtividadeExtra AtividadeExtra { get; set; }
        public virtual Prospect Prospect { get; set; }
    }
}
