//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AtividadeExtra : TO
    {
        public AtividadeExtra()
        {
            this.AtividadeAluno = new HashSet<AtividadeAluno>();
            this.AtividadeCurso = new HashSet<AtividadeCurso>();
            this.AtividadeEscolaAtividade = new HashSet<AtividadeEscolaAtividade>();
            this.AtividadeProspect = new HashSet<AtividadeProspect>();
        }
    
         [Key()]
         public int cd_atividade_extra { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_atividade_extra { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_atividade_extra { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan hh_inicial { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan hh_final { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_vagas { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public int cd_funcionario { get; set; }
    
         [CommonEntityProperty()]
        public bool ind_carga_horaria { get; set; }
    
         [CommonEntityProperty()]
        public bool ind_pagar_professor { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_atividade { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario_atendente { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_sala { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public bool id_calendario_academico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hr_limite_academico { get; set; }
    
         [CommonEntityProperty()]
        public bool id_email_enviado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_atividade_recorrrencia { get; set; }
    
    
        public virtual ICollection<AtividadeAluno> AtividadeAluno { get; set; }
        public virtual FuncionarioSGF Funcionario { get; set; }
        public virtual TipoAtividadeExtra TipoAtividadeExtra { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual UsuarioWebSGF AtividadeSysUsuario { get; set; }
        public virtual Sala AtividadeSala { get; set; }
        public virtual Escola AtividadeEscola { get; set; }
        public virtual ICollection<AtividadeCurso> AtividadeCurso { get; set; }
        public virtual ICollection<AtividadeEscolaAtividade> AtividadeEscolaAtividade { get; set; }
        public virtual ICollection<AtividadeProspect> AtividadeProspect { get; set; }
        public virtual AtividadeRecorrencia AtividadeRecorrencia { get; set; }
    }
}
