//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AulaPersonalizadaAluno : TO
    {
         [Key()]
         public int cd_aula_personalizada_aluno { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aula_personalizada { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public bool id_aula_dada { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_aula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_diario_aula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hh_inicial_aluno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hh_final_aluno { get; set; }
    
    
        public virtual Aluno Aluno { get; set; }
        public virtual AulaPersonalizada AulaPersonalizada { get; set; }
        public virtual DiarioAula DiarioAula { get; set; }
    }
}
