//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AulaPersonalizada : TO
    {
        public AulaPersonalizada()
        {
            this.AulaPersonalizadaAlunos = new HashSet<AulaPersonalizadaAluno>();
        }
    
         [Key()]
         public int cd_aula_personalizada { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_aula_personalizada { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan hh_inicial { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan hh_final { get; set; }
    
         [CommonEntityProperty()]
        public int cd_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public int cd_turma_personalizada { get; set; }
    
    
        public virtual Escola Empresa { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Turma Turma { get; set; }
        public virtual ICollection<AulaPersonalizadaAluno> AulaPersonalizadaAlunos { get; set; }
    }
}
