//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AulaReposicao : TO
    {
        public AulaReposicao()
        {
            this.AlunoAulaReposicao = new HashSet<AlunoAulaReposicao>();
        }
    
         [Key()]
         public int cd_aula_reposicao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_atendente { get; set; }
    
         [CommonEntityProperty()]
        public int cd_professor { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_aula_reposicao { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan dh_inicial_evento { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan dh_final_evento { get; set; }
    
         [CommonEntityProperty()]
        public bool id_carga_horaria { get; set; }
    
         [CommonEntityProperty()]
        public bool id_pagar_professor { get; set; }
    
         [CommonEntityProperty()]
        public string tx_observacao_aula { get; set; }
    
         [CommonEntityProperty()]
        public int cd_turma { get; set; }
    
         [CommonEntityProperty()]
        public int cd_sala { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_turma_destino { get; set; }
    
    
        public virtual ICollection<AlunoAulaReposicao> AlunoAulaReposicao { get; set; }
        public virtual UsuarioWebSGF UsuarioWebSGF { get; set; }
        public virtual Escola Escola { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual Turma Turma { get; set; }
        public virtual Turma TurmaDestino { get; set; }
    }
}
