//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoParticipacaoVinc : TO
    {
         [Key()]
         public int cd_avaliacao_participacao_vinc { get; set; }
    
         [CommonEntityProperty()]
        public int cd_avaliacao_participacao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_participacao_avaliacao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_avaliacao_participacao_ativa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_ordem { get; set; }
    
    
        public virtual AvaliacaoParticipacao AvaliacaoParticipacao { get; set; }
        public virtual Escola Empresa { get; set; }
        public virtual Participacao ParticipacaoAvaliacao { get; set; }
    }
}
