//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoAluno : TO
    {
        public AvaliacaoAluno()
        {
            this.AvaliacoesAlunoParticipacao = new HashSet<AvaliacaoAlunoParticipacao>();
        }
    
         [Key()]
         public int cd_avaliacao_aluno { get; set; }
    
         [CommonEntityProperty()]
        public int cd_avaliacao_turma { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_conceito { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_avalicao_aluno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> nm_nota_aluno { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_nota_aluno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_segunda_prova { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> nm_nota_aluno_2 { get; set; }
    
    
        public virtual Aluno Aluno { get; set; }
        public virtual AvaliacaoTurma AvaliacaoTurma { get; set; }
        public virtual Conceito Conceito { get; set; }
        public virtual ICollection<AvaliacaoAlunoParticipacao> AvaliacoesAlunoParticipacao { get; set; }
    }
}
