//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class BaixaTitulo : TO
    {
        public BaixaTitulo()
        {
            this.ContaCorrente = new HashSet<ContaCorrente>();
            this.ChequeBaixa = new HashSet<ChequeBaixa>();
        }
    
         [Key()]
         public int cd_baixa_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tran_finan { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_liquidacao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_local_movto { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_baixa_titulo { get; set; }
    
         [CommonEntityProperty()]
        public bool id_baixa_processada { get; set; }
    
         [CommonEntityProperty()]
        public bool id_baixa_parcial { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_dias_float { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_liquidacao_baixa { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_juros_baixa { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_baixa { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_principal_baixa { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_juros_calculado { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_multa_calculada { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desc_multa_baixa { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desc_juros_baixa { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_multa_baixa { get; set; }
    
         [CommonEntityProperty()]
        public double pc_pontualidade { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_baixa { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_baixa_calculado { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_baixa_saldo_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int nm_recibo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_politica_desconto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_taxa_cartao { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_valor_troco { get; set; }
    
    
        public virtual TipoLiquidacao TipoLiquidacao { get; set; }
        public virtual LocalMovto LocalMovimento { get; set; }
        public virtual Titulo Titulo { get; set; }
        public virtual TransacaoFinanceira TransacaoFinanceira { get; set; }
        public virtual ICollection<ContaCorrente> ContaCorrente { get; set; }
        public virtual PoliticaDesconto PoliticaDesconto { get; set; }
        public virtual ICollection<ChequeBaixa> ChequeBaixa { get; set; }
        public virtual UsuarioWebSGF SysUsuario { get; set; }
    }
}
