//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class BaixaAutomatica : TO
    {
        public BaixaAutomatica()
        {
            this.TitulosBaixaAutomatica = new HashSet<TitulosBaixaAutomatica>();
        }
    
         [Key()]
         public int cd_baixa_automatica { get; set; }
    
         [CommonEntityProperty()]
        public int cd_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_local_movto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_cartao_credito { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_inicial { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_final { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dh_baixa_automatica { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo { get; set; }
    
         [CommonEntityProperty()]
        public bool id_trocar_local { get; set; }
    
         [CommonEntityProperty()]
        public bool id_processado { get; set; }
    
    
        public virtual Escola Empresa { get; set; }
        public virtual LocalMovto LocalMovto { get; set; }
        public virtual LocalMovto LocalMovto1 { get; set; }
        public virtual UsuarioWebSGF SysUsuario { get; set; }
        public virtual ICollection<TitulosBaixaAutomatica> TitulosBaixaAutomatica { get; set; }
    }
}
