//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Banco : TO
    {
        public Banco()
        {
            this.LocalMovimento = new HashSet<LocalMovto>();
            this.CarteirasCnab = new HashSet<CarteiraCnab>();
            this.Cheques = new HashSet<Cheque>();
        }
    
         [Key()]
         public int cd_banco { get; set; }
    
         [CommonEntityProperty()]
        public string no_banco { get; set; }
    
         [CommonEntityProperty()]
        public string nm_banco { get; set; }
    
    
        public virtual ICollection<LocalMovto> LocalMovimento { get; set; }
        public virtual ICollection<CarteiraCnab> CarteirasCnab { get; set; }
        public virtual ICollection<Cheque> Cheques { get; set; }
    }
}
