//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarioEvento : TO
    {
         [Key()]
         public int cd_calendario_evento { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public string dc_titulo_evento { get; set; }
    
         [CommonEntityProperty()]
        public string dc_desc_evento { get; set; }
    
         [CommonEntityProperty()]
        public bool id_ativo { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_inicial_evento { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_final_evento { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan hh_inicial_evento { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan hh_final_evento { get; set; }
    
    
        public virtual Escola Empresa { get; set; }
    }
}
