//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class CargaProfessor : TO
    {
         [Key()]
         public int cd_carga_professor { get; set; }
    
         [CommonEntityProperty()]
        public int cd_escola { get; set; }
    
         [CommonEntityProperty()]
        public short nm_carga_horaria { get; set; }
    
         [CommonEntityProperty()]
        public short nm_carga_professor { get; set; }
    
    }
}
