//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class CarteiraCnab : TO
    {
        public CarteiraCnab()
        {
            this.LocaisMovimento = new HashSet<LocalMovto>();
        }
    
         [Key()]
         public int cd_carteira_cnab { get; set; }
    
         [CommonEntityProperty()]
        public string no_carteira { get; set; }
    
         [CommonEntityProperty()]
        public int cd_banco { get; set; }
    
         [CommonEntityProperty()]
        public string nm_carteira { get; set; }
    
         [CommonEntityProperty()]
        public bool id_registrada { get; set; }
    
         [CommonEntityProperty()]
        public bool id_carteira_ativa { get; set; }
    
         [CommonEntityProperty()]
        public int nm_colunas { get; set; }
    
         [CommonEntityProperty()]
        public byte id_impressao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_homologado { get; set; }
    
    
        public virtual Banco Banco { get; set; }
        public virtual ICollection<LocalMovto> LocaisMovimento { get; set; }
    }
}
