//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class CFOP : TO
    {
        public CFOP()
        {
            this.ItensMovto = new HashSet<ItemMovimento>();
            this.Movimentos = new HashSet<Movimento>();
            this.TiposNF = new HashSet<TipoNotaFiscal>();
        }
    
         [Key()]
         public int cd_cfop { get; set; }
    
         [CommonEntityProperty()]
        public string dc_cfop { get; set; }
    
         [CommonEntityProperty()]
        public short nm_cfop { get; set; }
    
         [CommonEntityProperty()]
        public byte id_natureza_cfop { get; set; }
    
    
        public virtual ICollection<ItemMovimento> ItensMovto { get; set; }
        public virtual ICollection<Movimento> Movimentos { get; set; }
        public virtual ICollection<TipoNotaFiscal> TiposNF { get; set; }
    }
}
