//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque : TO
    {
        public Cheque()
        {
            this.ChequeBaixa = new HashSet<ChequeBaixa>();
            this.ChequeTransacaoFinanceira = new HashSet<ChequeTransacao>();
        }
    
         [Key()]
         public int cd_cheque { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_contrato { get; set; }
    
         [CommonEntityProperty()]
        public string no_emitente_cheque { get; set; }
    
         [CommonEntityProperty()]
        public string no_agencia_cheque { get; set; }
    
         [CommonEntityProperty()]
        public int nm_agencia_cheque { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_digito_agencia_cheque { get; set; }
    
         [CommonEntityProperty()]
        public int nm_conta_corrente_cheque { get; set; }
    
         [CommonEntityProperty()]
        public int nm_digito_cc_cheque { get; set; }
    
         [CommonEntityProperty()]
        public string nm_primeiro_cheque { get; set; }
    
         [CommonEntityProperty()]
        public int cd_banco { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_movimento { get; set; }
    
    
        public virtual Banco Banco { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Movimento Movimento { get; set; }
        public virtual ICollection<ChequeBaixa> ChequeBaixa { get; set; }
        public virtual ICollection<ChequeTransacao> ChequeTransacaoFinanceira { get; set; }
    }
}
