//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeBaixa : TO
    {
         [Key()]
         public int cd_cheque_baixa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_baixa_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_cheque { get; set; }
    
         [CommonEntityProperty()]
        public string nm_cheque { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_bom_para { get; set; }
    
    
        public virtual BaixaTitulo BaixaTitulo { get; set; }
        public virtual Cheque Cheque { get; set; }
    }
}
