//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Circular : TO
    {
         [Key()]
         public int cd_circular { get; set; }
    
         [CommonEntityProperty()]
        public short nm_ano_circular { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_mes_circular { get; set; }
    
         [CommonEntityProperty()]
        public int nm_circular { get; set; }
    
         [CommonEntityProperty()]
        public string no_circular { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_menu_circular { get; set; }
    
         [CommonEntityProperty()]
        public string no_arquivo_circular { get; set; }
    
    }
}
