//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Conceito : TO
    {
        public Conceito()
        {
            this.AvaliacaoAluno = new HashSet<AvaliacaoAluno>();
            this.AvaliacoesAlunoParticipacao = new HashSet<AvaliacaoAlunoParticipacao>();
        }
    
         [Key()]
         public int cd_conceito { get; set; }
    
         [CommonEntityProperty()]
        public string no_conceito { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_inicial_conceito { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_final_conceito { get; set; }
    
         [CommonEntityProperty()]
        public bool id_conceito_ativo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public double vl_nota_participacao { get; set; }
    
    
        public virtual Produto Produto { get; set; }
        public virtual ICollection<AvaliacaoAluno> AvaliacaoAluno { get; set; }
        public virtual ICollection<AvaliacaoAlunoParticipacao> AvaliacoesAlunoParticipacao { get; set; }
    }
}
