//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ContaCorrente : TO
    {
         [CommonEntityProperty()]
        public int cd_local_origem { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_local_destino { get; set; }
    
         [CommonEntityProperty()]
        public int cd_movimentacao_financeira { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_baixa_titulo { get; set; }
    
         [Key()]
         public int cd_conta_corrente { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dta_conta_corrente { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_movimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_conta_corrente { get; set; }
    
         [CommonEntityProperty()]
        public string dc_obs_conta_corrente { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_liquidacao { get; set; }
    
    
        public virtual BaixaTitulo BaixaTitulo { get; set; }
        public virtual Escola Empresa { get; set; }
        public virtual LocalMovto LocalMovtoDestino { get; set; }
        public virtual LocalMovto LocalMovtoOrigem { get; set; }
        public virtual PlanoConta PlanoContas { get; set; }
        public virtual MovimentacaoFinanceira MovimentacaoFinanceira { get; set; }
        public virtual TipoLiquidacao TipoLiquidacao { get; set; }
    }
}
