//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Curso : TO
    {
        public Curso()
        {
            this.ProximoCurso = new HashSet<Curso>();
            this.ProgramacaoCurso = new HashSet<ProgramacaoCurso>();
            this.CursoTabelaPreco = new HashSet<TabelaPreco>();
            this.AvaliacaoCurso = new HashSet<AvaliacaoCurso>();
            this.Turma = new HashSet<Turma>();
            this.Contratos = new HashSet<Contrato>();
            this.MalaDiretaCurso = new HashSet<MalaDiretaCurso>();
            this.ReajustesCursos = new HashSet<ReajusteCurso>();
            this.ReajustesTitutlos = new HashSet<ReajusteTitulo>();
            this.AtividadeCurso = new HashSet<AtividadeCurso>();
            this.CursoContrato = new HashSet<CursoContrato>();
            this.T_MENSAGEM_AVALIACAO = new HashSet<MensagemAvaliacao>();
            this.MateriaisDidaticos = new HashSet<ItemCurso>();
            this.T_PESSOA_FISICA = new HashSet<PessoaFisicaSGF>();
        }
    
         [Key()]
         public int cd_curso { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_proximo_curso { get; set; }
    
         [CommonEntityProperty()]
        public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public int cd_estagio { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_modalidade { get; set; }
    
         [CommonEntityProperty()]
        public string no_curso { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> nm_carga_horaria { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_vagas_curso { get; set; }
    
         [CommonEntityProperty()]
        public bool id_curso_ativo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_criterio_aprovacao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_total_nota { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> nm_faixa_etaria_minima { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_faixa_etaria_maxima { get; set; }
    
         [CommonEntityProperty()]
        public int cd_nivel { get; set; }
    
         [CommonEntityProperty()]
        public bool id_permitir_matricula { get; set; }
    
         [CommonEntityProperty()]
        public bool id_certificado { get; set; }
    
         [CommonEntityProperty()]
        public int nm_carga_maxima { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_curso_padrao { get; set; }
    
    
        public virtual ICollection<Curso> ProximoCurso { get; set; }
        public virtual Estagio Estagio { get; set; }
        public virtual Modalidade Modalidade { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual ICollection<ProgramacaoCurso> ProgramacaoCurso { get; set; }
        public virtual ICollection<TabelaPreco> CursoTabelaPreco { get; set; }
        public virtual ICollection<AvaliacaoCurso> AvaliacaoCurso { get; set; }
        public virtual ICollection<Turma> Turma { get; set; }
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual ICollection<MalaDiretaCurso> MalaDiretaCurso { get; set; }
        public virtual ICollection<ReajusteCurso> ReajustesCursos { get; set; }
        public virtual ICollection<ReajusteTitulo> ReajustesTitutlos { get; set; }
        public virtual ICollection<AtividadeCurso> AtividadeCurso { get; set; }
        public virtual Nivel Nivel { get; set; }
        public virtual ICollection<CursoContrato> CursoContrato { get; set; }
        public virtual ICollection<MensagemAvaliacao> T_MENSAGEM_AVALIACAO { get; set; }
        public virtual ICollection<ItemCurso> MateriaisDidaticos { get; set; }
        public virtual ICollection<PessoaFisicaSGF> T_PESSOA_FISICA { get; set; }
    }
}
