//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class CursoContrato : TO
    {
        public CursoContrato()
        {
            this.AlunoTurma = new HashSet<AlunoTurma>();
        }
    
         [Key()]
         public int cd_curso_contrato { get; set; }
    
         [CommonEntityProperty()]
        public int cd_contrato { get; set; }
    
         [CommonEntityProperty()]
        public int cd_curso { get; set; }
    
         [CommonEntityProperty()]
        public int cd_duracao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_responsavel { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_dia_vcto { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_mes_vcto { get; set; }
    
         [CommonEntityProperty()]
        public short nm_ano_vcto { get; set; }
    
         [CommonEntityProperty()]
        public int nm_parcelas_mensalidade { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_curso_contrato { get; set; }
    
         [CommonEntityProperty()]
        public decimal pc_desconto_contrato { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_matricula_curso { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_parcela_contrato { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_contrato { get; set; }
    
         [CommonEntityProperty()]
        public decimal pc_responsavel_contrato { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_parcela_liquida { get; set; }
    
         [CommonEntityProperty()]
        public bool id_liberar_certificado { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_curso_liquido { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_mes_curso_inicial { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> nm_ano_curso_inicial { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_mes_curso_final { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> nm_ano_curso_final { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_valor_incluso { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_incorporar_valor_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_parcelas_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_parcela_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_material_contrato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_parcela_liq_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> pc_bolsa_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_desconto_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_liquido_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_desconto_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_opcao_venda { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_financeiro_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_pessoa_responsavel_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_responsavel_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_vencimento_parcela_1 { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_regime { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_bolsa_contrato { get; set; }
    
    
        public virtual ICollection<AlunoTurma> AlunoTurma { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Duracao Duracao { get; set; }
        public virtual PessoaSGF PessoaSGF { get; set; }
        public virtual TipoFinanceiro TipoFinanceiro { get; set; }
    }
}
