//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class DescontoTituloCNAB : TO
    {
         [Key()]
         public int cd_desconto_titulo_cnab { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_titulo_cnab { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_desconto { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto { get; set; }
    
    
        public virtual TituloCnab TituloCNAB { get; set; }
    }
}
