//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Desistencia : TO
    {
        public Desistencia()
        {
            this.HistoricoAluno = new HashSet<HistoricoAluno>();
        }
    
         [Key()]
         public int cd_desistencia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_motivo_desistencia { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_desistencia { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aluno_turma { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_desistencia { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_desistencia { get; set; }
    
    
        public virtual AlunoTurma AlunoTurma { get; set; }
        public virtual MotivoDesistencia MotivoDesistencia { get; set; }
        public virtual ICollection<HistoricoAluno> HistoricoAluno { get; set; }
    }
}
