//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class DespesaTituloCnab : TO
    {
         [Key()]
         public int cd_despesa_titulo_cnab { get; set; }
    
         [CommonEntityProperty()]
        public int cd_titulo_retorno_cnab { get; set; }
    
         [CommonEntityProperty()]
        public string cd_despesa { get; set; }
    
         [CommonEntityProperty()]
        public string dc_despesa { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_despesa { get; set; }
    
    
        public virtual TituloRetornoCNAB TituloRetornoCNAB { get; set; }
    }
}
