//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class DiarioAula : TO
    {
        public DiarioAula()
        {
            this.AlunoEvento = new HashSet<AlunoEvento>();
            this.AulaPersonalizadaAluno = new HashSet<AulaPersonalizadaAluno>();
        }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_programacao_turma { get; set; }
    
         [Key()]
         public int cd_diario_aula { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_turma { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_professor { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_aula { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_professor_substituto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_sala { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_avaliacao { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_aula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_cadastro_aula { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan hr_inicial_aula { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan hr_final_aula { get; set; }
    
         [CommonEntityProperty()]
        public bool id_aula_externa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> id_status_aula { get; set; }
    
         [CommonEntityProperty()]
        public byte id_falta_professor { get; set; }
    
         [CommonEntityProperty()]
        public string dc_obs_falta { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> nm_aula_turma { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_aula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_motivo_falta { get; set; }
    
    
        public virtual ProgramacaoTurma ProgramacaoTurma { get; set; }
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Professor ProfessorSubstituto { get; set; }
        public virtual TipoAtividadeExtra TipoAtividade_Extra { get; set; }
        public virtual Escola Empresa { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual Turma Turma { get; set; }
        public virtual UsuarioWebSGF SysUsuario { get; set; }
        public virtual ICollection<AlunoEvento> AlunoEvento { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual MotivoFalta MotivoFalta { get; set; }
        public virtual ICollection<AulaPersonalizadaAluno> AulaPersonalizadaAluno { get; set; }
    }
}
