//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class DiasPolitica : TO
    {
         [Key()]
         public int cd_dias_politica { get; set; }
    
         [CommonEntityProperty()]
        public int cd_politica_desconto { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_dia_limite_politica { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> pc_desconto { get; set; }
    
    
        public virtual PoliticaDesconto DiasPoliticaDesc { get; set; }
    }
}
