//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Duracao : TO
    {
        public Duracao()
        {
            this.ProgramacaoCurso = new HashSet<ProgramacaoCurso>();
            this.DuracaoTabelaPreco = new HashSet<TabelaPreco>();
            this.Turma = new HashSet<Turma>();
            this.Contratos = new HashSet<Contrato>();
            this.CursoContrato = new HashSet<CursoContrato>();
        }
    
         [Key()]
         public int cd_duracao { get; set; }
    
         [CommonEntityProperty()]
        public string dc_duracao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_duracao_ativa { get; set; }
    
         [CommonEntityProperty()]
        public decimal nm_duracao { get; set; }
    
    
        public virtual ICollection<ProgramacaoCurso> ProgramacaoCurso { get; set; }
        public virtual ICollection<TabelaPreco> DuracaoTabelaPreco { get; set; }
        public virtual ICollection<Turma> Turma { get; set; }
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual ICollection<CursoContrato> CursoContrato { get; set; }
    }
}
