//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimo : TO
    {
         [Key()]
         public int cd_biblioteca { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_item { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_emprestimo { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_prevista_devolucao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_devolucao { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_taxa_emprestimo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_multa_emprestimo { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_biblioteca { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_renovacao { get; set; }
    
    
        public virtual Item Item { get; set; }
        public virtual PessoaSGF Pessoa { get; set; }
        public virtual Escola Escola { get; set; }
    }
}
