//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaValorServico : TO
    {
         [Key()]
         public int cd_empresa_valor_servico { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_inicio_valor { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_unitario_servico { get; set; }
    
    
        public virtual Escola Escola { get; set; }
    }
}
