//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class EnderecoSGF : TO
    {
        public EnderecoSGF()
        {
            this.PessoasEnderecoPrincipal = new HashSet<PessoaSGF>();
            this.Telefones = new HashSet<TelefoneSGF>();
        }
    
         [Key()]
         public int cd_endereco { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_loc_pais { get; set; }
    
         [CommonEntityProperty()]
        public int cd_loc_estado { get; set; }
    
         [CommonEntityProperty()]
        public int cd_loc_cidade { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_endereco { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_loc_distrito { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_loc_bairro { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_logradouro { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_loc_logradouro { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_caixa_postal { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_status_endereco { get; set; }
    
         [CommonEntityProperty()]
        public string dc_compl_endereco { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_exportado { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_endereco { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_local_geografico { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_cep { get; set; }
    
    
        public virtual ICollection<PessoaSGF> PessoasEnderecoPrincipal { get; set; }
        public virtual ICollection<TelefoneSGF> Telefones { get; set; }
        public virtual PessoaSGF Pessoa { get; set; }
        public virtual TipoEnderecoSGF TipoEndereco { get; set; }
        public virtual TipoLogradouroSGF TipoLogradouro { get; set; }
        public virtual LocalidadeSGF Bairro { get; set; }
        public virtual LocalidadeSGF Cidade { get; set; }
        public virtual LocalidadeSGF Distrito { get; set; }
        public virtual LocalidadeSGF Estado { get; set; }
        public virtual LocalidadeSGF Logradouro { get; set; }
        public virtual LocalidadeSGF Pais { get; set; }
    }
}
