//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Escolaridade : TO
    {
        public Escolaridade()
        {
            this.EscolaridadeAluno = new HashSet<Aluno>();
            this.AnoEscolar = new HashSet<AnoEscolar>();
            this.T_PESSOA_FISICA = new HashSet<PessoaFisicaSGF>();
        }
    
         [Key()]
         public int cd_escolaridade { get; set; }
    
         [CommonEntityProperty()]
        public bool id_escolaridade_ativa { get; set; }
    
         [CommonEntityProperty()]
        public string no_escolaridade { get; set; }
    
    
        public virtual ICollection<Aluno> EscolaridadeAluno { get; set; }
        public virtual ICollection<AnoEscolar> AnoEscolar { get; set; }
        public virtual ICollection<PessoaFisicaSGF> T_PESSOA_FISICA { get; set; }
    }
}
