//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Escola : PessoaJuridicaSGF
    {
        public Escola()
        {
            this.Sala = new HashSet<Sala>();
            this.Feriado = new HashSet<Feriado>();
            this.EscolaAluno = new HashSet<Aluno>();
            this.EscolaPoliticaDesc = new HashSet<PoliticaDesconto>();
            this.EscolaTurma = new HashSet<Turma>();
            this.EscolaItem = new HashSet<ItemEscola>();
            this.EscolaHorario = new HashSet<Horario>();
            this.EscolaTabelaPreco = new HashSet<TabelaPreco>();
            this.EscolaAtividade = new HashSet<AtividadeExtra>();
            this.EscolaProspect = new HashSet<Prospect>();
            this.PessoaEscola = new HashSet<PessoaEscola>();
            this.EscolaPlanoConta = new HashSet<PlanoConta>();
            this.Funcionarios = new HashSet<FuncionarioSGF>();
            this.EmpresasAntigas = new HashSet<Escola>();
            this.Contrato = new HashSet<Contrato>();
            this.Titulo = new HashSet<Titulo>();
            this.NomeContrato = new HashSet<NomeContrato>();
            this.LocalMovimento = new HashSet<LocalMovto>();
            this.DiarioAula = new HashSet<DiarioAula>();
            this.ContaCorrente = new HashSet<ContaCorrente>();
            this.Movimentos = new HashSet<Movimento>();
            this.PoliticaComercial = new HashSet<PoliticaComercial>();
            this.Kardexs = new HashSet<Kardex>();
            this.Usuarios = new HashSet<UsuarioEmpresaSGF>();
            this.Fechamentos = new HashSet<Fechamento>();
            this.EmprestimosEscola = new HashSet<Emprestimo>();
            this.TiposDescontoEscola = new HashSet<TipoDescontoEscola>();
            this.ModelosProgramacoesCursos = new HashSet<ProgramacaoCurso>();
            this.FollowUps = new HashSet<FollowUp>();
            this.FollowUpsEscola = new HashSet<FollowUpEscola>();
            this.ListasNaoInscrito = new HashSet<ListaNaoInscrito>();
            this.MalasDireta = new HashSet<MalaDireta>();
            this.AulaPersonalizada = new HashSet<AulaPersonalizada>();
            this.LogsGeral = new HashSet<LogGeral>();
            this.Grupos = new HashSet<SysGrupo>();
            this.AvaliacaoParticipacaoVinc = new HashSet<AvaliacaoParticipacaoVinc>();
            this.ReajustesAnuais = new HashSet<ReajusteAnual>();
            this.AtividadeCurso = new HashSet<AtividadeCurso>();
            this.CalendarioAcademico = new HashSet<CalendarioAcademico>();
            this.CalendarioEvento = new HashSet<CalendarioEvento>();
            this.T_BAIXA_AUTOMATICA = new HashSet<BaixaAutomatica>();
            this.AulaReposicao = new HashSet<AulaReposicao>();
            this.TurmaEscola = new HashSet<TurmaEscola>();
            this.AtividadeEscolaAtividade = new HashSet<AtividadeEscolaAtividade>();
            this.TransferenciaAlunoDestino = new HashSet<TransferenciaAluno>();
            this.TransferenciaAlunoOrigem = new HashSet<TransferenciaAluno>();
            this.EmpresaValorServico = new HashSet<EmpresaValorServico>();
            this.T_DESCONTO = new HashSet<T_DESCONTO>();
        }
    
         [CommonEntityProperty()]
        public Nullable<int> id_host { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_cliente_integracao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hr_inicial { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hr_final { get; set; }
    
         [CommonEntityProperty()]
        public bool id_escola_ativa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_empresa_integracao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_inicio { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_abertura { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_empresa { get; set; }
    
         [CommonEntityProperty()]
        public decimal nm_investimento { get; set; }
    
         [CommonEntityProperty()]
        public decimal nm_patrimonio { get; set; }
    
         [CommonEntityProperty()]
        public bool id_empresa_propria { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_dia_gerar_nfs { get; set; }
    
         [CommonEntityProperty()]
        public string nome_assinatura_certificado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_historico_sgf { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_empresa_coligada { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_dia_gerar_nf_servico { get; set; }
    
         [CommonEntityProperty()]
        public bool id_empresa_internacional { get; set; }
    
    
        public virtual ICollection<Sala> Sala { get; set; }
        public virtual ICollection<Feriado> Feriado { get; set; }
        public virtual ICollection<Aluno> EscolaAluno { get; set; }
        public virtual ICollection<PoliticaDesconto> EscolaPoliticaDesc { get; set; }
        public virtual ICollection<Turma> EscolaTurma { get; set; }
        public virtual ICollection<ItemEscola> EscolaItem { get; set; }
        public virtual ICollection<Horario> EscolaHorario { get; set; }
        public virtual ICollection<TabelaPreco> EscolaTabelaPreco { get; set; }
        public virtual ICollection<AtividadeExtra> EscolaAtividade { get; set; }
        public virtual ICollection<Prospect> EscolaProspect { get; set; }
        public virtual ICollection<PessoaEscola> PessoaEscola { get; set; }
        public virtual ICollection<PlanoConta> EscolaPlanoConta { get; set; }
        public virtual ICollection<FuncionarioSGF> Funcionarios { get; set; }
        public virtual ICollection<Escola> EmpresasAntigas { get; set; }
        public virtual Escola EmpresaAtual { get; set; }
        public virtual ICollection<Contrato> Contrato { get; set; }
        public virtual ICollection<Titulo> Titulo { get; set; }
        public virtual ICollection<NomeContrato> NomeContrato { get; set; }
        public virtual ICollection<LocalMovto> LocalMovimento { get; set; }
        public virtual ICollection<DiarioAula> DiarioAula { get; set; }
        public virtual ICollection<ContaCorrente> ContaCorrente { get; set; }
        public virtual ICollection<Movimento> Movimentos { get; set; }
        public virtual ICollection<PoliticaComercial> PoliticaComercial { get; set; }
        public virtual ICollection<Kardex> Kardexs { get; set; }
        public virtual ICollection<UsuarioEmpresaSGF> Usuarios { get; set; }
        public virtual Parametro EscolaParametro { get; set; }
        public virtual ICollection<Fechamento> Fechamentos { get; set; }
        public virtual ICollection<Emprestimo> EmprestimosEscola { get; set; }
        public virtual ICollection<TipoDescontoEscola> TiposDescontoEscola { get; set; }
        public virtual ICollection<ProgramacaoCurso> ModelosProgramacoesCursos { get; set; }
        public virtual ICollection<FollowUp> FollowUps { get; set; }
        public virtual ICollection<FollowUpEscola> FollowUpsEscola { get; set; }
        public virtual ICollection<ListaNaoInscrito> ListasNaoInscrito { get; set; }
        public virtual ICollection<MalaDireta> MalasDireta { get; set; }
        public virtual ICollection<AulaPersonalizada> AulaPersonalizada { get; set; }
        public virtual ICollection<LogGeral> LogsGeral { get; set; }
        public virtual ICollection<SysGrupo> Grupos { get; set; }
        public virtual ICollection<AvaliacaoParticipacaoVinc> AvaliacaoParticipacaoVinc { get; set; }
        public virtual ICollection<ReajusteAnual> ReajustesAnuais { get; set; }
        public virtual ICollection<AtividadeCurso> AtividadeCurso { get; set; }
        public virtual ICollection<CalendarioAcademico> CalendarioAcademico { get; set; }
        public virtual ICollection<CalendarioEvento> CalendarioEvento { get; set; }
        public virtual ICollection<BaixaAutomatica> T_BAIXA_AUTOMATICA { get; set; }
        public virtual ICollection<AulaReposicao> AulaReposicao { get; set; }
        public virtual ICollection<TurmaEscola> TurmaEscola { get; set; }
        public virtual ICollection<AtividadeEscolaAtividade> AtividadeEscolaAtividade { get; set; }
        public virtual ICollection<TransferenciaAluno> TransferenciaAlunoDestino { get; set; }
        public virtual ICollection<TransferenciaAluno> TransferenciaAlunoOrigem { get; set; }
        public virtual ICollection<EmpresaValorServico> EmpresaValorServico { get; set; }
        public virtual ICollection<T_DESCONTO> T_DESCONTO { get; set; }
    }
}
