//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Estagio : TO
    {
        public Estagio()
        {
            this.Cursos = new HashSet<Curso>();
            this.EstagioHabilitacaoProfessor = new HashSet<HabilitacaoProfessor>();
        }
    
         [Key()]
         public int cd_estagio { get; set; }
    
         [CommonEntityProperty()]
        public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public string no_estagio { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_ordem_estagio { get; set; }
    
         [CommonEntityProperty()]
        public bool id_estagio_ativo { get; set; }
    
         [CommonEntityProperty()]
        public string no_estagio_abreviado { get; set; }
    
         [CommonEntityProperty()]
        public string cor_legenda { get; set; }
    
    
        public virtual Produto Produto { get; set; }
        public virtual ICollection<Curso> Cursos { get; set; }
        public virtual ICollection<HabilitacaoProfessor> EstagioHabilitacaoProfessor { get; set; }
    }
}
