//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoCivilSGF : TO
    {
        public EstadoCivilSGF()
        {
            this.PessoasFisicas = new HashSet<PessoaFisicaSGF>();
        }
    
         [Key()]
         public int cd_estado_civil { get; set; }
    
         [CommonEntityProperty()]
        public string dc_estado_civil_masc { get; set; }
    
         [CommonEntityProperty()]
        public string dc_estado_civil_fem { get; set; }
    
    
        public virtual ICollection<PessoaFisicaSGF> PessoasFisicas { get; set; }
    }
}
