//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Evento : TO
    {
        public Evento()
        {
            this.AlunoEvento = new HashSet<AlunoEvento>();
        }
    
         [Key()]
         public int cd_evento { get; set; }
    
         [CommonEntityProperty()]
        public bool id_evento_ativo { get; set; }
    
         [CommonEntityProperty()]
        public string no_evento { get; set; }
    
    
        public virtual ICollection<AlunoEvento> AlunoEvento { get; set; }
    }
}
