//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Faq : TO
    {
         [Key()]
         public int cd_faq { get; set; }
    
         [CommonEntityProperty()]
        public string dc_faq_pergunta { get; set; }
    
         [CommonEntityProperty()]
        public string dc_faq_resposta { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_menu_faq { get; set; }
    
         [CommonEntityProperty()]
        public string no_video_faq { get; set; }
    
    }
}
