//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class FeriadoDesconsiderado : TO
    {
        public FeriadoDesconsiderado()
        {
            this.ProgramacoesTurma = new HashSet<ProgramacaoTurma>();
        }
    
         [CommonEntityProperty()]
        public int cd_turma { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_inicial { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_final { get; set; }
    
         [Key()]
         public int cd_feriado_desconsiderado { get; set; }
    
         [CommonEntityProperty()]
        public bool id_programacao_feriado { get; set; }
    
    
        public virtual Turma Turma { get; set; }
        public virtual ICollection<ProgramacaoTurma> ProgramacoesTurma { get; set; }
    }
}
