//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Feriado : TO
    {
        public Feriado()
        {
            this.Feriados = new HashSet<ProgramacaoTurma>();
        }
    
         [Key()]
         public int cod_feriado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public byte dd_feriado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> aa_feriado { get; set; }
    
         [CommonEntityProperty()]
        public byte mm_feriado { get; set; }
    
         [CommonEntityProperty()]
        public string dc_feriado { get; set; }
    
         [CommonEntityProperty()]
        public bool id_feriado_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> aa_feriado_fim { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> mm_feriado_fim { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> dd_feriado_fim { get; set; }
    
         [CommonEntityProperty()]
        public bool id_feriado_ativo { get; set; }
    
    
        public virtual Escola Escola { get; set; }
        public virtual ICollection<ProgramacaoTurma> Feriados { get; set; }
    }
}
