//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class FichaSaude : TO
    {
         [Key()]
         public int cd_ficha_saude { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_problema_saude { get; set; }
    
         [CommonEntityProperty()]
        public string dc_problema_saude { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_tratamento_medico { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tratamento_medico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_uso_medicamento { get; set; }
    
         [CommonEntityProperty()]
        public string dc_uso_medicamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_recomendacao_medica { get; set; }
    
         [CommonEntityProperty()]
        public string dc_recomendacao_medica { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_alergico { get; set; }
    
         [CommonEntityProperty()]
        public string dc_alergico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_alergico_alimento_material { get; set; }
    
         [CommonEntityProperty()]
        public string dc_alergico_alimento_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_epiletico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_epiletico_tratamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_asmatico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_asmatico_tratamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_diabetico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_depende_insulina { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_medicacao_especifica { get; set; }
    
         [CommonEntityProperty()]
        public string dc_medicacao_especifica { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> dt_hora_medicacao_especifica { get; set; }
    
         [CommonEntityProperty()]
        public string tx_informacoes_adicionais { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_plano_saude { get; set; }
    
         [CommonEntityProperty()]
        public string dc_plano_saude { get; set; }
    
         [CommonEntityProperty()]
        public string dc_nm_carteirinha_plano { get; set; }
    
         [CommonEntityProperty()]
        public string dc_categoria_plano { get; set; }
    
         [CommonEntityProperty()]
        public string dc_nome_clinica_hospital { get; set; }
    
         [CommonEntityProperty()]
        public string dc_endereco_hospital_clinica { get; set; }
    
         [CommonEntityProperty()]
        public string dc_telefone_hospital_clinica { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_aviso_emergencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_nome_pessoa_aviso_emergencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_parentesco_aviso_emergencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_telefone_residencial_aviso_emergencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_telefone_comercial_aviso_emergencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_telefone_celular_aviso_emergencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_telefone_fixo_hospital_clinica { get; set; }
    
    
        public virtual Aluno T_ALUNO { get; set; }
    }
}
