//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp : TO
    {
        public FollowUp()
        {
            this.FollowUpUsuarios = new HashSet<FollowUpUsuario>();
            this.FollowUpEscolas = new HashSet<FollowUpEscola>();
            this.FollowUpsDestino = new HashSet<FollowUp>();
            this.FollowUpsTodasRespostas = new HashSet<FollowUp>();
        }
    
         [Key()]
         public int cd_follow_up { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_prospect { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_follow_up { get; set; }
    
         [CommonEntityProperty()]
        public string dc_assunto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_escola { get; set; }
    
         [CommonEntityProperty()]
        public bool id_follow_resolvido { get; set; }
    
         [CommonEntityProperty()]
        public bool id_follow_lido { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_follow { get; set; }
    
         [CommonEntityProperty()]
        public bool id_usuario_administrador { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_acao_follow_up { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_usuario_destino { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_proximo_contato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_follow_up_pai { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_follow_up_origem { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_tipo_atendimento { get; set; }
    
         [CommonEntityProperty()]
        public bool id_email_enviado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_turma { get; set; }
    
    
        public virtual Aluno FollowUpAluno { get; set; }
        public virtual Prospect FollowUpProspect { get; set; }
        public virtual UsuarioWebSGF FollowUpUsuario { get; set; }
        public virtual AcaoFollowUp AcaoFollowUp { get; set; }
        public virtual Escola Empresa { get; set; }
        public virtual ICollection<FollowUpUsuario> FollowUpUsuarios { get; set; }
        public virtual UsuarioWebSGF UsuarioDestino { get; set; }
        public virtual ICollection<FollowUpEscola> FollowUpEscolas { get; set; }
        public virtual ICollection<FollowUp> FollowUpsDestino { get; set; }
        public virtual FollowUp FollowUpOrigem { get; set; }
        public virtual ICollection<FollowUp> FollowUpsTodasRespostas { get; set; }
        public virtual FollowUp FollowUpOrigemTodasRespostas { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
