//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpUsuario : TO
    {
         [Key()]
         public int cd_follow_usuario { get; set; }
    
         [CommonEntityProperty()]
        public int cd_follow_up { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_follow_usuario { get; set; }
    
    
        public virtual FollowUp FollowUp { get; set; }
        public virtual UsuarioWebSGF Usuario { get; set; }
    }
}
