//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionarioSGF : TO
    {
        public FuncionarioSGF()
        {
            this.AtividadeExtraFuncionario = new HashSet<AtividadeExtra>();
            this.AvaliacaoTurma = new HashSet<AvaliacaoTurma>();
            this.FuncionarioComissao = new HashSet<FuncionarioComissao>();
            this.ProdutoFuncionario = new HashSet<ProdutoFuncionario>();
        }
    
         [Key()]
         public int cd_funcionario { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_funcionario { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_admissao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_demissao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_comissionado { get; set; }
    
         [CommonEntityProperty()]
        public bool id_professor { get; set; }
    
         [CommonEntityProperty()]
        public bool id_funcionario_ativo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_salario { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_cargo { get; set; }
    
         [CommonEntityProperty()]
        public bool id_colaborador_cyber { get; set; }
    
         [CommonEntityProperty()]
        public string nome_assinatura_certificado { get; set; }
    
    
        public virtual PessoaFisicaSGF FuncionarioPessoaFisica { get; set; }
        public virtual ICollection<AtividadeExtra> AtividadeExtraFuncionario { get; set; }
        public virtual ICollection<AvaliacaoTurma> AvaliacaoTurma { get; set; }
        public virtual Escola Empresa { get; set; }
        public virtual Atividade FuncionarioAtividade { get; set; }
        public virtual ICollection<FuncionarioComissao> FuncionarioComissao { get; set; }
        public virtual ICollection<ProdutoFuncionario> ProdutoFuncionario { get; set; }
    }
}
