//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionarioComissao : TO
    {
         [Key()]
         public int cd_funcionario_comissao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_funcionario { get; set; }
    
         [CommonEntityProperty()]
        public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_comissao_matricula { get; set; }
    
         [CommonEntityProperty()]
        public double pc_comissao_matricula { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_comissao_rematricula { get; set; }
    
         [CommonEntityProperty()]
        public decimal pc_comissao_rematricula { get; set; }
    
    
        public virtual FuncionarioSGF Funcionario { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
