//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoSituacao : TO
    {
         [Key()]
         public int cd_grupo_situacao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_grupo_estoque { get; set; }
    
         [CommonEntityProperty()]
        public int cd_situacao_tributaria { get; set; }
    
         [CommonEntityProperty()]
        public byte id_regime_tributaria { get; set; }
    
    
        public virtual GrupoEstoque GrupoEstoque { get; set; }
        public virtual SituacaoTributaria SituacaoTributaria { get; set; }
    }
}
