//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoConta : TO
    {
        public GrupoConta()
        {
            this.SubGrupos = new HashSet<SubgrupoConta>();
        }
    
         [Key()]
         public int cd_grupo_conta { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_grupo_conta { get; set; }
    
         [CommonEntityProperty()]
        public string no_grupo_conta { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_ordem_grupo { get; set; }
    
    
        public virtual ICollection<SubgrupoConta> SubGrupos { get; set; }
    }
}
