//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoEstoque : TO
    {
        public GrupoEstoque()
        {
            this.Itens = new HashSet<Item>();
            this.GrupoSituacoes = new HashSet<GrupoSituacao>();
        }
    
         [Key()]
         public int cd_grupo_estoque { get; set; }
    
         [CommonEntityProperty()]
        public string no_grupo_estoque { get; set; }
    
         [CommonEntityProperty()]
        public bool id_grupo_estoque_ativo { get; set; }
    
         [CommonEntityProperty()]
        public byte id_categoria_grupo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_situacao_tributaria { get; set; }
    
         [CommonEntityProperty()]
        public bool id_eliminar_inventario { get; set; }
    
    
        public virtual ICollection<Item> Itens { get; set; }
        public virtual SituacaoTributaria SituacaoTributaria { get; set; }
        public virtual ICollection<GrupoSituacao> GrupoSituacoes { get; set; }
    }
}
