//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class HabilitacaoProfessor : TO
    {
         [CommonEntityProperty()]
        public int cd_professor { get; set; }
    
         [CommonEntityProperty()]
        public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public int cd_estagio { get; set; }
    
         [Key()]
         public int cd_habilitacao_professor { get; set; }
    
    
        public virtual Estagio Estagio { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
