//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Horario : TO
    {
        public Horario()
        {
            this.HorariosProfessores = new HashSet<HorarioProfessorTurma>();
        }
    
         [Key()]
         public int cd_horario { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_registro { get; set; }
    
         [CommonEntityProperty()]
        public byte id_origem { get; set; }
    
         [CommonEntityProperty()]
        public bool id_disponivel { get; set; }
    
         [CommonEntityProperty()]
        public byte id_dia_semana { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan dt_hora_ini { get; set; }
    
         [CommonEntityProperty()]
        public System.TimeSpan dt_hora_fim { get; set; }
    
    
        public virtual Escola Escola { get; set; }
        public virtual ICollection<HorarioProfessorTurma> HorariosProfessores { get; set; }
    }
}
