//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ImportacaoXML : TO
    {
         [Key()]
         public int cd_importacao_XML { get; set; }
    
         [CommonEntityProperty()]
        public string no_arquivo_XML { get; set; }
    
         [CommonEntityProperty()]
        public string dc_path_arquivo { get; set; }
    
         [CommonEntityProperty()]
        public string dc_mensagem_XML { get; set; }
    
         [CommonEntityProperty()]
        public string nm_nota_fiscal { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_emissao_nf { get; set; }
    
         [CommonEntityProperty()]
        public string no_escola { get; set; }
    
         [CommonEntityProperty()]
        public string no_pessoa { get; set; }
    
         [CommonEntityProperty()]
        public string no_item_inexistente { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_importacao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_resolvido { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_importacao_xml { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
    }
}
