//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEscola : TO
    {
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_item { get; set; }
    
         [CommonEntityProperty()]
        public int qt_estoque { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_custo { get; set; }
    
         [Key()]
         public int cd_item_escola { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta { get; set; }
    
    
        public virtual Escola Escola { get; set; }
        public virtual Item Item { get; set; }
        public virtual PlanoConta PlanoConta { get; set; }
    }
}
