//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPolitica : TO
    {
         [Key()]
         public int cd_item_politica { get; set; }
    
         [CommonEntityProperty()]
        public int cd_politica_comercial { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_dias_politica { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> pc_politica { get; set; }
    
    
        public virtual PoliticaComercial PoliticaComercial { get; set; }
    }
}
