//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMovimento : TO
    {
        public ItemMovimento()
        {
            this.ItemMovItemKit = new HashSet<ItemMovItemKit>();
        }
    
         [Key()]
         public int cd_item_movimento { get; set; }
    
         [CommonEntityProperty()]
        public int cd_movimento { get; set; }
    
         [CommonEntityProperty()]
        public int cd_item { get; set; }
    
         [CommonEntityProperty()]
        public string dc_item_movimento { get; set; }
    
         [CommonEntityProperty()]
        public int qt_item_movimento { get; set; }
    
         [CommonEntityProperty()]
        public double vl_unitario_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_total_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_liquido_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_acrescimo_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_item { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta { get; set; }
    
         [CommonEntityProperty()]
        public decimal pc_desconto_item { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_situacao_tributaria_ICMS { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_situacao_tributaria_PIS { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_situacao_tributaria_COFINS { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_ICMS_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_PIS_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_COFINS_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_IPI_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_ISS_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_ICMS_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_PIS_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_COFINS_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_IPI_item { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_ISS_item { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_ICMS { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_PIS { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_COFINS { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_IPI { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_ISS { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_cfop { get; set; }
    
         [CommonEntityProperty()]
        public string dc_cfop { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_aproximada { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_aproximado { get; set; }
    
    
        public virtual Item Item { get; set; }
        public virtual Movimento Movimento { get; set; }
        public virtual PlanoConta PlanoConta { get; set; }
        public virtual SituacaoTributaria SituacaoTribCOFINS { get; set; }
        public virtual SituacaoTributaria SituacaoTribICMS { get; set; }
        public virtual SituacaoTributaria SituacaoTribPIS { get; set; }
        public virtual CFOP CFOP { get; set; }
        public virtual ICollection<ItemMovItemKit> ItemMovItemKit { get; set; }
    }
}
