//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class JsonTeste : TO
    {
         [Key()]
         public int cd_json_teste { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo { get; set; }
    
         [CommonEntityProperty()]
        public int id_teste { get; set; }
    
         [CommonEntityProperty()]
        public string dc_json { get; set; }
    
         [CommonEntityProperty()]
        public byte id_erro { get; set; }
    
         [CommonEntityProperty()]
        public string dc_erro { get; set; }
    
    }
}
