//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ListaEnderecoMala : TO
    {
         [Key()]
         public int cd_lista_endereco_mala { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_mala_direta { get; set; }
    
         [CommonEntityProperty()]
        public byte id_cadastro { get; set; }
    
         [CommonEntityProperty()]
        public int cd_cadastro { get; set; }
    
         [CommonEntityProperty()]
        public string dc_email_cadastro { get; set; }
    
    
        public virtual MalaDireta MalaDireta { get; set; }
    }
}
