//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class LivroCyber : TO
    {
         [Key()]
         public int cd_livro_cyber { get; set; }
    
         [Key()]
         public string no_livro_cyber { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_estagio { get; set; }
    
    }
}
