//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class LocalidadeSGF : TO
    {
        public LocalidadeSGF()
        {
            this.Bairros = new HashSet<EnderecoSGF>();
            this.Cidades = new HashSet<EnderecoSGF>();
            this.Distritos = new HashSet<EnderecoSGF>();
            this.Estados = new HashSet<EnderecoSGF>();
            this.Logradouros = new HashSet<EnderecoSGF>();
            this.Paises = new HashSet<EnderecoSGF>();
            this.FilhasLocalidade = new HashSet<LocalidadeSGF>();
            this.PessoasFisicasLocalNascimento = new HashSet<PessoaFisicaSGF>();
            this.PessoasFisicasNacionalidades = new HashSet<PessoaFisicaSGF>();
            this.DadosNF = new HashSet<DadosNF>();
        }
    
         [Key()]
         public int cd_localidade { get; set; }
    
         [CommonEntityProperty()]
        public string no_localidade { get; set; }
    
         [CommonEntityProperty()]
        public byte cd_tipo_localidade { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_loc_relacionada { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_municipio { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_exportado { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_cep { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_logradouro { get; set; }
    
    
        public virtual ICollection<EnderecoSGF> Bairros { get; set; }
        public virtual ICollection<EnderecoSGF> Cidades { get; set; }
        public virtual ICollection<EnderecoSGF> Distritos { get; set; }
        public virtual ICollection<EnderecoSGF> Estados { get; set; }
        public virtual ICollection<EnderecoSGF> Logradouros { get; set; }
        public virtual ICollection<EnderecoSGF> Paises { get; set; }
        public virtual ICollection<LocalidadeSGF> FilhasLocalidade { get; set; }
        public virtual LocalidadeSGF LocalidadeRelacionada { get; set; }
        public virtual ICollection<PessoaFisicaSGF> PessoasFisicasLocalNascimento { get; set; }
        public virtual ICollection<PessoaFisicaSGF> PessoasFisicasNacionalidades { get; set; }
        public virtual EstadoSGF Estado { get; set; }
        public virtual ICollection<DadosNF> DadosNF { get; set; }
        public virtual PaisSGF Pais { get; set; }
    }
}
