//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class LogGeral : TO
    {
        public LogGeral()
        {
            this.DetalhesLogGeral = new HashSet<LogGeralDetalhe>();
        }
    
         [Key()]
         public int cd_log_geral { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_log_geral { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_log { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_registro_pai { get; set; }
    
         [CommonEntityProperty()]
        public int cd_origem { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_spid { get; set; }
    
         [CommonEntityProperty()]
        public string hostprocess { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_pessoa_raf { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_fuso_horario { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.Guid> connection_id { get; set; }
    
    
        public virtual Escola Empresa { get; set; }
        public virtual Origem Origem { get; set; }
        public virtual UsuarioWebSGF Usuario { get; set; }
        public virtual TipoLog TipoLog { get; set; }
        public virtual ICollection<LogGeralDetalhe> DetalhesLogGeral { get; set; }
    }
}
