//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class LogGeralDetalhe : TO
    {
         [Key()]
         public int cd_log_geral_detalhe { get; set; }
    
         [CommonEntityProperty()]
        public string dc_valor_antigo { get; set; }
    
         [CommonEntityProperty()]
        public string dc_valor_novo { get; set; }
    
         [CommonEntityProperty()]
        public string no_coluna { get; set; }
    
         [CommonEntityProperty()]
        public int cd_log_geral { get; set; }
    
    
        public virtual LogGeral LogGeral { get; set; }
    }
}
