//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class MalaDireta : TO
    {
        public MalaDireta()
        {
            this.Contratos = new HashSet<Contrato>();
            this.ListasEnderecoMala = new HashSet<ListaEnderecoMala>();
            this.MalasDiretaCadastro = new HashSet<MalaDiretaCadastro>();
            this.MalasDiretaProduto = new HashSet<MalaDiretaProduto>();
            this.MalasDiretaCurso = new HashSet<MalaDiretaCurso>();
            this.MalasDiretaPeriodo = new HashSet<MalaDiretaPeriodo>();
        }
    
         [Key()]
         public int cd_mala_direta { get; set; }
    
         [CommonEntityProperty()]
        public int cd_escola { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_mala_direta { get; set; }
    
         [CommonEntityProperty()]
        public string dc_assunto { get; set; }
    
         [CommonEntityProperty()]
        public string tx_msg_header { get; set; }
    
         [CommonEntityProperty()]
        public string tx_msg_body { get; set; }
    
         [CommonEntityProperty()]
        public string tx_msg_footer { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dh_mala_direta { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_sexo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_mes_nascimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hh_inicial { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hh_final { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_enviados { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_mala { get; set; }
    
    
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual Escola Empresa { get; set; }
        public virtual ICollection<ListaEnderecoMala> ListasEnderecoMala { get; set; }
        public virtual ICollection<MalaDiretaCadastro> MalasDiretaCadastro { get; set; }
        public virtual ICollection<MalaDiretaProduto> MalasDiretaProduto { get; set; }
        public virtual ICollection<MalaDiretaCurso> MalasDiretaCurso { get; set; }
        public virtual ICollection<MalaDiretaPeriodo> MalasDiretaPeriodo { get; set; }
        public virtual UsuarioWebSGF Usuario { get; set; }
    }
}
