//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class MensagemAvaliacao : TO
    {
        public MensagemAvaliacao()
        {
            this.MensagemAvaliacaoAluno = new HashSet<MensagemAvaliacaoAluno>();
        }
    
         [Key()]
         public int cd_mensagem_avaliacao { get; set; }
    
         [CommonEntityProperty()]
        public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public int cd_curso { get; set; }
    
         [CommonEntityProperty()]
        public bool id_mensagem_ativa { get; set; }
    
         [CommonEntityProperty()]
        public string tx_mensagem_avaliacao { get; set; }
    
    
        public virtual Curso Curso { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual ICollection<MensagemAvaliacaoAluno> MensagemAvaliacaoAluno { get; set; }
    }
}
