//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Midia : TO
    {
        public Midia()
        {
            this.MidiaAluno = new HashSet<Aluno>();
            this.MidiaProspect = new HashSet<Prospect>();
        }
    
         [Key()]
         public int cd_midia { get; set; }
    
         [CommonEntityProperty()]
        public bool id_midia_ativa { get; set; }
    
         [CommonEntityProperty()]
        public string no_midia { get; set; }
    
    
        public virtual ICollection<Aluno> MidiaAluno { get; set; }
        public virtual ICollection<Prospect> MidiaProspect { get; set; }
    }
}
