//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Modalidade : TO
    {
        public Modalidade()
        {
            this.Cursos = new HashSet<Curso>();
        }
    
         [Key()]
         public int cd_modalidade { get; set; }
    
         [CommonEntityProperty()]
        public bool id_modalidade_ativa { get; set; }
    
         [CommonEntityProperty()]
        public string no_modalidade { get; set; }
    
    
        public virtual ICollection<Curso> Cursos { get; set; }
    }
}
