//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoCancelamentoBolsa : TO
    {
        public MotivoCancelamentoBolsa()
        {
            this.AlunosBolsas = new HashSet<AlunoBolsa>();
        }
    
         [Key()]
         public int cd_motivo_cancelamento_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public string dc_motivo_cancelamento_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public bool id_motivo_cancelamento_bolsa_ativo { get; set; }
    
    
        public virtual ICollection<AlunoBolsa> AlunosBolsas { get; set; }
    }
}
