//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoDesistencia : TO
    {
        public MotivoDesistencia()
        {
            this.Desistencia = new HashSet<Desistencia>();
        }
    
         [Key()]
         public int cd_motivo_desistencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_motivo_desistencia { get; set; }
    
         [CommonEntityProperty()]
        public bool id_motivo_desistencia_ativo { get; set; }
    
         [CommonEntityProperty()]
        public bool id_cancelamento { get; set; }
    
    
        public virtual ICollection<Desistencia> Desistencia { get; set; }
    }
}
