//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoTransferenciaAluno : TO
    {
        public MotivoTransferenciaAluno()
        {
            this.T_TRANSFERENCIA_ALUNO = new HashSet<TransferenciaAluno>();
        }
    
         [Key()]
         public int cd_motivo_transferencia_aluno { get; set; }
    
         [CommonEntityProperty()]
        public string dc_motivo_transferencia_aluno { get; set; }
    
         [CommonEntityProperty()]
        public bool id_motivo_transferencia_ativo { get; set; }
    
    
        public virtual ICollection<TransferenciaAluno> T_TRANSFERENCIA_ALUNO { get; set; }
    }
}
