//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Movimento : TO
    {
        public Movimento()
        {
            this.ItensMovimento = new HashSet<ItemMovimento>();
            this.MovimentoDevolver = new HashSet<Movimento>();
            this.Cheques = new HashSet<Cheque>();
            this.ItemMovimentoKit = new HashSet<ItemMovimentoKit>();
            this.PerdaMaterial = new HashSet<PerdaMaterial>();
        }
    
         [Key()]
         public int cd_movimento { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_politica_comercial { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_movimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_movimento { get; set; }
    
         [CommonEntityProperty()]
        public string dc_serie_movimento { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_emissao_movimento { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_vcto_movimento { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_mov_movimento { get; set; }
    
         [CommonEntityProperty()]
        public decimal pc_acrescimo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_acrescimo { get; set; }
    
         [CommonEntityProperty()]
        public decimal pc_desconto { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_movimento { get; set; }
    
         [CommonEntityProperty()]
        public bool id_nf { get; set; }
    
         [CommonEntityProperty()]
        public bool id_nf_escola { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_nota_fiscal { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_status_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_ICMS_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_PIS_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_COFINS_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_IPI_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_base_calculo_ISS_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_ICMS_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_PIS_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_COFINS_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_IPI_nf { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_ISS_nf { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_fiscal { get; set; }
    
         [CommonEntityProperty()]
        public string dc_justificativa_nf { get; set; }
    
         [CommonEntityProperty()]
        public string dc_cfop_nf { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> id_origem_movimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_origem_movimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_nota_fiscal { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_cfop_nf { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_aproximada { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_aproximado { get; set; }
    
         [CommonEntityProperty()]
        public string nm_nfe { get; set; }
    
         [CommonEntityProperty()]
        public string ds_protocolo_nfe { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_autorizacao_nfe { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_nfe_cancel { get; set; }
    
         [CommonEntityProperty()]
        public string dc_key_nfe { get; set; }
    
         [CommonEntityProperty()]
        public string dc_url_nf { get; set; }
    
         [CommonEntityProperty()]
        public string dc_mensagem_retorno { get; set; }
    
         [CommonEntityProperty()]
        public string dc_protocolo_cancel { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public bool id_exportado { get; set; }
    
         [CommonEntityProperty()]
        public string dc_meio_pagamento { get; set; }
    
         [CommonEntityProperty()]
        public bool id_importacao_xml { get; set; }
    
         [CommonEntityProperty()]
        public bool id_material_didatico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_curso { get; set; }
    
         [CommonEntityProperty()]
        public bool id_venda_futura { get; set; }
    
    
        public virtual Escola Empresa { get; set; }
        public virtual TipoFinanceiro TipoFinanceiro { get; set; }
        public virtual PessoaSGF Pessoa { get; set; }
        public virtual PoliticaComercial PoliticaComercial { get; set; }
        public virtual ICollection<ItemMovimento> ItensMovimento { get; set; }
        public virtual TipoNotaFiscal TipoNF { get; set; }
        public virtual CFOP CFOP { get; set; }
        public virtual ICollection<Movimento> MovimentoDevolver { get; set; }
        public virtual Movimento MovimentoDevolucao { get; set; }
        public virtual ICollection<Cheque> Cheques { get; set; }
        public virtual Aluno Aluno { get; set; }
        public virtual ICollection<ItemMovimentoKit> ItemMovimentoKit { get; set; }
        public virtual ICollection<PerdaMaterial> PerdaMaterial { get; set; }
    }
}
