//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Nivel : TO
    {
        public Nivel()
        {
            this.Curso = new HashSet<Curso>();
        }
    
         [Key()]
         public int cd_nivel { get; set; }
    
         [CommonEntityProperty()]
        public string dc_nivel { get; set; }
    
         [CommonEntityProperty()]
        public bool id_ativo { get; set; }
    
         [CommonEntityProperty()]
        public int nm_ordem { get; set; }
    
    
        public virtual ICollection<Curso> Curso { get; set; }
    }
}
