//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ObsSaldoCaixa : TO
    {
         [Key()]
         public int cd_obs_saldo_caixa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_caixa_usuario { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_saldo_caixa { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_saldo_caixa { get; set; }
    
    }
}
