//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Operadora : TO
    {
        public Operadora()
        {
            this.Telefones = new HashSet<TelefoneSGF>();
        }
    
         [Key()]
         public int cd_operadora { get; set; }
    
         [CommonEntityProperty()]
        public string no_operadora { get; set; }
    
         [CommonEntityProperty()]
        public bool id_operadora_ativa { get; set; }
    
    
        public virtual ICollection<TelefoneSGF> Telefones { get; set; }
    }
}
