//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class OrgaoFinanceiro : TO
    {
        public OrgaoFinanceiro()
        {
            this.AlunoRestricao = new HashSet<AlunoRestricao>();
        }
    
         [Key()]
         public int cd_orgao_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public string dc_orgao_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public byte id_orgao_ativo { get; set; }
    
    
        public virtual ICollection<AlunoRestricao> AlunoRestricao { get; set; }
    }
}
