//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Origem : TO
    {
        public Origem()
        {
            this.Kardexs = new HashSet<Kardex>();
            this.Titulos = new HashSet<Titulo>();
            this.Atributos = new HashSet<Atributos>();
            this.LogsGeral = new HashSet<LogGeral>();
        }
    
         [Key()]
         public int cd_origem { get; set; }
    
         [CommonEntityProperty()]
        public string dc_origem { get; set; }
    
    
        public virtual ICollection<Kardex> Kardexs { get; set; }
        public virtual ICollection<Titulo> Titulos { get; set; }
        public virtual ICollection<Atributos> Atributos { get; set; }
        public virtual ICollection<LogGeral> LogsGeral { get; set; }
    }
}
