//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class PapelSGF : TO
    {
        public PapelSGF()
        {
            this.PapelPessoa = new HashSet<PessoaSGF>();
            this.PapelPaiRelacionamento = new HashSet<RelacionamentoSGF>();
            this.PapelFilhoRelacionamento = new HashSet<RelacionamentoSGF>();
            this.PapelQualificador = new HashSet<QualifRelacionamento>();
            this.PapeisFilhos = new HashSet<PapelSGF>();
            this.PapeisPais = new HashSet<PapelSGF>();
        }
    
         [Key()]
         public int cd_papel { get; set; }
    
         [CommonEntityProperty()]
        public string no_papel { get; set; }
    
         [CommonEntityProperty()]
        public int nm_tipo_papel { get; set; }
    
         [CommonEntityProperty()]
        public byte id_natureza_papel { get; set; }
    
    
        public virtual ICollection<PessoaSGF> PapelPessoa { get; set; }
        public virtual ICollection<RelacionamentoSGF> PapelPaiRelacionamento { get; set; }
        public virtual ICollection<RelacionamentoSGF> PapelFilhoRelacionamento { get; set; }
        public virtual ICollection<QualifRelacionamento> PapelQualificador { get; set; }
        public virtual ICollection<PapelSGF> PapeisFilhos { get; set; }
        public virtual ICollection<PapelSGF> PapeisPais { get; set; }
    }
}
