//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro : TO
    {
         [Key()]
         public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public byte id_retroativo_caixa { get; set; }
    
         [CommonEntityProperty()]
        public bool id_liquidacao_tit_ant_aberto { get; set; }
    
         [CommonEntityProperty()]
        public bool id_somar_descontos_financeiros { get; set; }
    
         [CommonEntityProperty()]
        public bool id_permitir_desc_apos_politica { get; set; }
    
         [CommonEntityProperty()]
        public bool id_juros_final_semana { get; set; }
    
         [CommonEntityProperty()]
        public bool id_alterar_venc_final_semana { get; set; }
    
         [CommonEntityProperty()]
        public bool id_bloquear_venda_sem_estoque { get; set; }
    
         [CommonEntityProperty()]
        public bool id_bloquear_mov_retr_estoque { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_requer_plano_contas_mov { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_bloquear_imprimir_nf_data_atual { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_liberar_habilitacao_professor { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_bloquear_matricula_vaga { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_nro_contrato_automatico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_tipo_numero_contrato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_dia_vencimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_dia_util_vencimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_ultimo_contrato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_ultimo_matricula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_ultima_turma { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_ultimo_recibo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_cobrar_juros_multa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> pc_juros_dia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> pc_multa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_dias_carencia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_aulas_sem_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_minutos_concedidos { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_bloquear_alt_dta_biblio { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_dias_biblioteca { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> pc_taxa_dia_biblioteca { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> per_desconto_maximo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_niveis_plano_contas { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_local_movto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_mat { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_tax { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_trf { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_juros { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_multa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_desc { get; set; }
    
         [CommonEntityProperty()]
        public bool id_gerar_financeiro_contrato { get; set; }
    
         [CommonEntityProperty()]
        public bool id_emitir_nf_servico { get; set; }
    
         [CommonEntityProperty()]
        public bool id_emitir_nf_mercantil { get; set; }
    
         [CommonEntityProperty()]
        public bool id_numero_nf_automatico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_nf_servico { get; set; }
    
         [CommonEntityProperty()]
        public string dc_serie_nf_servico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_nf_mercantil { get; set; }
    
         [CommonEntityProperty()]
        public string dc_serie_nf_mercantil { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_item_taxa_matricula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_item_mensalidade { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_item_biblioteca { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_nf_matricula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_nf_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_nf_biblioteca { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_politica_comercial_nf { get; set; }
    
         [CommonEntityProperty()]
        public byte id_regime_tributario { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_ap_saida { get; set; }
    
         [CommonEntityProperty()]
        public double pc_aliquota_ap_servico { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_faltas_aluno { get; set; }
    
         [CommonEntityProperty()]
        public bool id_mostrar_3_boletos_pagina { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_dias_titulos_abertos { get; set; }
    
         [CommonEntityProperty()]
        public double nm_media_minima { get; set; }
    
         [CommonEntityProperty()]
        public double pc_falta_permitida { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_taxbco { get; set; }
    
         [CommonEntityProperty()]
        public bool id_baixa_automatica_cartao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_baixa_automatica_cheque { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_material { get; set; }
    
         [CommonEntityProperty()]
        public bool id_financeiro_negativo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_nf_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_nf_material_saida { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_item_servico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_nf_servico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_servico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_politica_servico { get; set; }
    
         [CommonEntityProperty()]
        public bool id_alterar_preco_curso_contrato { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_vagas_minima { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_alterar_preco_material_contrato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_alterar_valor_desconto_contrato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_opcao_venda_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_local_cartao { get; set; }
    
    
        public virtual Escola Escola { get; set; }
        public virtual LocalMovto LocalMovimento { get; set; }
        public virtual PlanoConta ParametroPlanoContaMatricula { get; set; }
        public virtual PlanoConta ParametroPlanoContaTaxa { get; set; }
        public virtual PlanoConta ParametroPlanoContaTRF { get; set; }
        public virtual PlanoConta ParametroPlanoContaDesconto { get; set; }
        public virtual PlanoConta ParametroPlanoContaJuros { get; set; }
        public virtual PlanoConta ParametroPlanoContaMulta { get; set; }
        public virtual Item ItemBiblioteca { get; set; }
        public virtual Item ItemMensalidade { get; set; }
        public virtual Item ItemTaxaMens { get; set; }
        public virtual PoliticaComercial PoliticaComercial { get; set; }
        public virtual TipoNotaFiscal TpNFBiblioteca { get; set; }
        public virtual TipoNotaFiscal TpNFMaterial { get; set; }
        public virtual TipoNotaFiscal TpNFMatricula { get; set; }
        public virtual PlanoConta ParametroPlanoContaTaxaBco { get; set; }
        public virtual PlanoConta ParametroPlanoContaMaterial { get; set; }
        public virtual TipoNotaFiscal TpNFMaterialSaida { get; set; }
        public virtual Item ItemServico { get; set; }
        public virtual PlanoConta PlanoContaServico { get; set; }
        public virtual PoliticaComercial PoliticaComercialServico { get; set; }
        public virtual TipoNotaFiscal TipoNotaFiscalServico { get; set; }
        public virtual LocalMovto T_LOCAL_MOVTO { get; set; }
    }
}
