//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class PerdaMaterial : TO
    {
         [Key()]
         public int cd_perda_material { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_perda_material { get; set; }
    
         [CommonEntityProperty()]
        public int cd_movimento { get; set; }
    
         [CommonEntityProperty()]
        public int cd_contrato { get; set; }
    
         [CommonEntityProperty()]
        public byte id_status_perda { get; set; }
    
    
        public virtual Contrato Contrato { get; set; }
        public virtual Movimento Movimento { get; set; }
    }
}
