//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaJuridicaSGF : PessoaSGF
    {
         [CommonEntityProperty()]
        public int cd_tipo_sociedade { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_cgc { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_registro_junta_comercial { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_insc_estadual { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_insc_municipal { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_cnpj_cnab { get; set; }
    
         [CommonEntityProperty()]
        public string dc_registro_junta_comercial { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_baixa { get; set; }
    
         [CommonEntityProperty()]
        public string dc_nom_presidente { get; set; }
    
    
        public virtual TipoSociedade TipoSociedade { get; set; }
    }
}
