//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaFisicaSGF : PessoaSGF
    {
        public PessoaFisicaSGF()
        {
            this.PessoaFisicaFuncioanrio = new HashSet<FuncionarioSGF>();
            this.UsuarioWebSGF = new HashSet<UsuarioWebSGF>();
            this.PessoasSGFQueUsamMeuCpf = new HashSet<PessoaFisicaSGF>();
            this.Prospect = new HashSet<Prospect>();
            this.Alunos = new HashSet<Aluno>();
        }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_estado_civil { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_loc_nascimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_loc_nacionalidade { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tratamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_pessoa_cpf { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_sexo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_nascimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_casamento { get; set; }
    
         [CommonEntityProperty()]
        public string nm_cpf { get; set; }
    
         [CommonEntityProperty()]
        public string nm_doc_identidade { get; set; }
    
         [CommonEntityProperty()]
        public string dc_carteira_trabalho { get; set; }
    
         [CommonEntityProperty()]
        public string dc_carteira_motorista { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_titulo_eleitor { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_insc_inss { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_crc { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_venc_habilitacao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_integracao_folha { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_orgao_expedidor { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_estado_expedidor { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_emis_expedidor { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_certidao_nascimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_escolaridade { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_curso_recomendado { get; set; }
    
    
        public virtual ICollection<FuncionarioSGF> PessoaFisicaFuncioanrio { get; set; }
        public virtual ICollection<UsuarioWebSGF> UsuarioWebSGF { get; set; }
        public virtual ICollection<PessoaFisicaSGF> PessoasSGFQueUsamMeuCpf { get; set; }
        public virtual PessoaFisicaSGF PessoaSGFQueUsoOCpf { get; set; }
        public virtual ICollection<Prospect> Prospect { get; set; }
        public virtual LocalidadeSGF LocalNascimento { get; set; }
        public virtual LocalidadeSGF Nacionalidade { get; set; }
        public virtual EstadoCivilSGF EstadoCivil { get; set; }
        public virtual ICollection<Aluno> Alunos { get; set; }
        public virtual EstadoSGF Estado { get; set; }
        public virtual TratamentoPessoa TratamentoPessoa { get; set; }
        public virtual OrgaoExpedidor PessoaOrgaoExpedidor { get; set; }
        public virtual Curso T_CURSO { get; set; }
        public virtual Escolaridade T_ESCOLARIDADE { get; set; }
        public virtual Produto T_PRODUTO { get; set; }
    }
}
