//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaRaf : TO
    {
         [Key()]
         public int cd_pessoa_raf { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa { get; set; }
    
         [CommonEntityProperty()]
        public string nm_raf { get; set; }
    
         [CommonEntityProperty()]
        public string dc_senha_raf { get; set; }
    
         [CommonEntityProperty()]
        public bool id_raf_liberado { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_tentativa { get; set; }
    
         [CommonEntityProperty()]
        public bool id_bloqueado { get; set; }
    
         [CommonEntityProperty()]
        public bool id_trocar_senha { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_expiracao_senha { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_limite_bloqueio { get; set; }
    
    
        public virtual PessoaSGF PessoaSGF { get; set; }
    }
}
