//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaCarta : TO
    {
         [Key()]
         public int cd_pessoa_carta { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa { get; set; }
    
         [CommonEntityProperty()]
        public short nm_ano_carta { get; set; }
    
    
        public virtual PessoaSGF PessoaSGF { get; set; }
    }
}
