//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoConta : TO
    {
        public PlanoConta()
        {
            this.Contrato = new HashSet<Contrato>();
            this.TaxaMatricula = new HashSet<TaxaMatricula>();
            this.Titulo = new HashSet<Titulo>();
            this.ContaCorrente = new HashSet<ContaCorrente>();
            this.PlanoTitulo = new HashSet<PlanoTitulo>();
            this.PlanoContaMatricula = new HashSet<Parametro>();
            this.PlanoContaTaxa = new HashSet<Parametro>();
            this.PlanoContaTRF = new HashSet<Parametro>();
            this.Itens = new HashSet<ItemEscola>();
            this.Prospect = new HashSet<Prospect>();
            this.PlanoContaDescricao = new HashSet<Parametro>();
            this.PlanoContaJuros = new HashSet<Parametro>();
            this.PlanoContaMulta = new HashSet<Parametro>();
            this.ItensMovimento = new HashSet<ItemMovimento>();
            this.T_PARAMETRO5 = new HashSet<Parametro>();
            this.PlanoContaMaterial = new HashSet<Parametro>();
            this.PlanoContaServico = new HashSet<Parametro>();
        }
    
         [Key()]
         public int cd_plano_conta { get; set; }
    
         [CommonEntityProperty()]
        public int cd_subgrupo_conta { get; set; }
    
         [CommonEntityProperty()]
        public bool id_conta_segura { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public bool id_ativo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_tipo_conta { get; set; }
    
    
        public virtual Escola EmpresaPlanoConta { get; set; }
        public virtual SubgrupoConta PlanoContaSubgrupo { get; set; }
        public virtual ICollection<Contrato> Contrato { get; set; }
        public virtual ICollection<TaxaMatricula> TaxaMatricula { get; set; }
        public virtual ICollection<Titulo> Titulo { get; set; }
        public virtual ICollection<ContaCorrente> ContaCorrente { get; set; }
        public virtual ICollection<PlanoTitulo> PlanoTitulo { get; set; }
        public virtual ICollection<Parametro> PlanoContaMatricula { get; set; }
        public virtual ICollection<Parametro> PlanoContaTaxa { get; set; }
        public virtual ICollection<Parametro> PlanoContaTRF { get; set; }
        public virtual ICollection<ItemEscola> Itens { get; set; }
        public virtual ICollection<Prospect> Prospect { get; set; }
        public virtual ICollection<Parametro> PlanoContaDescricao { get; set; }
        public virtual ICollection<Parametro> PlanoContaJuros { get; set; }
        public virtual ICollection<Parametro> PlanoContaMulta { get; set; }
        public virtual ICollection<ItemMovimento> ItensMovimento { get; set; }
        public virtual ICollection<Parametro> T_PARAMETRO5 { get; set; }
        public virtual ICollection<Parametro> PlanoContaMaterial { get; set; }
        public virtual ICollection<Parametro> PlanoContaServico { get; set; }
    }
}
