//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticaComercial : TO
    {
        public PoliticaComercial()
        {
            this.Movimentos = new HashSet<Movimento>();
            this.ItemPolitica = new HashSet<ItemPolitica>();
            this.Parametro = new HashSet<Parametro>();
            this.PoliticaComercialServico = new HashSet<Parametro>();
        }
    
         [Key()]
         public int cd_politica_comercial { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public string dc_politica_comercial { get; set; }
    
         [CommonEntityProperty()]
        public bool id_politica_ativa { get; set; }
    
         [CommonEntityProperty()]
        public bool id_parcela_igual { get; set; }
    
         [CommonEntityProperty()]
        public bool id_vencimento_fixo { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_parcelas { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_intervalo_parcela { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_periodo_intervalo { get; set; }
    
    
        public virtual Escola Empresa { get; set; }
        public virtual ICollection<Movimento> Movimentos { get; set; }
        public virtual ICollection<ItemPolitica> ItemPolitica { get; set; }
        public virtual ICollection<Parametro> Parametro { get; set; }
        public virtual ICollection<Parametro> PoliticaComercialServico { get; set; }
    }
}
