//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Produto : TO
    {
        public Produto()
        {
            this.Conceito = new HashSet<Conceito>();
            this.Estagio = new HashSet<Estagio>();
            this.Cursos = new HashSet<Curso>();
            this.ProdutoHabilitacaoProfesso = new HashSet<HabilitacaoProfessor>();
            this.AtividadeExtraProduto = new HashSet<AtividadeExtra>();
            this.ProdutoProspect = new HashSet<ProspectProduto>();
            this.Turma = new HashSet<Turma>();
            this.Contratos = new HashSet<Contrato>();
            this.HistoricoAluno = new HashSet<HistoricoAluno>();
            this.MalaDiretaProduto = new HashSet<MalaDiretaProduto>();
            this.AulaPersonalizada = new HashSet<AulaPersonalizada>();
            this.AvaliacaoParticipacao = new HashSet<AvaliacaoParticipacao>();
            this.FuncionarioComissao = new HashSet<FuncionarioComissao>();
            this.ProdutoFuncionario = new HashSet<ProdutoFuncionario>();
            this.T_MENSAGEM_AVALIACAO = new HashSet<MensagemAvaliacao>();
            this.T_PESSOA_FISICA = new HashSet<PessoaFisicaSGF>();
        }
    
         [Key()]
         public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public string no_produto { get; set; }
    
         [CommonEntityProperty()]
        public bool id_produto_ativo { get; set; }
    
         [CommonEntityProperty()]
        public string no_produto_abreviado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_produto_padrao { get; set; }
    
    
        public virtual ICollection<Conceito> Conceito { get; set; }
        public virtual ICollection<Estagio> Estagio { get; set; }
        public virtual ICollection<Curso> Cursos { get; set; }
        public virtual ICollection<HabilitacaoProfessor> ProdutoHabilitacaoProfesso { get; set; }
        public virtual ICollection<AtividadeExtra> AtividadeExtraProduto { get; set; }
        public virtual ICollection<ProspectProduto> ProdutoProspect { get; set; }
        public virtual ICollection<Turma> Turma { get; set; }
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual ICollection<HistoricoAluno> HistoricoAluno { get; set; }
        public virtual ICollection<MalaDiretaProduto> MalaDiretaProduto { get; set; }
        public virtual ICollection<AulaPersonalizada> AulaPersonalizada { get; set; }
        public virtual ICollection<AvaliacaoParticipacao> AvaliacaoParticipacao { get; set; }
        public virtual ICollection<FuncionarioComissao> FuncionarioComissao { get; set; }
        public virtual ICollection<ProdutoFuncionario> ProdutoFuncionario { get; set; }
        public virtual ICollection<MensagemAvaliacao> T_MENSAGEM_AVALIACAO { get; set; }
        public virtual ICollection<PessoaFisicaSGF> T_PESSOA_FISICA { get; set; }
    }
}
