//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Professor : FuncionarioSGF
    {
        public Professor()
        {
            this.HabilitacaoProfessor = new HashSet<HabilitacaoProfessor>();
            this.ProfessorTurma = new HashSet<ProfessorTurma>();
            this.HorariosProfessores = new HashSet<HorarioProfessorTurma>();
            this.DiarioAulaProfSubtituto = new HashSet<DiarioAula>();
            this.DiarioAulaProfessor = new HashSet<DiarioAula>();
            this.AulaReposicao = new HashSet<AulaReposicao>();
        }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_forma_pagamento { get; set; }
    
         [CommonEntityProperty()]
        public bool id_contratado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_pagamento_interno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_pagamento_externo { get; set; }
    
         [CommonEntityProperty()]
        public string dc_numero_chapa { get; set; }
    
         [CommonEntityProperty()]
        public bool id_coordenador { get; set; }
    
         [CommonEntityProperty()]
        public double pc_termino_estagio { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_termino_estagio { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_rematricula { get; set; }
    
         [CommonEntityProperty()]
        public bool id_liberado { get; set; }
    
    
        public virtual ICollection<HabilitacaoProfessor> HabilitacaoProfessor { get; set; }
        public virtual ICollection<ProfessorTurma> ProfessorTurma { get; set; }
        public virtual ICollection<HorarioProfessorTurma> HorariosProfessores { get; set; }
        public virtual ICollection<DiarioAula> DiarioAulaProfSubtituto { get; set; }
        public virtual ICollection<DiarioAula> DiarioAulaProfessor { get; set; }
        public virtual ICollection<AulaReposicao> AulaReposicao { get; set; }
    }
}
