//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacaoTurma : TO
    {
        public ProgramacaoTurma()
        {
            this.DiariosAula = new HashSet<DiarioAula>();
        }
    
         [Key()]
         public int cd_programacao_turma { get; set; }
    
         [CommonEntityProperty()]
        public int cd_turma { get; set; }
    
         [CommonEntityProperty()]
        public int nm_aula_programacao_turma { get; set; }
    
         [CommonEntityProperty()]
        public string dc_programacao_turma { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dta_programacao_turma { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hr_inicial_programacao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.TimeSpan> hr_final_programacao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_aula_dada { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_programacao_manual { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dta_cadastro_programacao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_feriado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_feriado_desconsiderado { get; set; }
    
         [CommonEntityProperty()]
        public bool id_mostrar_calendario { get; set; }
    
         [CommonEntityProperty()]
        public bool id_prog_cancelada { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_programacao_real { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_programacao_aux { get; set; }
    
    
        public virtual Turma Turma { get; set; }
        public virtual ICollection<DiarioAula> DiariosAula { get; set; }
        public virtual Feriado Feriado { get; set; }
        public virtual FeriadoDesconsiderado FeriadoDesconsiderado { get; set; }
    }
}
