//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectPeriodo : TO
    {
         [Key()]
         public int cd_propsect_periodo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_prospect { get; set; }
    
         [CommonEntityProperty()]
        public byte id_periodo { get; set; }
    
    
        public virtual Prospect Prospect { get; set; }
    }
}
