//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Prospect : TO
    {
        public Prospect()
        {
            this.ProspectMotivoNaomatricula = new HashSet<ProspectMotivoNaoMatricula>();
            this.ProspectProduto = new HashSet<ProspectProduto>();
            this.ProspectFollowUp = new HashSet<FollowUp>();
            this.ProspectPeriodo = new HashSet<ProspectPeriodo>();
            this.Aluno = new HashSet<Aluno>();
            this.ProspectDia = new HashSet<ProspectDia>();
            this.AtividadeProspect = new HashSet<AtividadeProspect>();
        }
    
         [Key()]
         public int cd_prospect { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_fisica { get; set; }
    
         [CommonEntityProperty()]
        public int cd_midia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public byte id_periodo { get; set; }
    
         [CommonEntityProperty()]
        public byte id_dia_semana { get; set; }
    
         [CommonEntityProperty()]
        public bool id_prospect_ativo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_matricula_prospect { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_matricula_prospect { get; set; }
    
         [CommonEntityProperty()]
        public bool id_gerar_baixa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_local_movimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tipo_liquidacao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_faixa_etaria { get; set; }
    
         [CommonEntityProperty()]
        public string no_escola { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_abatimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> cd_motivo_inativo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_tipo_online { get; set; }
    
         [CommonEntityProperty()]
        public bool id_consultado { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_tipo_site { get; set; }
    
    
        public virtual Escola Escola { get; set; }
        public virtual Midia Midia { get; set; }
        public virtual PessoaFisicaSGF PessoaFisica { get; set; }
        public virtual ICollection<ProspectMotivoNaoMatricula> ProspectMotivoNaomatricula { get; set; }
        public virtual ICollection<ProspectProduto> ProspectProduto { get; set; }
        public virtual UsuarioWebSGF SysUsuario { get; set; }
        public virtual ICollection<FollowUp> ProspectFollowUp { get; set; }
        public virtual ICollection<ProspectPeriodo> ProspectPeriodo { get; set; }
        public virtual ICollection<Aluno> Aluno { get; set; }
        public virtual LocalMovto LocalMovto { get; set; }
        public virtual PlanoConta PlanoConta { get; set; }
        public virtual TipoLiquidacao TipoLiquidacao { get; set; }
        public virtual ICollection<ProspectDia> ProspectDia { get; set; }
        public virtual ICollection<AtividadeProspect> AtividadeProspect { get; set; }
    }
}
