//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ReajusteAnual : TO
    {
        public ReajusteAnual()
        {
            this.ReajustesAlunos = new HashSet<ReajusteAluno>();
            this.ReajustesCursos = new HashSet<ReajusteCurso>();
            this.ReajustesTitulos = new HashSet<ReajusteTitulo>();
            this.ReajustesTurmas = new HashSet<ReajusteTurma>();
            this.Aditamento = new HashSet<Aditamento>();
        }
    
         [Key()]
         public int cd_reajuste_anual { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_reajuste { get; set; }
    
         [CommonEntityProperty()]
        public double pc_reajuste_anual { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_reajuste_anual { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_inicial_vencimento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_final_vencimento { get; set; }
    
         [CommonEntityProperty()]
        public byte id_status_reajuste { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dh_cadastro_reajuste { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public int cd_nome_contrato { get; set; }
    
    
        public virtual ICollection<ReajusteAluno> ReajustesAlunos { get; set; }
        public virtual UsuarioWebSGF SysUsuario { get; set; }
        public virtual ICollection<ReajusteCurso> ReajustesCursos { get; set; }
        public virtual ICollection<ReajusteTitulo> ReajustesTitulos { get; set; }
        public virtual ICollection<ReajusteTurma> ReajustesTurmas { get; set; }
        public virtual Escola Empresa { get; set; }
        public virtual NomeContrato NomeContrato { get; set; }
        public virtual ICollection<Aditamento> Aditamento { get; set; }
    }
}
