//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ReajusteTitulo : TO
    {
         [Key()]
         public int cd_reajuste_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_reajuste_anual { get; set; }
    
         [CommonEntityProperty()]
        public int cd_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_original_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_reajustado_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_turma { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_curso { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_original_saldo_titulo { get; set; }
    
    
        public virtual Aluno Aluno { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual ReajusteAnual ReajusteAnual { get; set; }
        public virtual Titulo Titulo { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
