//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class ReajusteTurma : TO
    {
         [Key()]
         public int cd_reajuste_turma { get; set; }
    
         [CommonEntityProperty()]
        public int cd_reajuste_anual { get; set; }
    
         [CommonEntityProperty()]
        public int cd_turma { get; set; }
    
    
        public virtual ReajusteAnual ReajusteAnual { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
