//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Regime : TO
    {
        public Regime()
        {
            this.RegimeTabelaPreco = new HashSet<TabelaPreco>();
            this.Turma = new HashSet<Turma>();
            this.Contratos = new HashSet<Contrato>();
        }
    
         [Key()]
         public int cd_regime { get; set; }
    
         [CommonEntityProperty()]
        public bool id_regime_ativo { get; set; }
    
         [CommonEntityProperty()]
        public string no_regime { get; set; }
    
         [CommonEntityProperty()]
        public string no_regime_abreviado { get; set; }
    
    
        public virtual ICollection<TabelaPreco> RegimeTabelaPreco { get; set; }
        public virtual ICollection<Turma> Turma { get; set; }
        public virtual ICollection<Contrato> Contratos { get; set; }
    }
}
