//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionamentoSGF : TO
    {
         [CommonEntityProperty()]
        public int cd_pessoa_pai { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_filho { get; set; }
    
         [CommonEntityProperty()]
        public int cd_papel_filho { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_qualif_relacionamento { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_papel_pai { get; set; }
    
         [Key()]
         public int cd_relacionamento { get; set; }
    
    
        public virtual PapelSGF RelacionamentoPaiPapel { get; set; }
        public virtual PapelSGF RelacionamentoFilhoPapel { get; set; }
        public virtual PessoaSGF PessoaFilho { get; set; }
        public virtual PessoaSGF PessoaPai { get; set; }
        public virtual QualifRelacionamento RelacionamentoQualif { get; set; }
    }
}
