//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using System;
    
    public partial class ReportPagamentoProfessor
    {
        public int cd_professor { get; set; }
        public int cd_turma { get; set; }
        public string no_turma { get; set; }
        public string qtd_total_horas_prof { get; set; }
        public string tx_obs { get; set; }
        public int id_dia_semana { get; set; }
        public string no_estagio { get; set; }
        public System.DateTime dt_inicio_aula { get; set; }
        public int qtd_alunos { get; set; }
        public string dc_horarios { get; set; }
        public string dias_horarios { get; set; }
        public string dc_total_horas_semana { get; set; }
        public string dc_total_hora_sabado { get; set; }
        public string dc_horario { get; set; }
        public string no_professor { get; set; }
        public string no_professor_substituto { get; set; }
        public Nullable<System.DateTime> dt_dia_falta { get; set; }
        public decimal vl_hora_interna { get; set; }
        public decimal vl_hora_externa { get; set; }
        public bool id_aula_externa { get; set; }
    }
}
