//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class RetornoCNAB : TO
    {
        public RetornoCNAB()
        {
            this.TitulosRetornoCNAB = new HashSet<TituloRetornoCNAB>();
        }
    
         [Key()]
         public int cd_retorno_cnab { get; set; }
    
         [CommonEntityProperty()]
        public int cd_local_movto { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public byte id_status_cnab { get; set; }
    
         [CommonEntityProperty()]
        public string no_arquivo_retorno { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_cadastro_cnab { get; set; }
    
         [CommonEntityProperty()]
        public short nm_linhas_retorno { get; set; }
    
         [CommonEntityProperty()]
        public short nm_titulos_gerados { get; set; }
    
    
        public virtual LocalMovto LocalMovto { get; set; }
        public virtual UsuarioWebSGF SysUsuario { get; set; }
        public virtual ICollection<TituloRetornoCNAB> TitulosRetornoCNAB { get; set; }
    }
}
