//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Sala : TO
    {
        public Sala()
        {
            this.SalaAtividadeExtra = new HashSet<AtividadeExtra>();
            this.Turma = new HashSet<Turma>();
            this.DiarioAula = new HashSet<DiarioAula>();
            this.AulaReposicao = new HashSet<AulaReposicao>();
            this.T_TURMA = new HashSet<Turma>();
        }
    
         [Key()]
         public int cd_sala { get; set; }
    
         [CommonEntityProperty()]
        public bool id_sala_ativa { get; set; }
    
         [CommonEntityProperty()]
        public string no_sala { get; set; }
    
         [CommonEntityProperty()]
        public int nm_vaga_sala { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_sala_online { get; set; }
    
         [CommonEntityProperty()]
        public string id_zoom { get; set; }
    
         [CommonEntityProperty()]
        public string dc_usuario_adm { get; set; }
    
         [CommonEntityProperty()]
        public string dc_senha_usuario_adm { get; set; }
    
         [CommonEntityProperty()]
        public string dc_usuario_escola { get; set; }
    
         [CommonEntityProperty()]
        public string dc_senha_usuario_escola { get; set; }
    
    
        public virtual Escola Escola { get; set; }
        public virtual ICollection<AtividadeExtra> SalaAtividadeExtra { get; set; }
        public virtual ICollection<Turma> Turma { get; set; }
        public virtual ICollection<DiarioAula> DiarioAula { get; set; }
        public virtual ICollection<AulaReposicao> AulaReposicao { get; set; }
        public virtual ICollection<Turma> T_TURMA { get; set; }
    }
}
