//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Linq.Mapping;
    using System.Reflection;
    using System.Transactions;
    using Componentes.GenericModel;
    using System.Linq;
    using System.Collections;
    
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    
    public partial class SGFWebContext : DbContext
    {
    	public Hashtable LISTA_ORIGEM_LOGS = new Hashtable();
        public SGFWebContext()
            : base("name=SGFWebContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.ProxyCreationEnabled = false;
    		populaListaOrigem();
        }
    
    	private void populaListaOrigem() {
            if(LISTA_ORIGEM_LOGS.Count <= 0) {
                LISTA_ORIGEM_LOGS.Add("TipoLog", Byte.Parse("0"));
        		LISTA_ORIGEM_LOGS.Add("SysDireitoUsuario", Byte.Parse("1"));
        		LISTA_ORIGEM_LOGS.Add("SysDireitoGrupo", Byte.Parse("2"));
        		LISTA_ORIGEM_LOGS.Add("SysGrupo", Byte.Parse("3"));
        		LISTA_ORIGEM_LOGS.Add("UsuarioWeb", Byte.Parse("4"));
        		LISTA_ORIGEM_LOGS.Add("UsuarioWebSGF", Byte.Parse("4"));
        		LISTA_ORIGEM_LOGS.Add("Pessoa", Byte.Parse("5"));
        		LISTA_ORIGEM_LOGS.Add("PessoaFisica", Byte.Parse("6"));
        		LISTA_ORIGEM_LOGS.Add("PessoaJuridica", Byte.Parse("7"));
        		LISTA_ORIGEM_LOGS.Add("Endereco", Byte.Parse("8"));
        		LISTA_ORIGEM_LOGS.Add("Telefone", Byte.Parse("9"));
        		LISTA_ORIGEM_LOGS.Add("PessoaSGF", Byte.Parse("5"));
        		LISTA_ORIGEM_LOGS.Add("PessoaFisicaSGF", Byte.Parse("6"));
        		LISTA_ORIGEM_LOGS.Add("PessoaJuridicaSGF", Byte.Parse("7"));
        		LISTA_ORIGEM_LOGS.Add("EnderecoSGF", Byte.Parse("8"));
        		LISTA_ORIGEM_LOGS.Add("TelefoneSGF", Byte.Parse("9"));
        		LISTA_ORIGEM_LOGS.Add("Aluno", Byte.Parse("10"));
        		LISTA_ORIGEM_LOGS.Add("AlunoBolsa", Byte.Parse("11"));
        		LISTA_ORIGEM_LOGS.Add("AtividadeExtra", Byte.Parse("12"));
        		LISTA_ORIGEM_LOGS.Add("AlunoCurso", Byte.Parse("13"));
        		LISTA_ORIGEM_LOGS.Add("AlunoMotivoMatricula", Byte.Parse("14"));
        		LISTA_ORIGEM_LOGS.Add("AlunoMotivoNaoMatricula", Byte.Parse("15"));
        		LISTA_ORIGEM_LOGS.Add("Horario", Byte.Parse("16"));
        		LISTA_ORIGEM_LOGS.Add("TabelaPreco", Byte.Parse("17"));
        		LISTA_ORIGEM_LOGS.Add("Prospect", Byte.Parse("18"));
        		LISTA_ORIGEM_LOGS.Add("Turma", Byte.Parse("19"));
        		LISTA_ORIGEM_LOGS.Add("Professor", Byte.Parse("20"));
        		LISTA_ORIGEM_LOGS.Add("AvaliacaoTurma", Byte.Parse("21"));
        		LISTA_ORIGEM_LOGS.Add("Contrato", Byte.Parse("22"));
        		LISTA_ORIGEM_LOGS.Add("PlanoConta", Byte.Parse("23"));
        		LISTA_ORIGEM_LOGS.Add("Funcionario", Byte.Parse("24"));
                LISTA_ORIGEM_LOGS.Add("FuncionarioSGF", Byte.Parse("24"));
        		LISTA_ORIGEM_LOGS.Add("ProgramacaoTurma", Byte.Parse("25"));
        		LISTA_ORIGEM_LOGS.Add("Feriado", Byte.Parse("26"));
        		LISTA_ORIGEM_LOGS.Add("FeriadoDesconsiderado", Byte.Parse("27"));
                LISTA_ORIGEM_LOGS.Add("AlunoTurma", Byte.Parse("28"));
                LISTA_ORIGEM_LOGS.Add("ProfessorTurma", Byte.Parse("29"));
                LISTA_ORIGEM_LOGS.Add("HorarioProfessorTurma", Byte.Parse("30"));
        		LISTA_ORIGEM_LOGS.Add("Aditamento", Byte.Parse("31"));
        		LISTA_ORIGEM_LOGS.Add("Titulo", Byte.Parse("32"));
        		LISTA_ORIGEM_LOGS.Add("TaxaMatricula", Byte.Parse("33"));
        		LISTA_ORIGEM_LOGS.Add("Cheque", Byte.Parse("34"));
                LISTA_ORIGEM_LOGS.Add("DiarioAula", Byte.Parse("35"));
                LISTA_ORIGEM_LOGS.Add("Banco", Byte.Parse("36"));
                LISTA_ORIGEM_LOGS.Add("LocalMovto", Byte.Parse("37"));
                LISTA_ORIGEM_LOGS.Add("HistoricoAluno", Byte.Parse("38"));
        		LISTA_ORIGEM_LOGS.Add("BaixaTitulo", Byte.Parse("47"));
        		LISTA_ORIGEM_LOGS.Add("TransacaoFinanceira", Byte.Parse("129"));
        		LISTA_ORIGEM_LOGS.Add("Desistencia", Byte.Parse("57"));
        		LISTA_ORIGEM_LOGS.Add("PoliticaComercial", Byte.Parse("132"));
        		LISTA_ORIGEM_LOGS.Add("Emprestimo", Byte.Parse("48"));
        		LISTA_ORIGEM_LOGS.Add("Kardex", Byte.Parse("133"));
        		LISTA_ORIGEM_LOGS.Add("ItemEscola", Byte.Parse("74"));
        		LISTA_ORIGEM_LOGS.Add("ContaCorrente", Byte.Parse("52"));
        		LISTA_ORIGEM_LOGS.Add("Movimento", Byte.Parse("69"));
        		LISTA_ORIGEM_LOGS.Add("ItemMovimento", Byte.Parse("70"));			
        		LISTA_ORIGEM_LOGS.Add("ItemPolitica", Byte.Parse("134"));
        		LISTA_ORIGEM_LOGS.Add("Empresa", Byte.Parse("135"));
        		LISTA_ORIGEM_LOGS.Add("Escola", Byte.Parse("135"));
        		LISTA_ORIGEM_LOGS.Add("Parametro", Byte.Parse("136"));
        		LISTA_ORIGEM_LOGS.Add("Item", Byte.Parse("72"));
        		LISTA_ORIGEM_LOGS.Add("PoliticaDesconto", Byte.Parse("100"));
        		LISTA_ORIGEM_LOGS.Add("DiasPolitica", Byte.Parse("58"));
        		LISTA_ORIGEM_LOGS.Add("PoliticaAluno", Byte.Parse("99"));
        		LISTA_ORIGEM_LOGS.Add("PoliticaTurma", Byte.Parse("101"));
        		LISTA_ORIGEM_LOGS.Add("TipoDesconto", Byte.Parse("119"));
        		LISTA_ORIGEM_LOGS.Add("Fechamento", Byte.Parse("137"));
        		LISTA_ORIGEM_LOGS.Add("SaldoItem", Byte.Parse("138"));
        		LISTA_ORIGEM_LOGS.Add("Cnab", Byte.Parse("139"));
        		LISTA_ORIGEM_LOGS.Add("TituloCnab", Byte.Parse("140"));
        		LISTA_ORIGEM_LOGS.Add("TipoDescontoEscola", Byte.Parse("141"));
        		LISTA_ORIGEM_LOGS.Add("RetornoCNAB", Byte.Parse("142"));
        		LISTA_ORIGEM_LOGS.Add("TipoNotaFiscal", Byte.Parse("143"));
        		LISTA_ORIGEM_LOGS.Add("SubgrupoConta", Byte.Parse("114"));
        		LISTA_ORIGEM_LOGS.Add("AliquotaUF", Byte.Parse("144"));
        		LISTA_ORIGEM_LOGS.Add("DadosNF", Byte.Parse("145"));
        		LISTA_ORIGEM_LOGS.Add("ItemSubgrupo", Byte.Parse("146"));
        		LISTA_ORIGEM_LOGS.Add("ProgramacaoCurso", Byte.Parse("103"));
        		LISTA_ORIGEM_LOGS.Add("ItemProgramacao", Byte.Parse("75"));
    			LISTA_ORIGEM_LOGS.Add("MalaDireta", Byte.Parse("148"));
                LISTA_ORIGEM_LOGS.Add("PerdaMaterial", Byte.Parse("149"));
        	}
        }
    
    	public int? IdUsuario { get; set; }
    	public int cd_empresa { get; set; }
    
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Escolaridade> Escolaridade { get; set; }
        public DbSet<Midia> Midia { get; set; }
        public DbSet<MotivoBolsa> MotivoBolsa { get; set; }
        public DbSet<MotivoCancelamentoBolsa> MotivoCancelamentoBolsa { get; set; }
        public DbSet<MotivoMatricula> MotivoMatricula { get; set; }
        public DbSet<MotivoNaoMatricula> MotivoNaoMatricula { get; set; }
        public DbSet<TipoContato> TipoContato { get; set; }
        public DbSet<Duracao> Duracao { get; set; }
        public DbSet<Evento> Evento { get; set; }
        public DbSet<Modalidade> Modalidade { get; set; }
        public DbSet<MotivoFalta> MotivoFalta { get; set; }
        public DbSet<Produto> Produto { get; set; }
        public DbSet<Regime> Regime { get; set; }
        public DbSet<Sala> Sala { get; set; }
        public DbSet<TipoDesconto> TipoDesconto { get; set; }
        public DbSet<TipoFinanceiro> TipoFinanceiro { get; set; }
        public DbSet<TipoLiquidacao> TipoLiquidacao { get; set; }
        public DbSet<MotivoDesistencia> MotivoDesistencia { get; set; }
        public DbSet<MovimentacaoFinanceira> MovimentacaoFinanceira { get; set; }
        public DbSet<GrupoEstoque> GrupoEstoque { get; set; }
        public DbSet<TipoAtividadeExtra> TipoAtividadeExtra { get; set; }
        public DbSet<PessoaSGF> PessoaSGF { get; set; }
        public DbSet<Conceito> Conceito { get; set; }
        public DbSet<Feriado> Feriado { get; set; }
        public DbSet<Estagio> Estagio { get; set; }
        public DbSet<Atividade> Atividade { get; set; }
        public DbSet<ClasseTelefoneSGF> ClasseTelefoneSGF { get; set; }
        public DbSet<TelefoneSGF> TelefoneSGF { get; set; }
        public DbSet<TipoEnderecoSGF> TipoEnderecoSGF { get; set; }
        public DbSet<TipoLogradouroSGF> TipoLogradouroSGF { get; set; }
        public DbSet<TipoTelefoneSGF> TipoTelefoneSGF { get; set; }
        public DbSet<UsuarioWebSGF> UsuarioWebSGF { get; set; }
        public DbSet<Curso> Curso { get; set; }
        public DbSet<Item> Item { get; set; }
        public DbSet<Aluno> Aluno { get; set; }
        public DbSet<PoliticaDesconto> PoliticaDesconto { get; set; }
        public DbSet<Turma> Turma { get; set; }
        public DbSet<ItemEscola> ItemEscola { get; set; }
        public DbSet<TipoItem> TipoItem { get; set; }
        public DbSet<Biblioteca> Biblioteca { get; set; }
        public DbSet<FuncionarioSGF> FuncionarioSGF { get; set; }
        public DbSet<CriterioAvaliacao> CriterioAvaliacao { get; set; }
        public DbSet<Avaliacao> Avaliacao { get; set; }
        public DbSet<TipoAvaliacao> TipoAvaliacao { get; set; }
        public DbSet<HabilitacaoProfessor> HabilitacaoProfessor { get; set; }
        public DbSet<ItemProgramacao> ItemProgramacao { get; set; }
        public DbSet<ProgramacaoCurso> ProgramacaoCurso { get; set; }
        public DbSet<Horario> Horario { get; set; }
        public DbSet<PapelSGF> PapelSGF { get; set; }
        public DbSet<AtividadeAluno> AtividadeAluno { get; set; }
        public DbSet<AtividadeExtra> AtividadeExtra { get; set; }
        public DbSet<RelacionamentoSGF> RelacionamentoSGF { get; set; }
        public DbSet<TabelaPreco> TabelaPreco { get; set; }
        public DbSet<AlunoBolsa> AlunoBolsa { get; set; }
        public DbSet<AvaliacaoCurso> AvaliacaoCurso { get; set; }
        public DbSet<AlunoMotivoMatricula> AlunoMotivoMatricula { get; set; }
        public DbSet<Prospect> Prospect { get; set; }
        public DbSet<ProspectMotivoNaoMatricula> ProspectMotivoNaoMatricula { get; set; }
        public DbSet<ProspectProduto> ProspectProduto { get; set; }
        public DbSet<FollowUp> FollowUp { get; set; }
        public DbSet<PessoaEscola> PessoaEscola { get; set; }
        public DbSet<AvaliacaoTurma> AvaliacaoTurma { get; set; }
        public DbSet<GrupoConta> GrupoConta { get; set; }
        public DbSet<PlanoConta> PlanoConta { get; set; }
        public DbSet<SubgrupoConta> SubgrupoConta { get; set; }
        public DbSet<ProfessorTurma> ProfessorTurma { get; set; }
        public DbSet<AlunoTurma> AlunoTurma { get; set; }
        public DbSet<AvaliacaoAluno> AvaliacaoAluno { get; set; }
        public DbSet<ProgramacaoTurma> ProgramacaoTurma { get; set; }
        public DbSet<DiarioAula> DiarioAula { get; set; }
        public DbSet<HorarioProfessorTurma> HorarioProfessorTurma { get; set; }
        public DbSet<FeriadoDesconsiderado> FeriadoDesconsiderado { get; set; }
        public DbSet<Contrato> Contrato { get; set; }
        public DbSet<TaxaMatricula> TaxaMatricula { get; set; }
        public DbSet<vi_contrato> vi_contrato { get; set; }
        public DbSet<Banco> Banco { get; set; }
        public DbSet<LocalMovto> LocalMovto { get; set; }
        public DbSet<Titulo> Titulo { get; set; }
        public DbSet<EnderecoSGF> EnderecoSGF { get; set; }
        public DbSet<LocalidadeSGF> LocalidadeSGF { get; set; }
        public DbSet<EstadoCivilSGF> EstadoCivilSGF { get; set; }
        public DbSet<NomeContrato> NomeContrato { get; set; }
        public DbSet<BaixaTitulo> BaixaTitulo { get; set; }
        public DbSet<vi_diario_aula> vi_diario_aula { get; set; }
        public DbSet<HistoricoAluno> HistoricoAluno { get; set; }
        public DbSet<AlunoEvento> AlunoEvento { get; set; }
        public DbSet<ProspectPeriodo> ProspectPeriodo { get; set; }
        public DbSet<TransacaoFinanceira> TransacaoFinanceira { get; set; }
        public DbSet<Desistencia> Desistencia { get; set; }
        public DbSet<ContaCorrente> ContaCorrente { get; set; }
        public DbSet<Movimento> Movimento { get; set; }
        public DbSet<PoliticaComercial> PoliticaComercial { get; set; }
        public DbSet<Emprestimo> Emprestimo { get; set; }
        public DbSet<PlanoTitulo> PlanoTitulo { get; set; }
        public DbSet<Kardex> Kardex { get; set; }
        public DbSet<ItemPolitica> ItemPolitica { get; set; }
        public DbSet<UsuarioEmpresaSGF> UsuarioEmpresaSGF { get; set; }
        public DbSet<EstadoSGF> EstadoSGF { get; set; }
        public DbSet<Origem> Origem { get; set; }
        public DbSet<Parametro> Parametro { get; set; }
        public DbSet<PoliticaAluno> PoliticaAluno { get; set; }
        public DbSet<PoliticaTurma> PoliticaTurma { get; set; }
        public DbSet<Fechamento> Fechamento { get; set; }
        public DbSet<SaldoItem> SaldoItem { get; set; }
        public DbSet<Cnab> Cnab { get; set; }
        public DbSet<CarteiraCnab> CarteiraCnab { get; set; }
        public DbSet<TituloCnab> TituloCnab { get; set; }
        public DbSet<TipoDescontoEscola> TipoDescontoEscola { get; set; }
        public DbSet<RetornoCNAB> RetornoCNAB { get; set; }
        public DbSet<TituloRetornoCNAB> TituloRetornoCNAB { get; set; }
        public DbSet<ItemSubgrupo> ItemSubgrupo { get; set; }
        public DbSet<SituacaoTributaria> SituacaoTributaria { get; set; }
        public DbSet<TipoNotaFiscal> TipoNotaFiscal { get; set; }
        public DbSet<ItemMovimento> ItemMovimento { get; set; }
        public DbSet<DadosNF> DadosNF { get; set; }
        public DbSet<AliquotaUF> AliquotaUF { get; set; }
        public DbSet<PaisSGF> PaisSGF { get; set; }
        public DbSet<CFOP> CFOP { get; set; }
        public DbSet<AcaoFollowUp> AcaoFollowUp { get; set; }
        public DbSet<FollowUpUsuario> FollowUpUsuario { get; set; }
        public DbSet<FollowUpEscola> FollowUpEscola { get; set; }
        public DbSet<Cheque> Cheque { get; set; }
        public DbSet<GrupoSituacao> GrupoSituacao { get; set; }
        public DbSet<DescontoContrato> DescontoContrato { get; set; }
        public DbSet<ListaEnderecoMala> ListaEnderecoMala { get; set; }
        public DbSet<ListaNaoInscrito> ListaNaoInscrito { get; set; }
        public DbSet<MalaDireta> MalaDireta { get; set; }
        public DbSet<MalaDiretaCadastro> MalaDiretaCadastro { get; set; }
        public DbSet<MalaDiretaProduto> MalaDiretaProduto { get; set; }
        public DbSet<SysApp> SysApp { get; set; }
        public DbSet<MalaDiretaCurso> MalaDiretaCurso { get; set; }
        public DbSet<MalaDiretaPeriodo> MalaDiretaPeriodo { get; set; }
        public DbSet<DescontoTituloCNAB> DescontoTituloCNAB { get; set; }
        public DbSet<AulaPersonalizada> AulaPersonalizada { get; set; }
        public DbSet<AulaPersonalizadaAluno> AulaPersonalizadaAluno { get; set; }
        public DbSet<Atributos> Atributos { get; set; }
        public DbSet<LogGeral> LogGeral { get; set; }
        public DbSet<TipoLog> TipoLog { get; set; }
        public DbSet<LogGeralDetalhe> LogGeralDetalhe { get; set; }
        public DbSet<QualifRelacionamento> QualifRelacionamento { get; set; }
        public DbSet<TratamentoPessoa> TratamentoPessoa { get; set; }
        public DbSet<TipoSociedade> TipoSociedade { get; set; }
        public DbSet<OrgaoExpedidor> OrgaoExpedidor { get; set; }
        public DbSet<Operadora> Operadora { get; set; }
        public DbSet<SysDireitoGrupo> SysDireitoGrupo { get; set; }
        public DbSet<SysDireitoUsuario> SysDireitoUsuario { get; set; }
        public DbSet<SysGrupo> SysGrupo { get; set; }
        public DbSet<SysGrupoUsuario> SysGrupoUsuario { get; set; }
        public DbSet<SysMenu> SysMenu { get; set; }
        public DbSet<AvaliacaoParticipacao> AvaliacaoParticipacao { get; set; }
        public DbSet<AvaliacaoParticipacaoVinc> AvaliacaoParticipacaoVinc { get; set; }
        public DbSet<Participacao> Participacao { get; set; }
        public DbSet<AvaliacaoAlunoParticipacao> AvaliacaoAlunoParticipacao { get; set; }
        public DbSet<CargaProfessor> CargaProfessor { get; set; }
        public DbSet<ObsSaldoCaixa> ObsSaldoCaixa { get; set; }
        public DbSet<DiasPolitica> DiasPolitica { get; set; }
        public DbSet<ReajusteAluno> ReajusteAluno { get; set; }
        public DbSet<ReajusteAnual> ReajusteAnual { get; set; }
        public DbSet<ReajusteCurso> ReajusteCurso { get; set; }
        public DbSet<ReajusteTitulo> ReajusteTitulo { get; set; }
        public DbSet<ReajusteTurma> ReajusteTurma { get; set; }
        public DbSet<ChequeBaixa> ChequeBaixa { get; set; }
        public DbSet<ChequeTransacao> ChequeTransacao { get; set; }
        public DbSet<FuncionarioComissao> FuncionarioComissao { get; set; }
        public DbSet<AnoEscolar> AnoEscolar { get; set; }
        public DbSet<AditamentoBolsa> AditamentoBolsa { get; set; }
        public DbSet<AtividadeCurso> AtividadeCurso { get; set; }
        public DbSet<Nivel> Nivel { get; set; }
        public DbSet<CalendarioAcademico> CalendarioAcademico { get; set; }
        public DbSet<CalendarioEvento> CalendarioEvento { get; set; }
        public DbSet<ProspectDia> ProspectDia { get; set; }
        public DbSet<JsonTeste> T_JSON_TESTE { get; set; }
        public DbSet<Video> Video { get; set; }
        public DbSet<Circular> Circular { get; set; }
        public DbSet<ProspectSite> ProspectSite { get; set; }
        public DbSet<ItemKit> ItemKit { get; set; }
        public DbSet<ItemMovimentoKit> ItemMovimentoKit { get; set; }
        public DbSet<ControleFaltas> ControleFaltas { get; set; }
        public DbSet<ControleFaltasAluno> ControleFaltasAluno { get; set; }
        public DbSet<DespesaTituloCnab> DespesaTituloCnab { get; set; }
        public DbSet<TaxaBancaria> TaxaBancaria { get; set; }
        public DbSet<ProdutoFuncionario> ProdutoFuncionario { get; set; }
        public DbSet<Aditamento> Aditamento { get; set; }
        public DbSet<TituloAditamento> TituloAditamento { get; set; }
        public DbSet<ItemMovItemKit> ItemMovItemKit { get; set; }
        public DbSet<ImportacaoXML> ImportacaoXML { get; set; }
        public DbSet<BaixaAutomatica> BaixaAutomatica { get; set; }
        public DbSet<TitulosBaixaAutomatica> TitulosBaixaAutomatica { get; set; }
        public DbSet<AlunoAulaReposicao> AlunoAulaReposicao { get; set; }
        public DbSet<AulaReposicao> AulaReposicao { get; set; }
        public DbSet<CursoContrato> CursoContrato { get; set; }
        public DbSet<TurmaEscola> TurmaEscola { get; set; }
        public DbSet<AtividadeEscolaAtividade> AtividadeEscolaAtividade { get; set; }
        public DbSet<AtividadeProspect> AtividadeProspect { get; set; }
        public DbSet<AtividadeRecorrencia> AtividadeRecorrencia { get; set; }
        public DbSet<Faq> Faq { get; set; }
        public DbSet<AlunoRestricao> AlunoRestricao { get; set; }
        public DbSet<OrgaoFinanceiro> OrgaoFinanceiro { get; set; }
        public DbSet<vi_curso_ordem> vi_curso_ordem { get; set; }
        public DbSet<LivroCyber> LivroCyber { get; set; }
        public DbSet<MensagemAvaliacao> MensagemAvaliacao { get; set; }
        public DbSet<MensagemAvaliacaoAluno> MensagemAvaliacaoAluno { get; set; }
        public DbSet<PessoaCarta> PessoaCarta { get; set; }
        public DbSet<PessoaRaf> PessoaRaf { get; set; }
        public DbSet<MotivoTransferenciaAluno> MotivoTransferenciaAluno { get; set; }
        public DbSet<TransferenciaAluno> TransferenciaAluno { get; set; }
        public DbSet<ItemCurso> ItemCurso { get; set; }
        public DbSet<vi_aluno_sem_aula> vi_aluno_sem_aula { get; set; }
        public DbSet<vi_carga_horaria> vi_carga_horaria { get; set; }
        public DbSet<vi_raf_com_diario> vi_raf_com_diario { get; set; }
        public DbSet<vi_raf_sem_diario> vi_raf_sem_diario { get; set; }
        public DbSet<vi_livro_devolvido> vi_livro_devolvido { get; set; }
        public DbSet<vi_carga_aluno> vi_carga_aluno { get; set; }
        public DbSet<PessoaPromocao> PessoaPromocao { get; set; }
        public DbSet<EmpresaValorServico> EmpresaValorServico { get; set; }
        public DbSet<FichaSaude> FichaSaude { get; set; }
        public DbSet<PerdaMaterial> PerdaMaterial { get; set; }
        public DbSet<vi_qt_avaliacao_curso> vi_qt_avaliacao_curso { get; set; }
        public DbSet<vi_desistencia_carga> vi_desistencia_carga { get; set; }
        public DbSet<vi_qt_programacao_curso> vi_qt_programacao_curso { get; set; }
        public DbSet<T_DESCONTO> T_DESCONTO { get; set; }
    
        public virtual int sp_enviar_mastersaf(Nullable<int> cd_movto)
        {
            var cd_movtoParameter = cd_movto.HasValue ?
                new ObjectParameter("cd_movto", cd_movto) :
                new ObjectParameter("cd_movto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_enviar_mastersaf", cd_movtoParameter);
        }
    
        public virtual ObjectResult<ReportPagamentoProfessor> st_RptPgtoProfessor(Nullable<int> cd_empresa, Nullable<int> cd_professor, Nullable<byte> id_tipo_relatorio, Nullable<System.DateTime> dt_inicio, Nullable<System.DateTime> dt_fim)
        {
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(int));
    
            var cd_professorParameter = cd_professor.HasValue ?
                new ObjectParameter("cd_professor", cd_professor) :
                new ObjectParameter("cd_professor", typeof(int));
    
            var id_tipo_relatorioParameter = id_tipo_relatorio.HasValue ?
                new ObjectParameter("id_tipo_relatorio", id_tipo_relatorio) :
                new ObjectParameter("id_tipo_relatorio", typeof(byte));
    
            var dt_inicioParameter = dt_inicio.HasValue ?
                new ObjectParameter("dt_inicio", dt_inicio) :
                new ObjectParameter("dt_inicio", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportPagamentoProfessor>("st_RptPgtoProfessor", cd_empresaParameter, cd_professorParameter, id_tipo_relatorioParameter, dt_inicioParameter, dt_fimParameter);
        }
    
        public virtual ObjectResult<ReportPagamentoProfessor> st_RptPgtoProfessor_faltas(Nullable<int> cd_empresa, Nullable<int> cd_professor, Nullable<byte> id_tipo_relatorio, Nullable<System.DateTime> dt_inicio, Nullable<System.DateTime> dt_fim)
        {
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(int));
    
            var cd_professorParameter = cd_professor.HasValue ?
                new ObjectParameter("cd_professor", cd_professor) :
                new ObjectParameter("cd_professor", typeof(int));
    
            var id_tipo_relatorioParameter = id_tipo_relatorio.HasValue ?
                new ObjectParameter("id_tipo_relatorio", id_tipo_relatorio) :
                new ObjectParameter("id_tipo_relatorio", typeof(byte));
    
            var dt_inicioParameter = dt_inicio.HasValue ?
                new ObjectParameter("dt_inicio", dt_inicio) :
                new ObjectParameter("dt_inicio", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportPagamentoProfessor>("st_RptPgtoProfessor_faltas", cd_empresaParameter, cd_professorParameter, id_tipo_relatorioParameter, dt_inicioParameter, dt_fimParameter);
        }
    
        public virtual ObjectResult<ReportPagamentoProfessor> st_RptPgtoProfessor_obs(Nullable<int> cd_empresa, Nullable<int> cd_professor, Nullable<byte> id_tipo_relatorio, Nullable<System.DateTime> dt_inicio, Nullable<System.DateTime> dt_fim)
        {
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(int));
    
            var cd_professorParameter = cd_professor.HasValue ?
                new ObjectParameter("cd_professor", cd_professor) :
                new ObjectParameter("cd_professor", typeof(int));
    
            var id_tipo_relatorioParameter = id_tipo_relatorio.HasValue ?
                new ObjectParameter("id_tipo_relatorio", id_tipo_relatorio) :
                new ObjectParameter("id_tipo_relatorio", typeof(byte));
    
            var dt_inicioParameter = dt_inicio.HasValue ?
                new ObjectParameter("dt_inicio", dt_inicio) :
                new ObjectParameter("dt_inicio", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportPagamentoProfessor>("st_RptPgtoProfessor_obs", cd_empresaParameter, cd_professorParameter, id_tipo_relatorioParameter, dt_inicioParameter, dt_fimParameter);
        }
    
        public virtual int sp_analise_feriado(Nullable<int> cd_feriado, Nullable<bool> ind_excluir)
        {
            var cd_feriadoParameter = cd_feriado.HasValue ?
                new ObjectParameter("cd_feriado", cd_feriado) :
                new ObjectParameter("cd_feriado", typeof(int));
    
            var ind_excluirParameter = ind_excluir.HasValue ?
                new ObjectParameter("ind_excluir", ind_excluir) :
                new ObjectParameter("ind_excluir", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_analise_feriado", cd_feriadoParameter, ind_excluirParameter);
        }
    
        public virtual ObjectResult<LogradouroCEP> SPConsultaCEP(string cep, string uf, string cidade, string logradouro, string bairro, Nullable<int> numero)
        {
            var cepParameter = cep != null ?
                new ObjectParameter("cep", cep) :
                new ObjectParameter("cep", typeof(string));
    
            var ufParameter = uf != null ?
                new ObjectParameter("Uf", uf) :
                new ObjectParameter("Uf", typeof(string));
    
            var cidadeParameter = cidade != null ?
                new ObjectParameter("cidade", cidade) :
                new ObjectParameter("cidade", typeof(string));
    
            var logradouroParameter = logradouro != null ?
                new ObjectParameter("logradouro", logradouro) :
                new ObjectParameter("logradouro", typeof(string));
    
            var bairroParameter = bairro != null ?
                new ObjectParameter("bairro", bairro) :
                new ObjectParameter("bairro", typeof(string));
    
            var numeroParameter = numero.HasValue ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LogradouroCEP>("SPConsultaCEP", cepParameter, ufParameter, cidadeParameter, logradouroParameter, bairroParameter, numeroParameter);
        }
    
        public virtual int sp_gerar_prospect(Nullable<int> nm_integracao, Nullable<byte> id_tipo, Nullable<int> id_teste, string no_pessoa, string email, string fone, string cep, string day_week, string periodo, Nullable<System.DateTime> dt_cadastro, string sexo, Nullable<double> hit, string phase, string course_id, ObjectParameter cod_prospect)
        {
            var nm_integracaoParameter = nm_integracao.HasValue ?
                new ObjectParameter("nm_integracao", nm_integracao) :
                new ObjectParameter("nm_integracao", typeof(int));
    
            var id_tipoParameter = id_tipo.HasValue ?
                new ObjectParameter("id_tipo", id_tipo) :
                new ObjectParameter("id_tipo", typeof(byte));
    
            var id_testeParameter = id_teste.HasValue ?
                new ObjectParameter("id_teste", id_teste) :
                new ObjectParameter("id_teste", typeof(int));
    
            var no_pessoaParameter = no_pessoa != null ?
                new ObjectParameter("no_pessoa", no_pessoa) :
                new ObjectParameter("no_pessoa", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var foneParameter = fone != null ?
                new ObjectParameter("fone", fone) :
                new ObjectParameter("fone", typeof(string));
    
            var cepParameter = cep != null ?
                new ObjectParameter("cep", cep) :
                new ObjectParameter("cep", typeof(string));
    
            var day_weekParameter = day_week != null ?
                new ObjectParameter("day_week", day_week) :
                new ObjectParameter("day_week", typeof(string));
    
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            var dt_cadastroParameter = dt_cadastro.HasValue ?
                new ObjectParameter("dt_cadastro", dt_cadastro) :
                new ObjectParameter("dt_cadastro", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var hitParameter = hit.HasValue ?
                new ObjectParameter("hit", hit) :
                new ObjectParameter("hit", typeof(double));
    
            var phaseParameter = phase != null ?
                new ObjectParameter("phase", phase) :
                new ObjectParameter("phase", typeof(string));
    
            var course_idParameter = course_id != null ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_gerar_prospect", nm_integracaoParameter, id_tipoParameter, id_testeParameter, no_pessoaParameter, emailParameter, foneParameter, cepParameter, day_weekParameter, periodoParameter, dt_cadastroParameter, sexoParameter, hitParameter, phaseParameter, course_idParameter, cod_prospect);
        }
    
        public virtual ObjectResult<sp_RptAvaliacaoEstagio_Result> sp_RptAvaliacaoEstagio(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAvaliacaoEstagio_Result>("sp_RptAvaliacaoEstagio", cd_alunoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sp_RptAvaliacaoTurma_Result> sp_RptAvaliacaoTurma(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAvaliacaoTurma_Result>("sp_RptAvaliacaoTurma", cd_alunoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sp_RptDiarioAluno_Result> sp_RptDiarioAluno(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptDiarioAluno_Result>("sp_RptDiarioAluno", cd_alunoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sp_RptEventoAluno_Result> sp_RptEventoAluno(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptEventoAluno_Result>("sp_RptEventoAluno", cd_alunoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoAluno_Result> sp_RptHistoricoAluno(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoAluno_Result>("sp_RptHistoricoAluno", cd_alunoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoAlunoM_Result> sp_RptHistoricoAlunoM(Nullable<int> cd_aluno)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoAlunoM_Result>("sp_RptHistoricoAlunoM", cd_alunoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoAtividade_Result> sp_RptHistoricoAtividade(Nullable<int> cd_aluno)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoAtividade_Result>("sp_RptHistoricoAtividade", cd_alunoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoConceito_Result> sp_RptHistoricoConceito(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoConceito_Result>("sp_RptHistoricoConceito", cd_alunoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoEstagio_Result> sp_RptHistoricoEstagio(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoEstagio_Result>("sp_RptHistoricoEstagio", cd_alunoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoFollow_Result> sp_RptHistoricoFollow(Nullable<int> cd_aluno)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoFollow_Result>("sp_RptHistoricoFollow", cd_alunoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoItem_Result> sp_RptHistoricoItem(Nullable<int> cd_aluno)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoItem_Result>("sp_RptHistoricoItem", cd_alunoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoObs_Result> sp_RptHistoricoObs(Nullable<int> cd_aluno)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoObs_Result>("sp_RptHistoricoObs", cd_alunoParameter);
        }
    
        public virtual ObjectResult<sp_RptHistoricoTitulos_Result> sp_RptHistoricoTitulos(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptHistoricoTitulos_Result>("sp_RptHistoricoTitulos", cd_alunoParameter, tipoParameter);
        }
    
        public virtual ObjectResult<sp_RptTurmasAvaliacoes_Result> sp_RptTurmasAvaliacoes(Nullable<int> cd_aluno, string tipo)
        {
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptTurmasAvaliacoes_Result>("sp_RptTurmasAvaliacoes", cd_alunoParameter, tipoParameter);
        }
    
        public virtual int st_RptEtiqueta(Nullable<int> cod_mala_direta)
        {
            var cod_mala_diretaParameter = cod_mala_direta.HasValue ?
                new ObjectParameter("cod_mala_direta", cod_mala_direta) :
                new ObjectParameter("cod_mala_direta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_RptEtiqueta", cod_mala_diretaParameter);
        }
    
        public virtual ObjectResult<sp_RptTurmaControleFalta_Result> sp_RptTurmaControleFalta(Nullable<int> cd_turma)
        {
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptTurmaControleFalta_Result>("sp_RptTurmaControleFalta", cd_turmaParameter);
        }
    
        public virtual ObjectResult<sp_RptControleFaltas_Result> sp_RptControleFaltas(Nullable<int> cd_escola, Nullable<int> cd_turma, Nullable<int> cd_produto, Nullable<int> cd_curso, Nullable<byte> tipo, Nullable<int> cd_professor, Nullable<byte> sit_turma, Nullable<int> cd_nivel, Nullable<System.DateTime> dt_inicio, Nullable<System.DateTime> dt_fim, string id_situacao)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var cd_produtoParameter = cd_produto.HasValue ?
                new ObjectParameter("cd_produto", cd_produto) :
                new ObjectParameter("cd_produto", typeof(int));
    
            var cd_cursoParameter = cd_curso.HasValue ?
                new ObjectParameter("cd_curso", cd_curso) :
                new ObjectParameter("cd_curso", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(byte));
    
            var cd_professorParameter = cd_professor.HasValue ?
                new ObjectParameter("cd_professor", cd_professor) :
                new ObjectParameter("cd_professor", typeof(int));
    
            var sit_turmaParameter = sit_turma.HasValue ?
                new ObjectParameter("sit_turma", sit_turma) :
                new ObjectParameter("sit_turma", typeof(byte));
    
            var cd_nivelParameter = cd_nivel.HasValue ?
                new ObjectParameter("cd_nivel", cd_nivel) :
                new ObjectParameter("cd_nivel", typeof(int));
    
            var dt_inicioParameter = dt_inicio.HasValue ?
                new ObjectParameter("dt_inicio", dt_inicio) :
                new ObjectParameter("dt_inicio", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            var id_situacaoParameter = id_situacao != null ?
                new ObjectParameter("id_situacao", id_situacao) :
                new ObjectParameter("id_situacao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptControleFaltas_Result>("sp_RptControleFaltas", cd_escolaParameter, cd_turmaParameter, cd_produtoParameter, cd_cursoParameter, tipoParameter, cd_professorParameter, sit_turmaParameter, cd_nivelParameter, dt_inicioParameter, dt_fimParameter, id_situacaoParameter);
        }
    
        public virtual int sp_fechamento_estoque(Nullable<int> cd_fechamento, Nullable<byte> id_tipo)
        {
            var cd_fechamentoParameter = cd_fechamento.HasValue ?
                new ObjectParameter("cd_fechamento", cd_fechamento) :
                new ObjectParameter("cd_fechamento", typeof(int));
    
            var id_tipoParameter = id_tipo.HasValue ?
                new ObjectParameter("id_tipo", id_tipo) :
                new ObjectParameter("id_tipo", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fechamento_estoque", cd_fechamentoParameter, id_tipoParameter);
        }
    
        public virtual int sp_gerar_matricula(string dc_turma, Nullable<System.DateTime> dt_inicial, Nullable<System.DateTime> dt_final, Nullable<bool> id_turma_nova, Nullable<int> cd_layout, Nullable<System.DateTime> dt_termino, Nullable<int> cd_usuario, ObjectParameter mensagem, Nullable<int> fuso)
        {
            var dc_turmaParameter = dc_turma != null ?
                new ObjectParameter("dc_turma", dc_turma) :
                new ObjectParameter("dc_turma", typeof(string));
    
            var dt_inicialParameter = dt_inicial.HasValue ?
                new ObjectParameter("dt_inicial", dt_inicial) :
                new ObjectParameter("dt_inicial", typeof(System.DateTime));
    
            var dt_finalParameter = dt_final.HasValue ?
                new ObjectParameter("dt_final", dt_final) :
                new ObjectParameter("dt_final", typeof(System.DateTime));
    
            var id_turma_novaParameter = id_turma_nova.HasValue ?
                new ObjectParameter("id_turma_nova", id_turma_nova) :
                new ObjectParameter("id_turma_nova", typeof(bool));
    
            var cd_layoutParameter = cd_layout.HasValue ?
                new ObjectParameter("cd_layout", cd_layout) :
                new ObjectParameter("cd_layout", typeof(int));
    
            var dt_terminoParameter = dt_termino.HasValue ?
                new ObjectParameter("dt_termino", dt_termino) :
                new ObjectParameter("dt_termino", typeof(System.DateTime));
    
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            var fusoParameter = fuso.HasValue ?
                new ObjectParameter("fuso", fuso) :
                new ObjectParameter("fuso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_gerar_matricula", dc_turmaParameter, dt_inicialParameter, dt_finalParameter, id_turma_novaParameter, cd_layoutParameter, dt_terminoParameter, cd_usuarioParameter, mensagem, fusoParameter);
        }
    
        public virtual int sp_cancelar_rematricula(Nullable<int> cd_turma, Nullable<int> cd_usuario, Nullable<int> fuso)
        {
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            var fusoParameter = fuso.HasValue ?
                new ObjectParameter("fuso", fuso) :
                new ObjectParameter("fuso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cancelar_rematricula", cd_turmaParameter, cd_usuarioParameter, fusoParameter);
        }
    
        public virtual int sp_excluir_contrato(Nullable<int> cd_contrato, Nullable<int> cd_usuario, Nullable<int> fuso)
        {
            var cd_contratoParameter = cd_contrato.HasValue ?
                new ObjectParameter("cd_contrato", cd_contrato) :
                new ObjectParameter("cd_contrato", typeof(int));
    
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            var fusoParameter = fuso.HasValue ?
                new ObjectParameter("fuso", fuso) :
                new ObjectParameter("fuso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_excluir_contrato", cd_contratoParameter, cd_usuarioParameter, fusoParameter);
        }
    
        public virtual int sp_dir_xml(Nullable<int> cd_usuario)
        {
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dir_xml", cd_usuarioParameter);
        }
    
        public virtual int sp_import_XML(Nullable<int> cd_usuario, ObjectParameter msg)
        {
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_import_XML", cd_usuarioParameter, msg);
        }
    
        public virtual int sp_gerar_baixa_automatica(Nullable<int> cd_baixa_automatica, Nullable<int> cd_usuario)
        {
            var cd_baixa_automaticaParameter = cd_baixa_automatica.HasValue ?
                new ObjectParameter("cd_baixa_automatica", cd_baixa_automatica) :
                new ObjectParameter("cd_baixa_automatica", typeof(int));
    
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_gerar_baixa_automatica", cd_baixa_automaticaParameter, cd_usuarioParameter);
        }
    
        public virtual ObjectResult<sp_RptAulaReposicao_Result> sp_RptAulaReposicao(Nullable<int> cd_escola, Nullable<System.DateTime> dta_ini, Nullable<System.DateTime> dta_fim, Nullable<int> cd_turma, Nullable<int> cd_funcionario, Nullable<int> cd_aluno, Nullable<byte> id_participacao)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var dta_iniParameter = dta_ini.HasValue ?
                new ObjectParameter("dta_ini", dta_ini) :
                new ObjectParameter("dta_ini", typeof(System.DateTime));
    
            var dta_fimParameter = dta_fim.HasValue ?
                new ObjectParameter("dta_fim", dta_fim) :
                new ObjectParameter("dta_fim", typeof(System.DateTime));
    
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var cd_funcionarioParameter = cd_funcionario.HasValue ?
                new ObjectParameter("cd_funcionario", cd_funcionario) :
                new ObjectParameter("cd_funcionario", typeof(int));
    
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var id_participacaoParameter = id_participacao.HasValue ?
                new ObjectParameter("id_participacao", id_participacao) :
                new ObjectParameter("id_participacao", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAulaReposicao_Result>("sp_RptAulaReposicao", cd_escolaParameter, dta_iniParameter, dta_fimParameter, cd_turmaParameter, cd_funcionarioParameter, cd_alunoParameter, id_participacaoParameter);
        }
    
        public virtual ObjectResult<sp_RptAulaReposicaoAluno_Result> sp_RptAulaReposicaoAluno(Nullable<int> cd_aula_reposicao, Nullable<int> cd_aluno, Nullable<byte> id_participou)
        {
            var cd_aula_reposicaoParameter = cd_aula_reposicao.HasValue ?
                new ObjectParameter("cd_aula_reposicao", cd_aula_reposicao) :
                new ObjectParameter("cd_aula_reposicao", typeof(int));
    
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var id_participouParameter = id_participou.HasValue ?
                new ObjectParameter("id_participou", id_participou) :
                new ObjectParameter("id_participou", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAulaReposicaoAluno_Result>("sp_RptAulaReposicaoAluno", cd_aula_reposicaoParameter, cd_alunoParameter, id_participouParameter);
        }
    
        public virtual ObjectResult<sp_listar_horario_aula_reposicao_Result> sp_listar_horario_aula_reposicao(Nullable<System.DateTime> dt_aula, Nullable<int> cd_professor, Nullable<int> cd_turma, Nullable<int> cd_aula_reposicao, string strAlunos)
        {
            var dt_aulaParameter = dt_aula.HasValue ?
                new ObjectParameter("dt_aula", dt_aula) :
                new ObjectParameter("dt_aula", typeof(System.DateTime));
    
            var cd_professorParameter = cd_professor.HasValue ?
                new ObjectParameter("cd_professor", cd_professor) :
                new ObjectParameter("cd_professor", typeof(int));
    
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var cd_aula_reposicaoParameter = cd_aula_reposicao.HasValue ?
                new ObjectParameter("cd_aula_reposicao", cd_aula_reposicao) :
                new ObjectParameter("cd_aula_reposicao", typeof(int));
    
            var strAlunosParameter = strAlunos != null ?
                new ObjectParameter("strAlunos", strAlunos) :
                new ObjectParameter("strAlunos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_horario_aula_reposicao_Result>("sp_listar_horario_aula_reposicao", dt_aulaParameter, cd_professorParameter, cd_turmaParameter, cd_aula_reposicaoParameter, strAlunosParameter);
        }
    
        public virtual ObjectResult<Nullable<System.TimeSpan>> sp_horario_aula_reposicao(Nullable<System.DateTime> dt_aula, Nullable<int> cd_professor, Nullable<int> cd_turma, Nullable<int> cd_aula_reposicao, string strAlunos)
        {
            var dt_aulaParameter = dt_aula.HasValue ?
                new ObjectParameter("dt_aula", dt_aula) :
                new ObjectParameter("dt_aula", typeof(System.DateTime));
    
            var cd_professorParameter = cd_professor.HasValue ?
                new ObjectParameter("cd_professor", cd_professor) :
                new ObjectParameter("cd_professor", typeof(int));
    
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var cd_aula_reposicaoParameter = cd_aula_reposicao.HasValue ?
                new ObjectParameter("cd_aula_reposicao", cd_aula_reposicao) :
                new ObjectParameter("cd_aula_reposicao", typeof(int));
    
            var strAlunosParameter = strAlunos != null ?
                new ObjectParameter("strAlunos", strAlunos) :
                new ObjectParameter("strAlunos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.TimeSpan>>("sp_horario_aula_reposicao", dt_aulaParameter, cd_professorParameter, cd_turmaParameter, cd_aula_reposicaoParameter, strAlunosParameter);
        }
    
        public virtual int sp_ins_avaliacao_nula(Nullable<int> cd_turma, Nullable<int> cd_tipo_avaliacao)
        {
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var cd_tipo_avaliacaoParameter = cd_tipo_avaliacao.HasValue ?
                new ObjectParameter("cd_tipo_avaliacao", cd_tipo_avaliacao) :
                new ObjectParameter("cd_tipo_avaliacao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_avaliacao_nula", cd_turmaParameter, cd_tipo_avaliacaoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_verifica_aula_reposicao(Nullable<System.TimeSpan> hini, Nullable<System.TimeSpan> hfim, Nullable<System.DateTime> dt_aula, Nullable<int> cd_professor, Nullable<int> cd_turma, Nullable<int> cd_aula_reposicao, Nullable<int> cd_escola, string strAlunos)
        {
            var hiniParameter = hini.HasValue ?
                new ObjectParameter("hini", hini) :
                new ObjectParameter("hini", typeof(System.TimeSpan));
    
            var hfimParameter = hfim.HasValue ?
                new ObjectParameter("hfim", hfim) :
                new ObjectParameter("hfim", typeof(System.TimeSpan));
    
            var dt_aulaParameter = dt_aula.HasValue ?
                new ObjectParameter("dt_aula", dt_aula) :
                new ObjectParameter("dt_aula", typeof(System.DateTime));
    
            var cd_professorParameter = cd_professor.HasValue ?
                new ObjectParameter("cd_professor", cd_professor) :
                new ObjectParameter("cd_professor", typeof(int));
    
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var cd_aula_reposicaoParameter = cd_aula_reposicao.HasValue ?
                new ObjectParameter("cd_aula_reposicao", cd_aula_reposicao) :
                new ObjectParameter("cd_aula_reposicao", typeof(int));
    
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var strAlunosParameter = strAlunos != null ?
                new ObjectParameter("strAlunos", strAlunos) :
                new ObjectParameter("strAlunos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_verifica_aula_reposicao", hiniParameter, hfimParameter, dt_aulaParameter, cd_professorParameter, cd_turmaParameter, cd_aula_reposicaoParameter, cd_escolaParameter, strAlunosParameter);
        }
    
        public virtual ObjectResult<sp_RptAtividadeExtra_Result> sp_RptAtividadeExtra(Nullable<int> cd_escola, Nullable<System.DateTime> dta_ini, Nullable<System.DateTime> dta_fim, Nullable<int> cd_produto, Nullable<int> cd_curso, Nullable<int> cd_funcionario, Nullable<int> cd_aluno, Nullable<byte> id_participacao, Nullable<byte> id_lancada)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var dta_iniParameter = dta_ini.HasValue ?
                new ObjectParameter("dta_ini", dta_ini) :
                new ObjectParameter("dta_ini", typeof(System.DateTime));
    
            var dta_fimParameter = dta_fim.HasValue ?
                new ObjectParameter("dta_fim", dta_fim) :
                new ObjectParameter("dta_fim", typeof(System.DateTime));
    
            var cd_produtoParameter = cd_produto.HasValue ?
                new ObjectParameter("cd_produto", cd_produto) :
                new ObjectParameter("cd_produto", typeof(int));
    
            var cd_cursoParameter = cd_curso.HasValue ?
                new ObjectParameter("cd_curso", cd_curso) :
                new ObjectParameter("cd_curso", typeof(int));
    
            var cd_funcionarioParameter = cd_funcionario.HasValue ?
                new ObjectParameter("cd_funcionario", cd_funcionario) :
                new ObjectParameter("cd_funcionario", typeof(int));
    
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var id_participacaoParameter = id_participacao.HasValue ?
                new ObjectParameter("id_participacao", id_participacao) :
                new ObjectParameter("id_participacao", typeof(byte));
    
            var id_lancadaParameter = id_lancada.HasValue ?
                new ObjectParameter("id_lancada", id_lancada) :
                new ObjectParameter("id_lancada", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAtividadeExtra_Result>("sp_RptAtividadeExtra", cd_escolaParameter, dta_iniParameter, dta_fimParameter, cd_produtoParameter, cd_cursoParameter, cd_funcionarioParameter, cd_alunoParameter, id_participacaoParameter, id_lancadaParameter);
        }
    
        public virtual ObjectResult<sp_RptAtividadeExtraAluno_Result> sp_RptAtividadeExtraAluno(Nullable<int> cd_atividade_extra, Nullable<int> cd_aluno, Nullable<byte> id_participou, Nullable<byte> id_lancada, Nullable<int> cd_escola)
        {
            var cd_atividade_extraParameter = cd_atividade_extra.HasValue ?
                new ObjectParameter("cd_atividade_extra", cd_atividade_extra) :
                new ObjectParameter("cd_atividade_extra", typeof(int));
    
            var cd_alunoParameter = cd_aluno.HasValue ?
                new ObjectParameter("cd_aluno", cd_aluno) :
                new ObjectParameter("cd_aluno", typeof(int));
    
            var id_participouParameter = id_participou.HasValue ?
                new ObjectParameter("id_participou", id_participou) :
                new ObjectParameter("id_participou", typeof(byte));
    
            var id_lancadaParameter = id_lancada.HasValue ?
                new ObjectParameter("id_lancada", id_lancada) :
                new ObjectParameter("id_lancada", typeof(byte));
    
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAtividadeExtraAluno_Result>("sp_RptAtividadeExtraAluno", cd_atividade_extraParameter, cd_alunoParameter, id_participouParameter, id_lancadaParameter, cd_escolaParameter);
        }
    
        public virtual ObjectResult<st_RptFaixaEtaria_Result> st_RptFaixaEtaria(Nullable<int> cd_escola, Nullable<byte> tipo, Nullable<byte> idade_min, Nullable<byte> idade_max, Nullable<int> cd_turma)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(byte));
    
            var idade_minParameter = idade_min.HasValue ?
                new ObjectParameter("idade_min", idade_min) :
                new ObjectParameter("idade_min", typeof(byte));
    
            var idade_maxParameter = idade_max.HasValue ?
                new ObjectParameter("idade_max", idade_max) :
                new ObjectParameter("idade_max", typeof(byte));
    
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_RptFaixaEtaria_Result>("st_RptFaixaEtaria", cd_escolaParameter, tipoParameter, idade_minParameter, idade_maxParameter, cd_turmaParameter);
        }
    
        public virtual ObjectResult<sp_RptInventario_Result> sp_RptInventario(Nullable<int> cd_escola, Nullable<System.DateTime> dt_analise, Nullable<byte> id_valor, string tp_item)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var dt_analiseParameter = dt_analise.HasValue ?
                new ObjectParameter("dt_analise", dt_analise) :
                new ObjectParameter("dt_analise", typeof(System.DateTime));
    
            var id_valorParameter = id_valor.HasValue ?
                new ObjectParameter("id_valor", id_valor) :
                new ObjectParameter("id_valor", typeof(byte));
    
            var tp_itemParameter = tp_item != null ?
                new ObjectParameter("tp_item", tp_item) :
                new ObjectParameter("tp_item", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptInventario_Result>("sp_RptInventario", cd_escolaParameter, dt_analiseParameter, id_valorParameter, tp_itemParameter);
        }
    
        public virtual ObjectResult<sp_RptAlunoRestricao_Result> sp_RptAlunoRestricao(Nullable<int> cd_escola, Nullable<System.DateTime> dt_ini, Nullable<System.DateTime> dt_fim, Nullable<byte> tipo_data, Nullable<int> cd_orgao)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var dt_iniParameter = dt_ini.HasValue ?
                new ObjectParameter("dt_ini", dt_ini) :
                new ObjectParameter("dt_ini", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            var tipo_dataParameter = tipo_data.HasValue ?
                new ObjectParameter("tipo_data", tipo_data) :
                new ObjectParameter("tipo_data", typeof(byte));
    
            var cd_orgaoParameter = cd_orgao.HasValue ?
                new ObjectParameter("cd_orgao", cd_orgao) :
                new ObjectParameter("cd_orgao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAlunoRestricao_Result>("sp_RptAlunoRestricao", cd_escolaParameter, dt_iniParameter, dt_fimParameter, tipo_dataParameter, cd_orgaoParameter);
        }
    
        public virtual ObjectResult<sp_RptAvaliacao_Result> sp_RptAvaliacao(Nullable<int> cd_escola, Nullable<int> cd_turma, Nullable<int> cd_curso, Nullable<byte> situacao, Nullable<int> cd_produto, Nullable<int> cd_funcionario, Nullable<int> cd_regime, Nullable<System.DateTime> dt_ini, Nullable<System.DateTime> dt_fim, Nullable<bool> isConceito)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var cd_cursoParameter = cd_curso.HasValue ?
                new ObjectParameter("cd_curso", cd_curso) :
                new ObjectParameter("cd_curso", typeof(int));
    
            var situacaoParameter = situacao.HasValue ?
                new ObjectParameter("situacao", situacao) :
                new ObjectParameter("situacao", typeof(byte));
    
            var cd_produtoParameter = cd_produto.HasValue ?
                new ObjectParameter("cd_produto", cd_produto) :
                new ObjectParameter("cd_produto", typeof(int));
    
            var cd_funcionarioParameter = cd_funcionario.HasValue ?
                new ObjectParameter("cd_funcionario", cd_funcionario) :
                new ObjectParameter("cd_funcionario", typeof(int));
    
            var cd_regimeParameter = cd_regime.HasValue ?
                new ObjectParameter("cd_regime", cd_regime) :
                new ObjectParameter("cd_regime", typeof(int));
    
            var dt_iniParameter = dt_ini.HasValue ?
                new ObjectParameter("dt_ini", dt_ini) :
                new ObjectParameter("dt_ini", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            var isConceitoParameter = isConceito.HasValue ?
                new ObjectParameter("isConceito", isConceito) :
                new ObjectParameter("isConceito", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAvaliacao_Result>("sp_RptAvaliacao", cd_escolaParameter, cd_turmaParameter, cd_cursoParameter, situacaoParameter, cd_produtoParameter, cd_funcionarioParameter, cd_regimeParameter, dt_iniParameter, dt_fimParameter, isConceitoParameter);
        }
    
        public virtual int sp_verificar_grupo_cyber(string no_turma, Nullable<int> id_unidade)
        {
            var no_turmaParameter = no_turma != null ?
                new ObjectParameter("no_turma", no_turma) :
                new ObjectParameter("no_turma", typeof(string));
    
            var id_unidadeParameter = id_unidade.HasValue ?
                new ObjectParameter("id_unidade", id_unidade) :
                new ObjectParameter("id_unidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_verificar_grupo_cyber", no_turmaParameter, id_unidadeParameter);
        }
    
        public virtual ObjectResult<sp_Rptmatriculas_outros_produtos_Result> sp_Rptmatriculas_outros_produtos(Nullable<int> cd_escola, Nullable<int> cd_produto, Nullable<System.DateTime> dta_ini, Nullable<System.DateTime> dta_fim, Nullable<byte> qtd_max)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var cd_produtoParameter = cd_produto.HasValue ?
                new ObjectParameter("cd_produto", cd_produto) :
                new ObjectParameter("cd_produto", typeof(int));
    
            var dta_iniParameter = dta_ini.HasValue ?
                new ObjectParameter("dta_ini", dta_ini) :
                new ObjectParameter("dta_ini", typeof(System.DateTime));
    
            var dta_fimParameter = dta_fim.HasValue ?
                new ObjectParameter("dta_fim", dta_fim) :
                new ObjectParameter("dta_fim", typeof(System.DateTime));
    
            var qtd_maxParameter = qtd_max.HasValue ?
                new ObjectParameter("qtd_max", qtd_max) :
                new ObjectParameter("qtd_max", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rptmatriculas_outros_produtos_Result>("sp_Rptmatriculas_outros_produtos", cd_escolaParameter, cd_produtoParameter, dta_iniParameter, dta_fimParameter, qtd_maxParameter);
        }
    
        public virtual int sp_insert_login(Nullable<int> cd_usuario, Nullable<int> cd_escola, Nullable<int> fuso_horario)
        {
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var fuso_horarioParameter = fuso_horario.HasValue ?
                new ObjectParameter("fuso_horario", fuso_horario) :
                new ObjectParameter("fuso_horario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_login", cd_usuarioParameter, cd_escolaParameter, fuso_horarioParameter);
        }
    
        public virtual ObjectResult<sp_RptCartaQuitacao_Result> sp_RptCartaQuitacao(Nullable<int> cd_escola, Nullable<short> ano, Nullable<int> cd_pessoa)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(short));
    
            var cd_pessoaParameter = cd_pessoa.HasValue ?
                new ObjectParameter("cd_pessoa", cd_pessoa) :
                new ObjectParameter("cd_pessoa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptCartaQuitacao_Result>("sp_RptCartaQuitacao", cd_escolaParameter, anoParameter, cd_pessoaParameter);
        }
    
        public virtual ObjectResult<sp_RptAvaliacaoSub_Result> sp_RptAvaliacaoSub(Nullable<int> cd_turma)
        {
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAvaliacaoSub_Result>("sp_RptAvaliacaoSub", cd_turmaParameter);
        }
    
        public virtual int sp_zerar_saldos_financeiros(Nullable<int> cd_escola, Nullable<int> cd_tipo_liquidacao, Nullable<System.DateTime> dta_base, Nullable<byte> tipo)
        {
            var cd_escolaParameter = cd_escola.HasValue ?
                new ObjectParameter("cd_escola", cd_escola) :
                new ObjectParameter("cd_escola", typeof(int));
    
            var cd_tipo_liquidacaoParameter = cd_tipo_liquidacao.HasValue ?
                new ObjectParameter("cd_tipo_liquidacao", cd_tipo_liquidacao) :
                new ObjectParameter("cd_tipo_liquidacao", typeof(int));
    
            var dta_baseParameter = dta_base.HasValue ?
                new ObjectParameter("dta_base", dta_base) :
                new ObjectParameter("dta_base", typeof(System.DateTime));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_zerar_saldos_financeiros", cd_escolaParameter, cd_tipo_liquidacaoParameter, dta_baseParameter, tipoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_encerrar_turmas(string dc_turma, Nullable<System.DateTime> dt_termino, Nullable<int> cd_usuario, Nullable<int> fuso)
        {
            var dc_turmaParameter = dc_turma != null ?
                new ObjectParameter("dc_turma", dc_turma) :
                new ObjectParameter("dc_turma", typeof(string));
    
            var dt_terminoParameter = dt_termino.HasValue ?
                new ObjectParameter("dt_termino", dt_termino) :
                new ObjectParameter("dt_termino", typeof(System.DateTime));
    
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            var fusoParameter = fuso.HasValue ?
                new ObjectParameter("fuso", fuso) :
                new ObjectParameter("fuso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_encerrar_turmas", dc_turmaParameter, dt_terminoParameter, cd_usuarioParameter, fusoParameter);
        }
    
        public virtual int sp_cancelar_encerramento(string dc_turma, Nullable<int> cd_usuario, Nullable<int> fuso)
        {
            var dc_turmaParameter = dc_turma != null ?
                new ObjectParameter("dc_turma", dc_turma) :
                new ObjectParameter("dc_turma", typeof(string));
    
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            var fusoParameter = fuso.HasValue ?
                new ObjectParameter("fuso", fuso) :
                new ObjectParameter("fuso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cancelar_encerramento", dc_turmaParameter, cd_usuarioParameter, fusoParameter);
        }
    
        public virtual ObjectResult<sp_login_escolas_Result> sp_login_escolas(Nullable<System.DateTime> dt_analise, Nullable<bool> id_login, Nullable<byte> id_matricula)
        {
            var dt_analiseParameter = dt_analise.HasValue ?
                new ObjectParameter("dt_analise", dt_analise) :
                new ObjectParameter("dt_analise", typeof(System.DateTime));
    
            var id_loginParameter = id_login.HasValue ?
                new ObjectParameter("id_login", id_login) :
                new ObjectParameter("id_login", typeof(bool));
    
            var id_matriculaParameter = id_matricula.HasValue ?
                new ObjectParameter("id_matricula", id_matricula) :
                new ObjectParameter("id_matricula", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_escolas_Result>("sp_login_escolas", dt_analiseParameter, id_loginParameter, id_matriculaParameter);
        }
    
        public virtual int sp_processar_perda_material(Nullable<int> cd_perda_material, Nullable<int> cd_usuario, Nullable<byte> fuso)
        {
            var cd_perda_materialParameter = cd_perda_material.HasValue ?
                new ObjectParameter("cd_perda_material", cd_perda_material) :
                new ObjectParameter("cd_perda_material", typeof(int));
    
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            var fusoParameter = fuso.HasValue ?
                new ObjectParameter("fuso", fuso) :
                new ObjectParameter("fuso", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_processar_perda_material", cd_perda_materialParameter, cd_usuarioParameter, fusoParameter);
        }
    
        public virtual ObjectResult<sp_RptAvaliacaoTurmaConceito_Result> sp_RptAvaliacaoTurmaConceito(Nullable<int> cd_turma)
        {
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RptAvaliacaoTurmaConceito_Result>("sp_RptAvaliacaoTurmaConceito", cd_turmaParameter);
        }
    
        public virtual ObjectResult<sp_getRptMediaAlunos_Result> sp_getRptMediaAlunos(Nullable<int> cd_pessoa_escola, Nullable<int> cd_turma, Nullable<int> tipoTurma, Nullable<int> cdCurso, Nullable<int> cdProduto, Nullable<byte> pesOpcao, Nullable<byte> pesTipoAluno, Nullable<double> vl_media, Nullable<System.DateTime> dt_inicial, Nullable<System.DateTime> dt_final)
        {
            var cd_pessoa_escolaParameter = cd_pessoa_escola.HasValue ?
                new ObjectParameter("cd_pessoa_escola", cd_pessoa_escola) :
                new ObjectParameter("cd_pessoa_escola", typeof(int));
    
            var cd_turmaParameter = cd_turma.HasValue ?
                new ObjectParameter("cd_turma", cd_turma) :
                new ObjectParameter("cd_turma", typeof(int));
    
            var tipoTurmaParameter = tipoTurma.HasValue ?
                new ObjectParameter("tipoTurma", tipoTurma) :
                new ObjectParameter("tipoTurma", typeof(int));
    
            var cdCursoParameter = cdCurso.HasValue ?
                new ObjectParameter("cdCurso", cdCurso) :
                new ObjectParameter("cdCurso", typeof(int));
    
            var cdProdutoParameter = cdProduto.HasValue ?
                new ObjectParameter("cdProduto", cdProduto) :
                new ObjectParameter("cdProduto", typeof(int));
    
            var pesOpcaoParameter = pesOpcao.HasValue ?
                new ObjectParameter("pesOpcao", pesOpcao) :
                new ObjectParameter("pesOpcao", typeof(byte));
    
            var pesTipoAlunoParameter = pesTipoAluno.HasValue ?
                new ObjectParameter("pesTipoAluno", pesTipoAluno) :
                new ObjectParameter("pesTipoAluno", typeof(byte));
    
            var vl_mediaParameter = vl_media.HasValue ?
                new ObjectParameter("vl_media", vl_media) :
                new ObjectParameter("vl_media", typeof(double));
    
            var dt_inicialParameter = dt_inicial.HasValue ?
                new ObjectParameter("dt_inicial", dt_inicial) :
                new ObjectParameter("dt_inicial", typeof(System.DateTime));
    
            var dt_finalParameter = dt_final.HasValue ?
                new ObjectParameter("dt_final", dt_final) :
                new ObjectParameter("dt_final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getRptMediaAlunos_Result>("sp_getRptMediaAlunos", cd_pessoa_escolaParameter, cd_turmaParameter, tipoTurmaParameter, cdCursoParameter, cdProdutoParameter, pesOpcaoParameter, pesTipoAlunoParameter, vl_mediaParameter, dt_inicialParameter, dt_finalParameter);
        }
    	
        public override int SaveChanges() {
            //LBM Em 17/05/2022 vai voltar a gravar log geral;
            if(IdUsuario != null)
                return SaveChanges(IdUsuario.Value, cd_empresa);
    		else
    			return base.SaveChanges();
        }
    
        public int SaveChanges(int userId, int cd_empresa) {
            List<DbEntityEntryComp> listaAuditoria = new List<DbEntityEntryComp>();
            foreach(var ent in this.ChangeTracker.Entries().Where(p => p.State == System.Data.Entity.EntityState.Added || p.State == System.Data.Entity.EntityState.Deleted || p.State == System.Data.Entity.EntityState.Modified)) {
                // For each changed record, get the audit record entries and add them
                DbEntityEntryComp dbEEC = new DbEntityEntryComp(ent, ent.State);
                listaAuditoria.Add(dbEEC);
            }
            List<LogGeral> LogGeralDifAdd = new List<LogGeral>();
            List<LogGeral> LogGeralDifModified = new List<LogGeral>();
            //Prepara as auditoria das entidades que são de modificação:
            //foreach(var ent in listaAuditoria)
            for (int i = listaAuditoria.Count - 1; i >= 0; i--)
            {
                DbEntityEntryComp ent = listaAuditoria[i];
                foreach (LogGeral x in this.GetAuditRecordsForChange(ent, userId, cd_empresa))
                    if (!ent.OriginalStatus.Equals(System.Data.Entity.EntityState.Added))
                    {
                        LogGeralDifAdd.Add(x);
                        listaAuditoria.Remove(ent);
                    }
            }
            this.LogGeral.AddRange(LogGeralDifAdd);                
            // Chama o save changes para atualizar os identitys:
            //using (var transaction = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.Snapshot, Timeout = TimeSpan.FromSeconds(36000) })) {
        	    var retorno = base.SaveChanges();
                    
        	//	((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 36000;
                // Prepara as auditorias das entidades que não são de modificação:
                foreach(var ent in listaAuditoria)
                    foreach(LogGeral x in this.GetAuditRecordsForChange(ent, userId, cd_empresa))
                        if(!ent.OriginalStatus.Equals(System.Data.Entity.EntityState.Modified))
                            LogGeralDifModified.Add(x);
                this.LogGeral.AddRange(LogGeralDifModified);
                // Call the original SaveChanges(), which will save both the changes made and the audit records
                retorno += base.SaveChanges();
             //   transaction.Complete();
            
                return retorno;
            //}
        }
    
    	public List<LogGeral> GetAuditRecordsForChange(DbEntityEntryComp dbEntryComp, int userId, int cd_empresa) {
            DbEntityEntry dbEntry = dbEntryComp.DbEntityEntry;
            List<LogGeral> result = new List<LogGeral>();
            DateTime changeTime = DateTime.UtcNow;
        
            // Get the Table() attribute, if one exists
            TableAttribute tableAttr = dbEntry.Entity.GetType().GetCustomAttributes(typeof(TableAttribute), false).SingleOrDefault() as TableAttribute;
            // Get table name (if it has a Table attribute, use that, otherwise get the pluralized name)
            string tableName = tableAttr != null ? tableAttr.Name : dbEntry.Entity.GetType().Name;
        
            byte? origem = (byte?) LISTA_ORIGEM_LOGS[tableName];
        
        
        	// Get primary key value (If you have more than one key column, this will need to be adjusted)
            string keyName = "";
            PropertyInfo property = dbEntry.Entity.GetType().GetProperties().SingleOrDefault(p => p.GetCustomAttributes(typeof(KeyAttribute), true).Count() > 0);
            
            if(property != null)
        		keyName = property.Name;
        			
        	int? cd_registro_pai = null;
            try {
                cd_registro_pai = Int32.Parse(dbEntry.CurrentValues.GetValue<object>(keyName).ToString());
            }
            catch(Exception e) { }
                            
            if(origem.HasValue) {
                LogGeral logGeral = null;
                if(dbEntryComp.OriginalStatus == System.Data.Entity.EntityState.Added) {
                    // For Inserts, just add the whole record
                    // If the entity implements IDescribableEntity, use the description from Describe(), otherwise use ToString()
                    logGeral = new LogGeral() {
                        cd_usuario = userId,
                        dt_log_geral = changeTime,
                        cd_tipo_log = (int) FundacaoFisk.SGF.GenericModel.TipoLog.TipoLogEnum.INCLUSAO,
                        cd_origem = origem.Value,
        				cd_registro_pai = cd_registro_pai,
        				cd_pessoa_empresa = cd_empresa
        
                        /*RecordID = dbEntry.CurrentValues.GetValue<object>(keyName).ToString(),  // Again, adjust this if you have a multi-column key
                        NewValue = (dbEntry.CurrentValues.ToObject() is IDescribableEntity) ? (dbEntry.CurrentValues.ToObject() as IDescribableEntity).Describe() : dbEntry.CurrentValues.ToObject().ToString()
                        */    
                    };
        
                    // Gera o log de cada campo (coluna) incluida:
                   /* ICollection<LogGeralDetalhe> detalhesLog = new List<LogGeralDetalhe>();
                    foreach(string propertyName in dbEntry.CurrentValues.PropertyNames) {
                        // For updates, we only want to capture the columns that actually changed
                        LogGeralDetalhe logGeralDetalhe = new LogGeralDetalhe();
                        //var objAntigo = dbEntry.OriginalValues.ToObject();
                        var objNovo = dbEntry.CurrentValues.GetValue<object>(propertyName);
        
                        logGeralDetalhe.no_coluna = propertyName;
                        //logGeralDetalhe.dc_valor_antigo = (objAntigo is IDescribableEntity) ? (objAntigo as IDescribableEntity).Describe() : objAntigo.ToString();
                        if(objNovo != null) {
                            logGeralDetalhe.dc_valor_novo = objNovo.ToString();
                            detalhesLog.Add(logGeralDetalhe);
                        }
                    }
                    logGeral.DetalhesLogGeral = detalhesLog;*/
                }
                else if(dbEntryComp.OriginalStatus == System.Data.Entity.EntityState.Deleted) {
                    // Same with deletes, do the whole record, and use either the description from Describe() or ToString()
                    logGeral = new LogGeral() {
                        cd_usuario = userId,
                        dt_log_geral = changeTime,
                        cd_tipo_log = (int) FundacaoFisk.SGF.GenericModel.TipoLog.TipoLogEnum.DELECAO,
                        cd_origem = origem.Value,
        				cd_registro_pai = cd_registro_pai,
        				cd_pessoa_empresa = cd_empresa
        
                        /*RecordID = dbEntry.OriginalValues.GetValue<object>(keyName).ToString()
                        NewValue = (dbEntry.OriginalValues.ToObject() is IDescribableEntity) ? (dbEntry.OriginalValues.ToObject() as IDescribableEntity).Describe() : dbEntry.OriginalValues.ToObject().ToString()
                        */    
                    };
        
                    // Gera o log de cada campo (coluna) deletada:
                    //LBM Em 17/05/2022 incluindo log geral e excluindo logs detalhes
                    /*ICollection<LogGeralDetalhe> detalhesLog = new List<LogGeralDetalhe>();
                    foreach(string propertyName in dbEntry.OriginalValues.PropertyNames) {
                        // For updates, we only want to capture the columns that actually changed
                        LogGeralDetalhe logGeralDetalhe = new LogGeralDetalhe();
                        //var objAntigo = dbEntry.OriginalValues.ToObject();
                        var objAntigo = dbEntry.OriginalValues.GetValue<object>(propertyName);
        
                        logGeralDetalhe.no_coluna = propertyName;
                        //logGeralDetalhe.dc_valor_antigo = (objAntigo is IDescribableEntity) ? (objAntigo as IDescribableEntity).Describe() : objAntigo.ToString();
                        if(objAntigo != null) {
                            logGeralDetalhe.dc_valor_antigo = objAntigo.ToString();
                            detalhesLog.Add(logGeralDetalhe);
                        }
                    }
                    logGeral.DetalhesLogGeral = detalhesLog;*/
                }
                else if(dbEntryComp.OriginalStatus == System.Data.Entity.EntityState.Modified) {
                    // Gera o log de alteração da entidade:
                    logGeral = new LogGeral() {
                        cd_usuario = userId,
                        dt_log_geral = changeTime,
                        cd_tipo_log = (int) FundacaoFisk.SGF.GenericModel.TipoLog.TipoLogEnum.ALTERACAO,
                        cd_origem = origem.Value,
        				cd_registro_pai = cd_registro_pai,
        				cd_pessoa_empresa = cd_empresa
        
                        /*RecordID = dbEntry.OriginalValues.GetValue<object>(keyName).ToString()*/
                    };
        
                    // Gera o log de cada campo (coluna) alerada:
                    //LBM Em 17/05/2022 incluindo log geral e excluindo logs detalhes
                    /*ICollection<LogGeralDetalhe> detalhesLog = new List<LogGeralDetalhe>();
                    IEnumerable<string> propertysModified = dbEntry.OriginalValues.PropertyNames.Where(x => !object.Equals(dbEntry.OriginalValues.GetValue<object>(x), dbEntry.CurrentValues.GetValue<object>(x))).ToList();
                    foreach (string propertyName in propertysModified){
                        // For updates, we only want to capture the columns that actually changed
                        LogGeralDetalhe logGeralDetalhe = new LogGeralDetalhe();
                        var objNovo = dbEntry.CurrentValues.GetValue<object>(propertyName);
                        var objAntigo = dbEntry.OriginalValues.GetValue<object>(propertyName);
        
                        logGeralDetalhe.no_coluna = propertyName;
                        logGeralDetalhe.dc_valor_novo = objNovo != null ? objNovo.ToString() : null;
                        logGeralDetalhe.dc_valor_antigo = objAntigo != null ? objAntigo.ToString() : null;
                        detalhesLog.Add(logGeralDetalhe);
                    }
                    logGeral.DetalhesLogGeral = detalhesLog;*/
                }
                if(logGeral != null)
                    result.Add(logGeral);
            }
            // Otherwise, don't do anything, we don't care about Unchanged or Detached entities
        
            return result;
        }
    }
}
