//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class SysApp : TO
    {
         [CommonEntityProperty()]
        public string dc_msg { get; set; }
    
         [CommonEntityProperty()]
        public string no_exe { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_script { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_versao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_ambiente_producao { get; set; }
    
         [CommonEntityProperty()]
        public string tx_msg_email { get; set; }
    
         [Key()]
         public int cd_sys_app { get; set; }
    
         [CommonEntityProperty()]
        public string tx_verso_cartao_postal { get; set; }
    
         [CommonEntityProperty()]
        public string dc_path_xml { get; set; }
    
         [CommonEntityProperty()]
        public string dc_path_xml_processadas { get; set; }
    
         [CommonEntityProperty()]
        public string dc_path_xml_inconsistentes { get; set; }
    
         [CommonEntityProperty()]
        public string dc_path_xml_NFsEstoque { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_acerto_estoque { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> f_config_1 { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> f_config_2 { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_acerto_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_notificacoes { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_advertencias { get; set; }
    
    }
}
