//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class SysDireitoGrupo : TO
    {
         [CommonEntityProperty()]
        public int cd_grupo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_menu { get; set; }
    
         [CommonEntityProperty()]
        public bool id_alterar_grupo { get; set; }
    
         [CommonEntityProperty()]
        public bool id_excluir_grupo { get; set; }
    
         [CommonEntityProperty()]
        public bool id_inserir_grupo { get; set; }
    
         [Key()]
         public int cd_direito_grupo { get; set; }
    
    
        public virtual SysGrupo SysGrupo { get; set; }
        public virtual SysMenu SysMenu { get; set; }
    }
}
