//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class SysDireitoUsuario : TO
    {
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [CommonEntityProperty()]
        public int cd_menu { get; set; }
    
         [CommonEntityProperty()]
        public bool id_alterar { get; set; }
    
         [CommonEntityProperty()]
        public bool id_deletar { get; set; }
    
         [CommonEntityProperty()]
        public bool id_inserir { get; set; }
    
         [Key()]
         public int cd_direito_usuario { get; set; }
    
    
        public virtual UsuarioWebSGF Usuario { get; set; }
        public virtual SysMenu Menu { get; set; }
    }
}
