//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class SysGrupoUsuario : TO
    {
         [CommonEntityProperty()]
        public int cd_grupo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_usuario { get; set; }
    
         [Key()]
         public int cd_grupo_usuario { get; set; }
    
    
        public virtual SysGrupo Grupo { get; set; }
        public virtual UsuarioWebSGF UsuarioWeb { get; set; }
    }
}
