//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenu : TO
    {
        public SysMenu()
        {
            this.SysDireitosGrupos = new HashSet<SysDireitoGrupo>();
            this.Direitos = new HashSet<SysDireitoUsuario>();
            this.MenusFilhos = new HashSet<SysMenu>();
        }
    
         [Key()]
         public int cd_menu { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_menu_pai { get; set; }
    
         [CommonEntityProperty()]
        public string no_menu { get; set; }
    
         [CommonEntityProperty()]
        public string dc_url_menu { get; set; }
    
         [CommonEntityProperty()]
        public int nm_ordem { get; set; }
    
         [CommonEntityProperty()]
        public bool id_menu_visivel { get; set; }
    
         [CommonEntityProperty()]
        public string dc_menu { get; set; }
    
         [CommonEntityProperty()]
        public bool id_permissao_visivel { get; set; }
    
         [CommonEntityProperty()]
        public bool id_separador { get; set; }
    
         [CommonEntityProperty()]
        public bool id_dashboard { get; set; }
    
         [CommonEntityProperty()]
        public string icone { get; set; }
    
    
        public virtual ICollection<SysDireitoGrupo> SysDireitosGrupos { get; set; }
        public virtual ICollection<SysDireitoUsuario> Direitos { get; set; }
        public virtual ICollection<SysMenu> MenusFilhos { get; set; }
        public virtual SysMenu SysMenuPai { get; set; }
    }
}
