//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class T_DESCONTO : TO
    {
         [Key()]
         public int cd_desconto { get; set; }
    
         [CommonEntityProperty()]
        public string dc_desconto { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public bool id_desconto_ativo { get; set; }
    
         [CommonEntityProperty()]
        public decimal pc_desconto { get; set; }
    
    
        public virtual Escola T_EMPRESA { get; set; }
    }
}
