//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TaxaMatricula : TO
    {
         [Key()]
         public int cd_taxa_matricula { get; set; }
    
         [CommonEntityProperty()]
        public int cd_contrato { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_matricula_taxa { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_vcto_taxa { get; set; }
    
         [CommonEntityProperty()]
        public int nm_parcelas_taxa { get; set; }
    
         [CommonEntityProperty()]
        public decimal pc_responsavel_taxa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_responsavel_taxa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_financeiro_taxa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_taxa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_parcela_taxa { get; set; }
    
    
        public virtual Contrato Contrato { get; set; }
        public virtual PessoaSGF Pessoa { get; set; }
        public virtual PlanoConta PlanoConta { get; set; }
        public virtual TipoFinanceiro TipoFinanceiro { get; set; }
    }
}
