//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TaxaBancaria : TO
    {
         [Key()]
         public int cd_taxa_bancaria { get; set; }
    
         [CommonEntityProperty()]
        public int cd_local_movto { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_parcela { get; set; }
    
         [CommonEntityProperty()]
        public double pc_taxa { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_dias { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dh_taxa_bancaria { get; set; }
    
    
        public virtual LocalMovto T_LOCAL_MOVTO { get; set; }
    }
}
