//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TelefoneSGF : TO
    {
        public TelefoneSGF()
        {
            this.TelefonePessoa = new HashSet<PessoaSGF>();
        }
    
         [Key()]
         public int cd_telefone { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_telefone { get; set; }
    
         [CommonEntityProperty()]
        public int cd_classe_telefone { get; set; }
    
         [CommonEntityProperty()]
        public string dc_fone_mail { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_endereco { get; set; }
    
         [CommonEntityProperty()]
        public bool id_telefone_principal { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_operadora { get; set; }
    
    
        public virtual ClasseTelefoneSGF ClasseTelefone { get; set; }
        public virtual ICollection<PessoaSGF> TelefonePessoa { get; set; }
        public virtual PessoaSGF PessoaTelefone { get; set; }
        public virtual TipoTelefoneSGF TelefoneTipo { get; set; }
        public virtual EnderecoSGF Endereco { get; set; }
        public virtual Operadora Operadora { get; set; }
    }
}
