//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoContato : TO
    {
         [Key()]
         public int cd_tipo_contato { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tipo_contato { get; set; }
    
         [CommonEntityProperty()]
        public bool id_tipo_contato_ativo { get; set; }
    
    }
}
