//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAtividadeExtra : TO
    {
        public TipoAtividadeExtra()
        {
            this.AtividadeExtraTipo = new HashSet<AtividadeExtra>();
            this.DiarioAula = new HashSet<DiarioAula>();
        }
    
         [Key()]
         public int cd_tipo_atividade_extra { get; set; }
    
         [CommonEntityProperty()]
        public string no_tipo_atividade_extra { get; set; }
    
         [CommonEntityProperty()]
        public bool id_tipo_atividade_extra_ativa { get; set; }
    
    
        public virtual ICollection<AtividadeExtra> AtividadeExtraTipo { get; set; }
        public virtual ICollection<DiarioAula> DiarioAula { get; set; }
    }
}
