//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAvaliacao : TO
    {
        public TipoAvaliacao()
        {
            this.Avaliacao = new HashSet<Avaliacao>();
            this.AvaliacaoCurso = new HashSet<AvaliacaoCurso>();
            this.MensagemAvaliacaoAluno = new HashSet<MensagemAvaliacaoAluno>();
        }
    
         [Key()]
         public int cd_tipo_avaliacao { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tipo_avaliacao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> vl_total_nota { get; set; }
    
         [CommonEntityProperty()]
        public bool id_tipo_ativo { get; set; }
    
    
        public virtual ICollection<Avaliacao> Avaliacao { get; set; }
        public virtual ICollection<AvaliacaoCurso> AvaliacaoCurso { get; set; }
        public virtual ICollection<MensagemAvaliacaoAluno> MensagemAvaliacaoAluno { get; set; }
    }
}
