//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEnderecoSGF : TO
    {
        public TipoEnderecoSGF()
        {
            this.Enderecos = new HashSet<EnderecoSGF>();
        }
    
         [Key()]
         public int cd_tipo_endereco { get; set; }
    
         [CommonEntityProperty()]
        public string no_tipo_endereco { get; set; }
    
    
        public virtual ICollection<EnderecoSGF> Enderecos { get; set; }
    }
}
