//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoLiquidacao : TO
    {
        public TipoLiquidacao()
        {
            this.BaixoTitulo = new HashSet<BaixaTitulo>();
            this.TransacoesFinanceiras = new HashSet<TransacaoFinanceira>();
            this.ContasCorrentes = new HashSet<ContaCorrente>();
            this.Prospect = new HashSet<Prospect>();
        }
    
         [Key()]
         public int cd_tipo_liquidacao { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tipo_liquidacao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_tipo_liquidacao_ativa { get; set; }
    
    
        public virtual ICollection<BaixaTitulo> BaixoTitulo { get; set; }
        public virtual ICollection<TransacaoFinanceira> TransacoesFinanceiras { get; set; }
        public virtual ICollection<ContaCorrente> ContasCorrentes { get; set; }
        public virtual ICollection<Prospect> Prospect { get; set; }
    }
}
