//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoFinanceiro : TO
    {
        public TipoFinanceiro()
        {
            this.Contrato = new HashSet<Contrato>();
            this.TaxaMatricula = new HashSet<TaxaMatricula>();
            this.Titulo = new HashSet<Titulo>();
            this.Movimentos = new HashSet<Movimento>();
            this.Aditamento = new HashSet<Aditamento>();
            this.CursoContrato = new HashSet<CursoContrato>();
        }
    
         [Key()]
         public int cd_tipo_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tipo_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public bool id_tipo_financeiro_ativo { get; set; }
    
    
        public virtual ICollection<Contrato> Contrato { get; set; }
        public virtual ICollection<TaxaMatricula> TaxaMatricula { get; set; }
        public virtual ICollection<Titulo> Titulo { get; set; }
        public virtual ICollection<Movimento> Movimentos { get; set; }
        public virtual ICollection<Aditamento> Aditamento { get; set; }
        public virtual ICollection<CursoContrato> CursoContrato { get; set; }
    }
}
