//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoItem : TO
    {
        public TipoItem()
        {
            this.Item = new HashSet<Item>();
        }
    
         [Key()]
         public int cd_tipo_item { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tipo_item { get; set; }
    
         [CommonEntityProperty()]
        public bool id_tipo_item_ativo { get; set; }
    
         [CommonEntityProperty()]
        public bool id_movimentar_estoque { get; set; }
    
    
        public virtual ICollection<Item> Item { get; set; }
    }
}
