//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TituloCnab : TO
    {
        public TituloCnab()
        {
            this.DescontoTituloCNAB = new HashSet<DescontoTituloCNAB>();
        }
    
         [Key()]
         public int cd_titulo_cnab { get; set; }
    
         [CommonEntityProperty()]
        public int cd_cnab { get; set; }
    
         [CommonEntityProperty()]
        public int cd_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_local_movto_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_turma_titulo { get; set; }
    
         [CommonEntityProperty()]
        public byte id_status_cnab_titulo { get; set; }
    
         [CommonEntityProperty()]
        public string dc_nosso_numero_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> pc_juros_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> pc_multa_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_vencimento_titulo { get; set; }
    
         [CommonEntityProperty()]
        public string tx_mensagem_cnab { get; set; }
    
    
        public virtual Cnab Cnab { get; set; }
        public virtual LocalMovto LocalMovimento { get; set; }
        public virtual Titulo Titulo { get; set; }
        public virtual Turma Turma { get; set; }
        public virtual ICollection<DescontoTituloCNAB> DescontoTituloCNAB { get; set; }
    }
}
