//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Titulo : TO
    {
        public Titulo()
        {
            this.BaixaTitulo = new HashSet<BaixaTitulo>();
            this.PlanoTitulo = new HashSet<PlanoTitulo>();
            this.TitulosCnab = new HashSet<TituloCnab>();
            this.TituloRetornoCNAB = new HashSet<TituloRetornoCNAB>();
            this.ReajustesTitulos = new HashSet<ReajusteTitulo>();
            this.T_TITULO_ADITAMENTO = new HashSet<TituloAditamento>();
        }
    
         [Key()]
         public int cd_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_responsavel { get; set; }
    
         [CommonEntityProperty()]
        public int cd_local_movto { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_emissao_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_origem_titulo { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_vcto_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dh_cadastro_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_liquidacao_titulo { get; set; }
    
         [CommonEntityProperty()]
        public string dc_codigo_barra { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tipo_titulo { get; set; }
    
         [CommonEntityProperty()]
        public string dc_nosso_numero { get; set; }
    
         [CommonEntityProperty()]
        public string dc_num_documento_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_saldo_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_parcela_titulo { get; set; }
    
         [CommonEntityProperty()]
        public int cd_tipo_financeiro { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> id_status_titulo { get; set; }
    
         [CommonEntityProperty()]
        public byte id_status_cnab { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> id_origem_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_natureza_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_multa_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_juros_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_liquidacao_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_multa_liquidada { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_juros_liquidado { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_juros { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_multa { get; set; }
    
         [CommonEntityProperty()]
        public double pc_juros_titulo { get; set; }
    
         [CommonEntityProperty()]
        public double pc_multa_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_plano_conta_tit { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_material_titulo { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_abatimento { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_contrato { get; set; }
    
         [CommonEntityProperty()]
        public double pc_taxa_cartao { get; set; }
    
         [CommonEntityProperty()]
        public byte nm_dias_cartao { get; set; }
    
         [CommonEntityProperty()]
        public bool id_cnab_contrato { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_taxa_cartao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_responsavel { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_mensalidade { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_bolsa { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_desconto_mensalidade { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_desconto_mensalidade { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_bolsa_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_bolsa_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_desconto_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_desconto_material { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> pc_desconto_total { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> vl_desconto_total { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> opcao_venda { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_curso { get; set; }
    
    
        public virtual Escola Empresa { get; set; }
        public virtual PessoaSGF Pessoa { get; set; }
        public virtual PessoaSGF PessoaResponsavel { get; set; }
        public virtual TipoFinanceiro TipoFinanceiro { get; set; }
        public virtual ICollection<BaixaTitulo> BaixaTitulo { get; set; }
        public virtual LocalMovto LocalMovto { get; set; }
        public virtual PlanoConta PlanoConta { get; set; }
        public virtual ICollection<PlanoTitulo> PlanoTitulo { get; set; }
        public virtual Origem Origem { get; set; }
        public virtual ICollection<TituloCnab> TitulosCnab { get; set; }
        public virtual ICollection<TituloRetornoCNAB> TituloRetornoCNAB { get; set; }
        public virtual ICollection<ReajusteTitulo> ReajustesTitulos { get; set; }
        public virtual ICollection<TituloAditamento> T_TITULO_ADITAMENTO { get; set; }
    }
}
