//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TituloRetornoCNAB : TO
    {
        public TituloRetornoCNAB()
        {
            this.DespesaTituloCnab = new HashSet<DespesaTituloCnab>();
        }
    
         [Key()]
         public int cd_titulo_retorno_cnab { get; set; }
    
         [CommonEntityProperty()]
        public int cd_retorno_cnab { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_titulo { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_baixa_retorno { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_banco_retorno { get; set; }
    
         [CommonEntityProperty()]
        public byte id_tipo_retorno { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_baixa_retorno { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_juros_retorno { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_multa_retorno { get; set; }
    
         [CommonEntityProperty()]
        public decimal vl_desconto_titulo { get; set; }
    
         [CommonEntityProperty()]
        public string tx_mensagem_retorno { get; set; }
    
         [CommonEntityProperty()]
        public string dc_nosso_numero { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_tran_finan { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> id_status_cnab_retorno { get; set; }
    
    
        public virtual RetornoCNAB RetornoCNAB { get; set; }
        public virtual Titulo Titulo { get; set; }
        public virtual TransacaoFinanceira TransacaoFinanceira { get; set; }
        public virtual ICollection<DespesaTituloCnab> DespesaTituloCnab { get; set; }
    }
}
