//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TransferenciaAluno : TO
    {
         [Key()]
         public int cd_transferencia_aluno { get; set; }
    
         [CommonEntityProperty()]
        public int cd_escola_origem { get; set; }
    
         [CommonEntityProperty()]
        public int cd_escola_destino { get; set; }
    
         [CommonEntityProperty()]
        public int cd_aluno_origem { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_aluno_destino { get; set; }
    
         [CommonEntityProperty()]
        public int cd_motivo_transferencia { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_cadastro_transferencia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_solicitacao_transferencia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_confirmacao_transferencia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_transferencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_email_origem { get; set; }
    
         [CommonEntityProperty()]
        public string dc_email_destino { get; set; }
    
         [CommonEntityProperty()]
        public byte id_status_transferencia { get; set; }
    
         [CommonEntityProperty()]
        public bool id_email_origem { get; set; }
    
         [CommonEntityProperty()]
        public bool id_email_destino { get; set; }
    
         [CommonEntityProperty()]
        public string no_arquivo_historico { get; set; }
    
         [CommonEntityProperty()]
        public string pdf_historico { get; set; }
    
    
        public virtual Aluno AlunoDestino { get; set; }
        public virtual Aluno AlunoOrigem { get; set; }
        public virtual Escola EscolaDestino { get; set; }
        public virtual Escola EscolaOrigem { get; set; }
        public virtual MotivoTransferenciaAluno T_MOTIVO_TRANSFERENCIA_ALUNO { get; set; }
    }
}
