//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class TratamentoPessoa : TO
    {
        public TratamentoPessoa()
        {
            this.PessoaFisica = new HashSet<PessoaFisicaSGF>();
        }
    
         [Key()]
         public int cd_tratamento { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tratamento_masc { get; set; }
    
         [CommonEntityProperty()]
        public string dc_tratamento_fem { get; set; }
    
    
        public virtual ICollection<PessoaFisicaSGF> PessoaFisica { get; set; }
    }
}
