//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Turma : TO
    {
        public Turma()
        {
            this.TurmaFilhasPPT = new HashSet<Turma>();
            this.AvaliacaoTurma = new HashSet<AvaliacaoTurma>();
            this.TurmaProfessorTurma = new HashSet<ProfessorTurma>();
            this.TurmaAluno = new HashSet<AlunoTurma>();
            this.ProgramacaoTurma = new HashSet<ProgramacaoTurma>();
            this.FeriadosDesconsiderados = new HashSet<FeriadoDesconsiderado>();
            this.DiarioAula = new HashSet<DiarioAula>();
            this.HistoricoAluno = new HashSet<HistoricoAluno>();
            this.AlunoTurmaOrigem = new HashSet<AlunoTurma>();
            this.PoliticasTurmas = new HashSet<PoliticaTurma>();
            this.TitulosCnab = new HashSet<TituloCnab>();
            this.TurmaEncerramento = new HashSet<Turma>();
            this.AulaPersonalizada = new HashSet<AulaPersonalizada>();
            this.ReajustesTitulos = new HashSet<ReajusteTitulo>();
            this.ReajustesTurmas = new HashSet<ReajusteTurma>();
            this.T_CONTROLE_FALTAS = new HashSet<ControleFaltas>();
            this.AulaReposicao = new HashSet<AulaReposicao>();
            this.TurmaEscola = new HashSet<TurmaEscola>();
            this.FollowUp = new HashSet<FollowUp>();
            this.AulaReposicaoDest = new HashSet<AulaReposicao>();
        }
    
         [Key()]
         public int cd_turma { get; set; }
    
         [CommonEntityProperty()]
        public string no_turma { get; set; }
    
         [CommonEntityProperty()]
        public int cd_pessoa_escola { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_turma_ppt { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_curso { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_sala { get; set; }
    
         [CommonEntityProperty()]
        public int cd_duracao { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_regime { get; set; }
    
         [CommonEntityProperty()]
        public System.DateTime dt_inicio_aula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_final_aula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<bool> id_aula_externa { get; set; }
    
         [CommonEntityProperty()]
        public short nro_aulas_programadas { get; set; }
    
         [CommonEntityProperty()]
        public bool id_turma_ppt { get; set; }
    
         [CommonEntityProperty()]
        public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public bool id_turma_ativa { get; set; }
    
         [CommonEntityProperty()]
        public int nm_turma { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_termino_turma { get; set; }
    
         [CommonEntityProperty()]
        public string no_apelido { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_turma_enc { get; set; }
    
         [CommonEntityProperty()]
        public bool id_percentual_faltas { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_sala_online { get; set; }
    
    
        public virtual Escola EscolaTurma { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Duracao Duracao { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Regime Regime { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual ICollection<Turma> TurmaFilhasPPT { get; set; }
        public virtual Turma TurmaPai { get; set; }
        public virtual ICollection<AvaliacaoTurma> AvaliacaoTurma { get; set; }
        public virtual ICollection<ProfessorTurma> TurmaProfessorTurma { get; set; }
        public virtual ICollection<AlunoTurma> TurmaAluno { get; set; }
        public virtual ICollection<ProgramacaoTurma> ProgramacaoTurma { get; set; }
        public virtual ICollection<FeriadoDesconsiderado> FeriadosDesconsiderados { get; set; }
        public virtual ICollection<DiarioAula> DiarioAula { get; set; }
        public virtual ICollection<HistoricoAluno> HistoricoAluno { get; set; }
        public virtual ICollection<AlunoTurma> AlunoTurmaOrigem { get; set; }
        public virtual ICollection<PoliticaTurma> PoliticasTurmas { get; set; }
        public virtual ICollection<TituloCnab> TitulosCnab { get; set; }
        public virtual ICollection<Turma> TurmaEncerramento { get; set; }
        public virtual Turma TurmaOriEncerramento { get; set; }
        public virtual ICollection<AulaPersonalizada> AulaPersonalizada { get; set; }
        public virtual ICollection<ReajusteTitulo> ReajustesTitulos { get; set; }
        public virtual ICollection<ReajusteTurma> ReajustesTurmas { get; set; }
        public virtual ICollection<ControleFaltas> T_CONTROLE_FALTAS { get; set; }
        public virtual ICollection<AulaReposicao> AulaReposicao { get; set; }
        public virtual Sala T_SALA { get; set; }
        public virtual ICollection<TurmaEscola> TurmaEscola { get; set; }
        public virtual ICollection<FollowUp> FollowUp { get; set; }
        public virtual ICollection<AulaReposicao> AulaReposicaoDest { get; set; }
    }
}
