//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class vi_carga_horaria : TO
    {
         [Key()]
         public string nm_raf { get; set; }
    
         [Key()]
         public int cd_escola { get; set; }
    
         [Key()]
         public int cd_pessoa_aluno { get; set; }
    
         [Key()]
         public int cd_escola_aluno { get; set; }
    
         [Key()]
         public int cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_curso { get; set; }
    
         [Key()]
         public string no_curso { get; set; }
    
         [Key()]
         public int nm_carga_maxima { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> nm_carga { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_ultima_aula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> qt_ano { get; set; }
    
         [Key()]
         public string no_aluno { get; set; }
    
         [Key()]
         public int cd_turma { get; set; }
    
         [Key()]
         public int qt_voucher { get; set; }
    
         [CommonEntityProperty()]
        public string no_turma { get; set; }
    
         [Key()]
         public byte id_situacao_historico { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_termino_turma { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_turma_ppt { get; set; }
    
         [Key()]
         public byte nm_sequencia { get; set; }
    
         [CommonEntityProperty()]
        public string dc_carga { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_minutos { get; set; }
    
    }
}
