//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class vi_carga_aluno : TO
    {
         [Key()]
         public int cd_aluno { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_curso { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> nm_carga { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> nm_maxima { get; set; }
    
         [Key()]
         public int nm_carga_maxima { get; set; }
    
         [Key()]
         public int qt_voucher { get; set; }
    
    }
}
