//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class vi_curso_ordem : TO
    {
         [Key()]
         public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<byte> nm_ordem_estagio { get; set; }
    
         [Key()]
         public int cd_curso { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<long> cd_curso_ordem { get; set; }
    
    }
}
