//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class vi_desistencia_carga : TO
    {
         [CommonEntityProperty()]
        public string dc_reduzido_pessoa { get; set; }
    
         [Key()]
         public int cd_pessoa_escola { get; set; }
    
         [Key()]
         public int cd_aluno { get; set; }
    
         [Key()]
         public int cd_pessoa_aluno { get; set; }
    
         [Key()]
         public string no_aluno { get; set; }
    
         [Key()]
         public string nm_raf { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_curso { get; set; }
    
         [Key()]
         public string no_curso { get; set; }
    
         [Key()]
         public int cd_turma { get; set; }
    
         [CommonEntityProperty()]
        public string no_turma { get; set; }
    
         [Key()]
         public int cd_desistencia { get; set; }
    
         [Key()]
         public System.DateTime dt_desistencia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> cd_contrato { get; set; }
    
         [CommonEntityProperty()]
        public string tx_obs_desistencia { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<System.DateTime> dt_cadastro { get; set; }
    
    }
}
