//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class vi_diario_aula : TO
    {
         [Key()]
         public int cd_diario_aula { get; set; }
    
         [Key()]
         public int cd_pessoa_empresa { get; set; }
    
         [CommonEntityProperty()]
        public string nom_professor { get; set; }
    
         [Key()]
         public int cd_tipo_aula { get; set; }
    
         [CommonEntityProperty()]
        public string nom_susbtituto { get; set; }
    
         [Key()]
         public System.DateTime dt_aula { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> id_status_aula { get; set; }
    
         [Key()]
         public byte id_falta_professor { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> nm_aula_turma { get; set; }
    
         [CommonEntityProperty()]
        public string no_turma { get; set; }
    
         [Key()]
         public string no_tipo_atividade_extra { get; set; }
    
         [Key()]
         public int cd_turma { get; set; }
    
         [Key()]
         public string dc_eventos { get; set; }
    
    }
}
