//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    using Componentes.GenericModel;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class vi_qt_programacao_curso : TO
    {
         [Key()]
         public int cd_programacao_curso { get; set; }
    
         [Key()]
         public string no_curso { get; set; }
    
         [Key()]
         public int cd_duracao { get; set; }
    
         [Key()]
         public string dc_duracao { get; set; }
    
         [Key()]
         public decimal nm_duracao { get; set; }
    
         [Key()]
         public int cd_produto { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<short> nm_carga_horaria { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<int> qtd_aulas { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<decimal> qt_horas { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> qt_aulas_sem { get; set; }
    
         [CommonEntityProperty()]
        public Nullable<double> qt_aulas_semana { get; set; }
    
         [Key()]
         public int cd_curso { get; set; }
    
    }
}
