//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.Web.Services.Secretaria.Model
{
    using System;
    using System.Collections.Generic;
    using Componentes.GenericModel;
    using FundacaoFisk.SGF.GenericModel;

    public partial class RptBolsistas : TO
    {
        public int cd_aluno { get; set; }
        public string no_aluno { get; set; }
        public Nullable<decimal> pc_bolsa { get; set; }
        public System.DateTime dt_inicio_bolsa { get; set; }
        public string dc_validade_bolsa { get; set; }
        public Nullable<decimal> pc_bolsa_material { get; set; }
        public Nullable<System.DateTime> dt_comunicado_bolsa { get; set; }
        public Nullable<System.DateTime> dt_cancelamento_bolsa { get; set; }
        public Nullable<int> cd_motivo_bolsa { get; set; }
        public string dc_motivo_bolsa { get; set; }
        public Nullable<int> cd_motivo_cancelamento_bolsa { get; set; }
        public string dc_motivo_cancelamento_bolsa { get; set; }
        public int? cd_turma { get; set; }
        public string no_turma { get; set; }
        public System.DateTime? dt_ini_turma { get; set; }
        public int nr_faltas { get; set; }
        public int? nm_nf { get; set; }
        public decimal vl_parcela { get; set; }
        public Nullable<double> nm_nota_aluno1 { get; set; }
        public Nullable<double> nm_nota_aluno2 { get; set; }
        public Nullable<double> nm_nota_aluno3 { get; set; }
        public string dc_tipo_avaliacao1 { get; set; }
        public string dc_tipo_avaliacao2 { get; set; }
        public string dc_tipo_avaliacao3 { get; set; }
        public int? nr_faltas_justificadas { get; set; }
        public System.DateTime? dt_transferencia { get; set; }
        public string tx_obs_transferencia { get; set; }
        public string no_produto { get; set; }
        public String dt_inicio
        {
            get
            {
                if (this.dt_ini_turma.HasValue)
                    return String.Format("{0:dd/MM/yyyy}", dt_ini_turma);
                else
                    return "";
            }
        }
    }
}
