//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.Web.Services.Financeiro.Model
{
    using System;
    using Componentes.GenericModel;
    
    public partial class RptBalanceteMensal : TO
    {
        public int cd_result { get; set; }
        public string Conta { get; set; }
        public int Ano { get; set; }
        public int Mes { get; set; }
        public decimal Anterior { get; set; }
        public decimal Debito { get; set; }
        public decimal Credito { get; set; }
        public decimal Saldo { get; set; }
        public int Empresa { get; set; }
        public int Tipo { get; set; }
        public int Nivel { get; set; }
        public int Grupo { get; set; }
        public int Subgrupo { get; set; }
    }
}
