//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.Web.Services.Financeiro.Model
{
    using System;
    using Componentes.GenericModel;

    public partial class RptPlanoTitulo : TO
    {
        public string no_subgrupo_conta { get; set; }
        public Nullable<decimal> vl_plano_titulo { get; set; }
    }
}
