//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.Web.Services.Financeiro.Model
{
    using System;
    using System.Collections.Generic;
    using Componentes.GenericModel;
    using FundacaoFisk.SGF.GenericModel;

    public partial class RptRecebidaPaga : TO
    {
        public Nullable<int> cd_pessoa_empresa { get; set; }
        public Nullable<int> cd_baixa_titulo { get; set; }
        public int cd_conta_corrente { get; set; }
        public string nm_escola { get; set; }
        public int cd_pessoa { get; set; }
        public string no_pessoa { get; set; }
        public int cd_responsavel { get; set; }
        public string nm_responsavel { get; set; }
        public Nullable<int> nm_titulo { get; set; }
        public Nullable<byte> nm_parcela_titulo { get; set; }
        public string dc_tipo_financeiro { get; set; }
        public int cd_subgrupo_conta { get; set; }
        public string no_subgrupo_conta { get; set; }
        public string dc_origem { get; set; }
        public decimal? vl_titulo { get; set; }
        public decimal vl_saldo_titulo { get; set; }
        public Nullable<double> pc_taxa_cartao { get; set; }
        public decimal nm_dias_cartao { get; set; }
        public Nullable<System.DateTime> dt_emissao_titulo { get; set; }
        public Nullable<System.DateTime> dt_vcto_titulo { get; set; }
        public Nullable<System.DateTime> dt_baixa_titulo { get; set; }
        public Nullable<decimal> vl_plano_titulo { get; set; }
        public string no_turma { get; set; }
        public string no_local { get; set; }
        public int cd_turma { get; set; }
        public string no_usuario_baixa { get; set; }
        public string tx_obs_baixa { get; set; }

        public Nullable<int> nm_qtd_dias_atraso {
            get {
                Nullable<int> dif = 0;

                if(this.dt_vcto_titulo.HasValue && this.dt_baixa_titulo.HasValue) 
                    dif = this.dt_vcto_titulo.Value.Subtract(this.dt_baixa_titulo.Value).Days;
                else
                    dif = null;
                return dif;
            }
        }

        public string cpf_responsavel { get; set; }

        public decimal? vl_principal_baixa { get; set; }
        public decimal vl_juros_baixa { get; set; }
        public decimal vl_multa_baixa { get; set; }
        public Nullable<decimal> vl_acr_baixa { get { return this.vl_juros_baixa + this.vl_multa_baixa; } }
       // public Nullable<double> vl_juros_do_cartao { get { return ((double)this.pc_taxa_cartao / 100); } }
        public decimal vl_desconto_baixa { get; set; }
        public decimal vl_liquidacao_baixa { get; set; }
        public string dc_tipo_liquidacao { get; set; }
        public int nm_recibo { get; set; }

        public List<TipoLiquidacao> tiposLiquidacao { get; set; }
        public List<TipoFinanceiro> tiposFinanceiro { get; set; }
    }
}
