//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.Web.Services.Financeiro.Model
{
    using System;
    using Componentes.GenericModel;
    
    public partial class RptReceberPagar : TO
    {
        public string nm_escola { get; set; }
        public string dc_tipo_titulo { get; set; }
        public int cd_titulo { get; set; }
        public Nullable<int> cd_pessoa_empresa { get; set; }
        public Nullable<int> nm_titulo { get; set; }
        public Nullable<byte> nm_parcela_titulo { get; set; }
        public Nullable<System.DateTime> dt_emissao_titulo { get; set; }
        public Nullable<System.DateTime> dt_vcto_titulo { get; set; }
        public Nullable<int> id_origem_titulo { get; set; }
        public Nullable<int> cd_origem_titulo { get; set; }
        public int cd_tipo_financeiro { get; set; }
        public string dc_tipo_financeiro { get; set; }
        public int cd_pessoa { get; set; }
        public string no_pessoa { get; set; }
        public Nullable<byte> nm_natureza_aluno { get; set; }
        public string nm_cgc_cpf { get; set; }
        public string nm_rg { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public string nm_telefone_aluno { get; set; }
        public string dc_endereco { get; set; }
        public string no_bairro_aluno { get; set; }
        public string nm_cep_aluno { get; set; }
        public string dc_cidade_uf_aluno { get; set; }
        public int cd_responsavel { get; set; }
        public string nm_responsavel { get; set; }
        public Nullable<byte> nm_natureza_resp { get; set; }
        public string nm_cgc_cpf_resp { get; set; }
        public string nm_rg_resp { get; set; }
        public Nullable<System.DateTime> dt_nascimento_resp { get; set; }
        public string nm_telefone_resp { get; set; }
        public string dc_endereco_resp { get; set; }
        public string no_bairro_resp { get; set; }
        public string nm_cep_resp { get; set; }
        public string dc_cidade_uf_resp { get; set; }
        public decimal vl_saldo_titulo { get; set; }
        public Nullable<decimal> vl_saldo { get; set; }
        public Nullable<double> pc_desc { get; set; }
        public Nullable<double> pc_juros { get; set; }
        public Nullable<double> pc_multa { get; set; }
        public Nullable<double> pc_pont { get; set; }
        public Nullable<decimal> vl_acr { get; set; }
        public Nullable<decimal> vl_desc { get; set; }
        public Nullable<decimal> vl_multa { get; set; }
        public string dc_descontos { get; set; }
        public string nm_telefone_contatos_aluno { get; set; }
        public string nm_telefone_contatos_resp { get; set; }
        public int qtd_subgrupo_conta { get; set; }
        public string no_turma { get; set; }
        public int cd_turma { get; set; }

        //Propriedades para o relatório na ordem de plano de contas:
        public Nullable<decimal> vl_plano_titulo { get; set; }
        public Nullable<int> cd_subgrupo_conta { get; set; }
        public string no_subgrupo_conta { get; set; }
    }
}
