using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Componentes.GenericBusiness;

namespace FundacaoFisk.SGF.Web.Services.Financeiro.Business
{
    public class FinanceiroBusinessException  : BusinessException
    {
         public enum TipoErro {
            ERRO_TITULO_COM_BAIXA = 1,
            ERRO_TITULO_SALDO_NEGATIVO = 2,
            ERRO_ESCOLA_NOT_EXIST_LOCALMOVTO = 3,
            ERRO_SUM_DIFERENTE_POLCOM = 4,
            ERRO_PARC_DIF_OBRIGATORIO = 5,
            ERRO_CONTA_BAIXA_FINAN = 6,
            ERRO_POLITICA_FINAN_DUPLICADA = 8,
            ERRO_ESTOQUE_NEGATIVO = 9,
            ERRO_TITULO_ANTERIOR_ABERTO = 10,
            ERRO_DATA_CONTA_CORRENTE_NULA = 11,
            ERRO_DATA_RETROATIVA_CONTA_CORRENTE = 12,
            ERRO_CATEGORIA_GRUPO_ITEM = 13,
            ERRO_PERMISSAO = 14,
            ERRO_PERMISSAO_PLANO_CONTAS_SEGURA = 15,
            ERRO_EXISTE_FECHAMENTO_BALANCO = 16,
            ERRO_EXISTE_FECHAMENTO = 17,
            ERRO_POLITICA_COMERCIAL_INCONSISTENTE = 18,
            ERRO_DIA_POL_COMERCIAL_NULL = 19,
            ERRO_ALTERAR_PREMATRICULA_BAIXA_MANUAL = 20,
            ERRO_CARTEIRA_USADA_CNAB = 21,
            ERRO_EXCLUIR_TP_DESC_ESCOLA = 22,
            ERRO_EXCLUIR_TP_DESC = 23,
            ERRO_ABERTURA_SALDO = 24,
            ERRO_POLITICA_COM_BAIXA = 25,
            ERRO_SUBGRUPO_ITEM_IGUAIS = 26,
            ERRO_TIPO_SUBGRUPO_ITEM_IGUAIS = 27,
            ERRO_TITULO_ENVIADO_CNAB = 28,
            ERRO_EXISTE_CONTATO_DESCONTO = 29,
            ERRO_EXISTE_CIDADE_DADOS_NF = 30,
            ERRO_TIPO_NF_UTILIZADO = 31,
            ERRO_DADOS_UF_UTILIZADO = 32,
            ERRO_ICMS_ESTADO_UTILIZADO = 33,
            ERRO_EXISTE_TAXA = 34,
            ERRO_NAO_EXISTE_ESTADO_ESC_PESSOA = 35,
            ERRO_NAO_EXISTE_PARAMETROS_TAXA = 36,
            ERRO_NAO_EXISTE_PARAMETROS_MAT = 37,
            ERRO_EXISTE_NF_MAT = 38,
            ERRO_NUMERACAO_AUTOMATICA_NF = 39,
            ERRO_NF_FECHADA_CANCELADA = 40,
            ERRO_NAO_EXISTE_PARAMETROS_BIBLIO = 41,
            ERRO_ORIGEM_TITULO = 42,
            ERRO_NAO_CONFIG_PARAMETRO_NF = 43,
            ERRO_NAO_EXISTE_PLANO_ITEM = 44,
			ERRO_DATA_EMISSAO_TITULO_INFERIOR = 45,
            ERRO_DATA_EMISSAO_TITULO_SUPERIOR = 46,
            ERRO_DATA_VENCIMENTO_TITULO_INFERIOR = 47,
            ERRO_DATA_VENCIMENTO_TITULO_SUPERIOR = 48,
            ERRO_MASTER_SEM_ESCOLA_LOGADA_VINCULADA = 49,
		    ERRO_NIVEL_SUBGRUPO = 50,
            ERRO_MOVTO_TIPO_NF = 51,
			ERRO_PARAMETRO_TIPO_NF = 52,
			ERRO_MINDATE_SMALLDATETIME = 53,
			ERRO_CALCULO_APLICAR_BAIXA_TITULO = 54,
            ERRO_EXISTE_TP_DESCONTO = 55,
            ERRO_EXISTE_TP_DESCONTO_ESC = 56,
            ERRO_TP_DESC_INCLUIDO_MASTER = 57,
            ERRO_TP_DESC_INCLUIDO_USUARIO_COMUM = 58,
            ERRO_TP_DESC_USADO_OUTRAS_ESC = 59,
            ERRO_EXISTE_ITEM_ESC = 60,
            ERRO_EXISTE_ITEM = 61,
            ERRO_ITEM_USADO_OUTRAS_ESC = 62,
            ERRO_ITEM_USADO_PARAMETRO = 63,
            ERRO_ITEM_POSSUI_KARDEX = 64,
            ERRO_BAIXA_BOLSA_CONTRATO = 65,
            ERRO_SALDO_ZERADO = 66,
            ERRO_REAJUSTE_ANUAL_FECHADO = 67,
            ERRO_TITULO_FECHADO_REAJUSTE_ANUAL = 68,
            ERRO_PERMISSAO_FECH_CAIXA_CONSOLIDADO = 69,
			ERRO_NAO_EXISTE_SALDO_TITULO = 70,
            ERRO_DADOS_CHEQUE = 71,
            ERRO_RECIBO_MOTIVO_BOLSA = 72,
			ERRO_DATA_INVALIDA = 73,
			ERRO_USANDO_TIPO_DESCONTO = 74,
            ERRO_TIPO_FINANCEIRO_DIFERENTE = 75,
            ERRO_LOCAL_BANCO_OBRIGATORIO = 76,
            ERRO_TAXA_BANCARIA_OBRIGATORIO = 77,
            ERRO_NAO_EXISTE_LOCALMOVTO_CARTAO = 78,
            ERRO_PLANO_TAXBANC_NULL = 79,
            ERRO_NAO_EXISTE_TITULO_BAIXA_AUTOMATICA = 80,
            ERRO_EXISTE_BAIXA_TITULO_TROCA_FINANCEIRA = 81,
            ERRO_TITULO_EMITIDO_BOLETO = 82,
            ERRO_TRIGGER_ALTERAR_LOCAL_MOVIMENTO = 83,
            ERRO_TRIGGER_DELETAR_LOCAL_MOVIMENTO = 84,
            ERRO_TRIGGER_INSERIR_LOCAL_MOVIMENTO = 85,
            ERRO_TITULOS_VALIDA_RECIBO_AGRUPADO_NOTFOUND = 86,
            ERRO_AGRUPAR_TITULOS_ALUNOS_DIFERENTES = 87,
            ERRO_AGRUPAR_TITULOS_RESPONSAVEIS_DIFERENTES = 88,
            ERRO_PLANO_MATERIAL_NULL = 89,
            ITEM_NAO_ENCONTRADO = 90,
            ERRO_DELETE_NOTA_MATERIAL_WITH_CONTRATO = 91,
            ERRO_CANCEL_NOTA_MATERIAL_WITH_CONTRATO = 92,
            ERRO_ALTERAR_CONTRATO_WITH_NOTA_MATERIAL = 93,
            ERRO_USUARIO_MASTER = 94

        }

        public TipoErro tipoErro;

        public FinanceiroBusinessException(String msg, Exception ex, TipoErro erro, bool mostraStackTrace)
            : base(msg, ex, mostraStackTrace)
        {
            tipoErro = erro;
        }
    }
}
