//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundacaoFisk.SGF.GenericModel
{
    
    public partial class ListaNaoInscrito
    {
         public string no_pessoa {get;set;}
         public bool inscrito { get; set; }
         public string dc_email_cadastro { get; set; }
         public bool id_inscrito { get; set; }
         public string tipo_cadastro
         {
             get
             {
                 string retorno = "";
                 if (id_cadastro > 0)
                     switch (id_cadastro)
                     {
                         case (int)MalaDireta.TipoCadastro.PROSPECT: retorno = "Prospect"; break;
                         case (int)MalaDireta.TipoCadastro.ALUNO: retorno = "Aluno"; break;
                         case (int)MalaDireta.TipoCadastro.CLIENTE: retorno = "Cliente"; break;
                         case (int)MalaDireta.TipoCadastro.PESSOARELACIONADA: retorno = "Pessoa Relacionada"; break;
                         case (int)MalaDireta.TipoCadastro.FUNCIONARIOPROFESSOR: retorno = "Funcionário/Professor"; break;
                     }
                 return retorno;
             }
         }
    }
}
