//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Web;

namespace FundacaoFisk.SGF.GenericModel
{

    public partial class MalaDireta
    {
        public enum TipoCadastro
        {
            PROSPECT  = 1,
            ALUNO = 2,
            CLIENTE = 3,
            PESSOARELACIONADA = 4,
            FUNCIONARIOPROFESSOR = 5,
            ALUNOINADIMPLENTE = 6
        }

        public enum TipoProfissao
        {
            CYBER = 1,
            COORDENADOR = 2,
            PROFESSOR = 3,
            FUNCIONARIO_PROFESSOR = 4
        }

        public string dc_hr_inicial { get; set; }
        public string dc_hr_fim { get; set; }
        public int qtd_enderecos_enviados { get; set; }
        public int id_tipo_profissao { get; set; }
        public List<int> cd_tipo_papel { get; set; }
        public int cd_midia { get; set; }

        public DateTime? dt_matricula { get; set; }
        public DateTime? dt_inicio_turma { get; set; }
        public int cd_tipo_turma { get; set; }
        public bool existe_turmas_filhas { get; set; }
        public int cd_situacao_turma { get; set; }
        public int cd_faixa_etaria { get; set; }
        public bool id_prospect_inativo { get; set; }
        public List<int> cd_situacao_aluno { get; set; }
        public int cd_turma { get; set; }
        public List<int> cd_dia_semana { get; set; }
        public List<int> cd_grau_parentesco { get; set; }
        public string json_nome_arquivos { get; set; }
        public Dictionary<string, string> nome_arquivos_anexo { get; set; }
        public string nome { get; set; }
        public DateTime? dtIniPeriodo { get; set; }
        public DateTime? dtFimPeriodo { get; set; }
        public int cd_escolaridade { get; set; }
        public int idade { get; set; }
        public int cd_pessoa_responsavel { get; set; }
        public int cd_localidade { get; set; }
        public int cd_cidade { get; set; }
        public int cd_estado { get; set; }

        public string no_login
        {
            get
            {
                if (this.Usuario != null)
                    return this.Usuario.no_login;
                else
                    return "";
            }
        }

        public string dta_mala_direta
        {
            get
            {
                return String.Format("{0:dd/MM/yyyy}", dt_mala_direta);
            }
        }

        public virtual ICollection<ListaEnderecoMala> ListasEnderecoMalaComNaoInscritos { get; set; }
        public virtual ICollection<ListaEnderecoMala> ListasEnderecoMalaView { get; set; }
        public string tx_msg_completa
        {
            get
            {
                return "<div>" + tx_msg_body + "</div><div>" + tx_msg_footer +"</div>";
            }
        }
    }
}
